import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = { title: "About Us | 3rd Generation Hatton Garden Jewellers", description: "Learn about Hatton Garden Fine Jewellers - a 3rd generation family business with GIA-certified gemologists. Crafting bespoke jewellery since 2005.", openGraph: { title: "About Us | Hatton Garden Fine Jewellers", description: "Three generations of fine jewellery craftsmanship in Hatton Garden." } };

export default function AboutPage() {
  return (<>
    <section className="hero-gradient py-20 lg:py-28"><div className="container-width"><div className="max-w-3xl"><span className="text-accent font-semibold tracking-wider uppercase text-sm">About Us</span><h1 className="text-4xl md:text-5xl font-bold text-white mt-4 mb-6">Three Generations of Craftsmanship</h1><p className="text-xl text-gray-200 leading-relaxed">A family business rooted in tradition, driven by passion and committed to creating jewellery that will be treasured for generations to come.</p></div></div></section>
    <section className="section-padding bg-white"><div className="container-width"><div className="grid lg:grid-cols-2 gap-16 items-center">
      <div><span className="text-accent font-semibold tracking-wider uppercase text-sm">Our Story</span><h2 className="text-3xl md:text-4xl font-bold text-primary mt-4 mb-4">Crafted With Love Since 2005</h2><div className="gold-line mb-6"></div>
        <p className="text-lg text-gray-600 mb-6 leading-relaxed">Hatton Garden Fine Jewellers was established in 2005, but our family&apos;s story in the jewellery trade stretches back three generations. Our grandfather first set up his bench in Hatton Garden in the 1960s, and the craft has been in our blood ever since.</p>
        <p className="text-gray-600 mb-6 leading-relaxed">Today, our team of GIA-certified gemologists and master craftspeople continues that tradition of excellence. We have crafted over 5,000 bespoke rings, helped thousands of couples celebrate their love, and built a reputation as one of Hatton Garden&apos;s most trusted independent jewellers.</p>
        <p className="text-gray-600 leading-relaxed">What sets us apart is our personal approach. Every client meets directly with our gemologists and designers. There are no salespeople, no pressure — just expert guidance and genuine care for helping you create something truly special.</p>
      </div>
      <div className="bg-gray-50 p-8 lg:p-12 rounded-sm"><div className="grid grid-cols-2 gap-8"><div className="text-center p-6 bg-white rounded-sm shadow-sm"><div className="stat-number">2005</div><p className="text-gray-600 mt-2 font-medium">Established</p></div><div className="text-center p-6 bg-white rounded-sm shadow-sm"><div className="stat-number">5k+</div><p className="text-gray-600 mt-2 font-medium">Rings Crafted</p></div><div className="text-center p-6 bg-white rounded-sm shadow-sm"><div className="stat-number">3</div><p className="text-gray-600 mt-2 font-medium">Generations</p></div><div className="text-center p-6 bg-white rounded-sm shadow-sm"><div className="stat-number">100%</div><p className="text-gray-600 mt-2 font-medium">Bespoke</p></div></div></div>
    </div></div></section>
    <section className="section-padding bg-gray-50"><div className="container-width"><div className="text-center mb-16"><span className="text-accent font-semibold tracking-wider uppercase text-sm">Our Values</span><h2 className="text-3xl md:text-4xl font-bold text-primary mt-4 mb-4">What We Stand For</h2><div className="gold-line-center mb-6"></div></div>
      <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
        <div className="card-premium p-8"><div className="w-16 h-16 bg-primary/10 rounded-full flex items-center justify-center mb-6"><svg className="w-8 h-8 text-primary" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M5 3v4M3 5h4M6 17v4m-2-2h4m5-16l2.286 6.857L21 12l-5.714 2.143L13 21l-2.286-6.857L5 12l5.714-2.143L13 3z" /></svg></div><h3 className="text-xl font-bold text-primary mb-3">Craftsmanship</h3><p className="text-gray-600">Every piece is handcrafted by our master jewellers using techniques passed down through three generations, combined with modern precision technology.</p></div>
        <div className="card-premium p-8"><div className="w-16 h-16 bg-primary/10 rounded-full flex items-center justify-center mb-6"><svg className="w-8 h-8 text-primary" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" /></svg></div><h3 className="text-xl font-bold text-primary mb-3">Trust</h3><p className="text-gray-600">GIA certification, transparent pricing and honest advice. We have built our reputation on trust and we protect it fiercely.</p></div>
        <div className="card-premium p-8"><div className="w-16 h-16 bg-primary/10 rounded-full flex items-center justify-center mb-6"><svg className="w-8 h-8 text-primary" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z" /></svg></div><h3 className="text-xl font-bold text-primary mb-3">Personal Service</h3><p className="text-gray-600">You will work directly with our gemologists and designers, not salespeople. Every client receives undivided attention and care.</p></div>
        <div className="card-premium p-8"><div className="w-16 h-16 bg-primary/10 rounded-full flex items-center justify-center mb-6"><svg className="w-8 h-8 text-primary" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M3.055 11H5a2 2 0 012 2v1a2 2 0 002 2 2 2 0 012 2v2.945M8 3.935V5.5A2.5 2.5 0 0010.5 8h.5a2 2 0 012 2 2 2 0 104 0 2 2 0 012-2h1.064M15 20.488V18a2 2 0 012-2h3.064M21 12a9 9 0 11-18 0 9 9 0 0118 0z" /></svg></div><h3 className="text-xl font-bold text-primary mb-3">Ethics</h3><p className="text-gray-600">All our diamonds are ethically sourced and conflict-free. We also offer lab-grown alternatives for environmentally conscious clients.</p></div>
        <div className="card-premium p-8"><div className="w-16 h-16 bg-primary/10 rounded-full flex items-center justify-center mb-6"><svg className="w-8 h-8 text-primary" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" /></svg></div><h3 className="text-xl font-bold text-primary mb-3">Legacy</h3><p className="text-gray-600">We create jewellery designed to be passed down through generations, just as our craft has been passed down through ours.</p></div>
        <div className="card-premium p-8"><div className="w-16 h-16 bg-primary/10 rounded-full flex items-center justify-center mb-6"><svg className="w-8 h-8 text-primary" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M13 10V3L4 14h7v7l9-11h-7z" /></svg></div><h3 className="text-xl font-bold text-primary mb-3">Innovation</h3><p className="text-gray-600">While we honour traditional techniques, we also embrace modern technology including 3D design and CAD modelling for precision results.</p></div>
      </div>
    </div></section>
    <section className="section-padding bg-white"><div className="container-width"><div className="text-center mb-16"><span className="text-accent font-semibold tracking-wider uppercase text-sm">Our Location</span><h2 className="text-3xl md:text-4xl font-bold text-primary mt-4 mb-4">In the Heart of Hatton Garden</h2><div className="gold-line-center mb-6"></div><p className="text-lg text-gray-600 max-w-3xl mx-auto">London&apos;s legendary diamond quarter has been home to jewellers and gem dealers for over 500 years. We are proud to continue that heritage from our workshop at 88 Hatton Garden.</p></div>
      <div className="grid md:grid-cols-2 gap-8">
        <div className="bg-gradient-to-br from-primary to-secondary p-8 lg:p-12 rounded-sm text-white"><h3 className="text-2xl font-bold mb-4">Find Us</h3><address className="not-italic text-gray-200 mb-6"><strong className="text-white">Hatton Garden Fine Jewellers</strong><br />88 Hatton Garden<br />Holborn, London EC1N 8PN</address><div className="space-y-3 text-gray-200"><p><strong className="text-accent">Opening Hours:</strong></p><p>Mon-Fri: 9:30am - 5:30pm</p><p>Sat: 10am - 4pm</p><p>Sun: Closed</p></div></div>
        <div className="bg-gray-50 p-8 lg:p-12 rounded-sm border-t-4 border-accent"><h3 className="text-2xl font-bold text-primary mb-4">Getting Here</h3><ul className="space-y-3 text-gray-600"><li className="flex items-center gap-2"><svg className="w-4 h-4 text-accent" fill="currentColor" viewBox="0 0 20 20"><path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" /></svg>Chancery Lane — 2 minute walk</li><li className="flex items-center gap-2"><svg className="w-4 h-4 text-accent" fill="currentColor" viewBox="0 0 20 20"><path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" /></svg>Farringdon — 4 minute walk</li><li className="flex items-center gap-2"><svg className="w-4 h-4 text-accent" fill="currentColor" viewBox="0 0 20 20"><path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" /></svg>Holborn — 5 minute walk</li></ul></div>
      </div></div></section>
    <section className="section-padding bg-primary"><div className="container-width text-center"><h2 className="text-3xl md:text-4xl font-bold text-white mb-4">Begin Your Journey</h2><p className="text-xl text-gray-200 mb-8 max-w-2xl mx-auto">Book a complimentary consultation and let our family help you create something truly extraordinary.</p><div className="flex flex-col sm:flex-row justify-center gap-4"><Link href="/jeweller-hatton-garden/contact" className="btn-accent">Book Free Consultation</Link><a href="tel:02079467750" className="btn-outline border-white text-white hover:bg-white hover:text-primary">Call 020 7946 7750</a></div></div></section>
  </>);
}
