import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "What We Offer | Books, Events, Club & Rare Editions",
  description: "Discover what Bloomsbury Books offers: 20,000+ curated titles, author events, book club, children's corner, rare books and gift services.",
  openGraph: { title: "What We Offer | Bloomsbury Books", description: "Independent bookshop services in the heart of Bloomsbury, London." },
};

export default function ServicesPage() {
  const services = [
    { id: "curated-selection", title: "Curated Book Selection", subtitle: "20,000+ Titles, Hand-Picked", description: "Our shelves are filled by booksellers, not algorithms. We stock literary fiction, translated works, poetry, philosophy, history, science, art, nature writing, cookery, and much more. Every section is curated by a specialist who reads deeply in that field. If we do not have what you need in stock, we can order any title in print and usually have it within 48 hours.", features: ["Literary and commercial fiction", "Non-fiction across all subjects", "Poetry, drama, and essays", "Staff recommendations and picks tables", "Special orders available within 48 hours", "Book tokens accepted and sold"], icon: (<svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253" /></svg>) },
    { id: "author-events", title: "Author Events & Signings", subtitle: "Meet the Writers", description: "We host two to four author events each month in our upstairs space. These range from intimate conversations with debut novelists to packed launches for established names. Events typically include a reading, a moderated discussion, and a signing. Our events programme is one of the most respected among independent bookshops in London.", features: ["Monthly author talks and readings", "Book launch events", "Signing sessions with dedicated queuing", "Moderated conversations and Q&A", "Events newsletter with advance booking", "Partnership with publishers for exclusive content"], icon: (<svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z" /></svg>) },
    { id: "book-club", title: "Book Club", subtitle: "Read, Discuss, Discover", description: "Our book club meets on the last Thursday of every month at 7pm in the shop. We choose one title each month — usually literary fiction, occasionally non-fiction — and discuss it over wine. The atmosphere is warm, the opinions are strong, and new members are always welcome. We occasionally invite the author of our chosen book to join us, which makes for unforgettable evenings.", features: ["Monthly meetings, last Thursday at 7pm", "Mix of literary fiction and non-fiction", "10% discount on the monthly pick", "Occasional author appearances", "Wine and refreshments provided", "New members welcome — no commitment required"], icon: (<svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M8 12h.01M12 12h.01M16 12h.01M21 12c0 4.418-4.03 8-9 8a9.863 9.863 0 01-4.255-.949L3 20l1.395-3.72C3.512 15.042 3 13.574 3 12c0-4.418 4.03-8 9-8s9 3.582 9 8z" /></svg>) },
    { id: "childrens-corner", title: "Children's Corner", subtitle: "Where Young Readers Begin", description: "Our dedicated children&apos;s section covers picture books, early readers, middle grade, and young adult fiction. We hold weekly story time sessions on Saturday mornings and run craft workshops during school holidays. Our children&apos;s bookseller is passionate about matching young readers with the right book at the right time — a skill that no website can replicate.", features: ["Picture books through to young adult fiction", "Weekly Saturday story time (ages 3-7)", "School holiday craft workshops", "Dedicated children&apos;s bookseller", "School visits and author workshops", "Birthday party packages available"], icon: (<svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M14.828 14.828a4 4 0 01-5.656 0M9 10h.01M15 10h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>) },
    { id: "rare-books", title: "Rare & Antiquarian Books", subtitle: "Treasures for Collectors", description: "Our rare books cabinet houses a rotating collection of first editions, signed copies, fine press editions, and antiquarian volumes. We source carefully through auctions, private sales, and estate clearances. Whether you are a serious collector or looking for a meaningful one-off gift, our rare books specialist can help you find something truly exceptional.", features: ["Signed first editions and proof copies", "Antiquarian volumes and fine press books", "Sourcing service for specific titles", "Authentication and provenance research", "Climate-controlled display and storage", "Gift certificates for rare book purchases"], icon: (<svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M5 3v4M3 5h4M6 17v4m-2-2h4m5-16l2.286 6.857L21 12l-5.714 2.143L13 21l-2.286-6.857L5 12l5.714-2.143L13 3z" /></svg>) },
    { id: "gift-wrapping", title: "Gift Wrapping & Hampers", subtitle: "The Perfect Literary Present", description: "We wrap any purchase in our signature paper at no extra charge. For something more special, our bespoke book hampers combine hand-picked titles with artisan treats, candles, and literary curiosities. We curate hampers for birthdays, weddings, new babies, housewarmings, and corporate gifts. Tell us about the recipient and we will do the rest.", features: ["Complimentary gift wrapping on all purchases", "Bespoke book hampers for any occasion", "Corporate gifting programmes", "Postal delivery across the UK", "Personalised handwritten gift messages", "Book subscription boxes available"], icon: (<svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M12 8v13m0-13V6a2 2 0 112 2h-2zm0 0V5.5A2.5 2.5 0 109.5 8H12zm-7 4h14M5 12a2 2 0 110-4h14a2 2 0 110 4M5 12v7a2 2 0 002 2h10a2 2 0 002-2v-7" /></svg>) },
  ];

  return (
    <>
      <section className="hero-gradient py-20 lg:py-28"><div className="container-width"><div className="max-w-3xl"><span className="text-accent font-semibold tracking-wider uppercase text-sm">What We Offer</span><h1 className="text-4xl md:text-5xl font-bold text-white mt-4 mb-6">Books, Events &amp; More</h1><p className="text-xl text-gray-200 leading-relaxed">Everything an independent bookshop should be — and a few things you might not expect. From rare first editions to children&apos;s story time, we have got it covered.</p></div></div></section>
      <section className="section-padding bg-white"><div className="container-width">
        <div className="text-center mb-16"><h2 className="text-3xl md:text-4xl font-bold text-primary mb-4">Our Full Offering</h2><div className="gold-line-center mb-6"></div><p className="text-lg text-gray-600 max-w-3xl mx-auto">Six reasons to visit Bloomsbury Books. We are open seven days a week and our booksellers are always happy to help you find your next read.</p></div>
        <div className="space-y-16">{services.map((service, index) => (<div key={service.id} id={service.id} className={`grid lg:grid-cols-2 gap-12 items-center ${index % 2 === 1 ? "lg:flex-row-reverse" : ""}`}><div className={index % 2 === 1 ? "lg:order-2" : ""}><div className="text-primary mb-4">{service.icon}</div><h3 className="text-2xl md:text-3xl font-bold text-primary mb-2">{service.title}</h3><p className="text-accent font-semibold mb-4">{service.subtitle}</p><p className="text-gray-600 mb-6 leading-relaxed">{service.description}</p><ul className="space-y-3 mb-8">{service.features.map((f, i) => (<li key={i} className="flex items-start gap-3"><svg className="w-5 h-5 text-accent mt-0.5 flex-shrink-0" fill="currentColor" viewBox="0 0 20 20"><path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" /></svg><span className="text-gray-700">{f}</span></li>))}</ul><Link href="/bookshop-bloomsbury/contact" className="btn-accent">Visit Us</Link></div><div className={`bg-gray-50 p-8 lg:p-12 rounded-sm ${index % 2 === 1 ? "lg:order-1" : ""}`}><div className="aspect-video bg-gradient-to-br from-primary to-secondary rounded-sm flex items-center justify-center"><div className="text-white opacity-20 scale-150">{service.icon}</div></div></div></div>))}</div>
      </div></section>
      <section className="section-padding bg-gray-50"><div className="container-width"><div className="text-center mb-16"><span className="text-accent font-semibold tracking-wider uppercase text-sm">Your Visit</span><h2 className="text-3xl md:text-4xl font-bold text-primary mt-4 mb-4">What to Expect</h2><div className="gold-line-center mb-6"></div></div><div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8">
        <div className="text-center"><div className="w-16 h-16 bg-primary text-white rounded-full flex items-center justify-center mx-auto mb-4 text-2xl font-bold font-serif">1</div><h3 className="text-xl font-bold text-primary mb-2">Browse</h3><p className="text-gray-600">Wander our shelves at your own pace. Check the staff picks and themed displays near the entrance.</p></div>
        <div className="text-center"><div className="w-16 h-16 bg-primary text-white rounded-full flex items-center justify-center mx-auto mb-4 text-2xl font-bold font-serif">2</div><h3 className="text-xl font-bold text-primary mb-2">Ask</h3><p className="text-gray-600">Our booksellers love recommending books. Tell them what you enjoyed recently and they will find your next favourite.</p></div>
        <div className="text-center"><div className="w-16 h-16 bg-primary text-white rounded-full flex items-center justify-center mx-auto mb-4 text-2xl font-bold font-serif">3</div><h3 className="text-xl font-bold text-primary mb-2">Discover</h3><p className="text-gray-600">Check the events board for upcoming talks and signings. Join our book club or bring the little ones to story time.</p></div>
        <div className="text-center"><div className="w-16 h-16 bg-primary text-white rounded-full flex items-center justify-center mx-auto mb-4 text-2xl font-bold font-serif">4</div><h3 className="text-xl font-bold text-primary mb-2">Take Home</h3><p className="text-gray-600">We wrap gifts beautifully, order anything not in stock, and can post books anywhere in the UK.</p></div>
      </div></div></section>
      <section className="section-padding bg-primary"><div className="container-width text-center"><h2 className="text-3xl md:text-4xl font-bold text-white mb-4">Come and See Us</h2><p className="text-xl text-gray-200 mb-8 max-w-2xl mx-auto">We are open seven days a week on Great Russell Street. The kettle is always on and the books are always waiting.</p><div className="flex flex-col sm:flex-row justify-center gap-4"><Link href="/bookshop-bloomsbury/contact" className="btn-accent">Plan Your Visit</Link><a href="tel:02079461190" className="btn-outline border-white text-white hover:bg-white hover:text-primary">Call 020 7946 1190</a></div></div></section>
    </>
  );
}
