import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = { title: "Services | Portrait, Wedding & Commercial Photography", description: "Full range of photography services from Hackney Photography Studio. Portraits, weddings, commercial, events, family photography and studio hire in East London.", openGraph: { title: "Services | Hackney Photography Studio", description: "Professional photography services in Hackney. Portraits, weddings, commercial and studio hire." } };

export default function ServicesPage() {
  const services = [
    { id: "portrait", title: "Portrait Photography", subtitle: "Headshots & Personal Branding", description: "Whether you need a professional LinkedIn headshot, actor portfolio shots or personal branding images, our portrait sessions are designed to bring out the best in you. We guide you through posing and expressions to ensure you look natural and confident.", features: ["Professional headshots for LinkedIn and corporate use", "Actor and model portfolio sessions", "Personal branding and lifestyle portraits", "Professional retouching included", "Multiple outfit changes welcome", "Digital gallery delivery within 5 working days"], icon: <svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" /></svg> },
    { id: "wedding", title: "Wedding Photography", subtitle: "Documentary & Editorial", description: "We shoot weddings with a natural, documentary approach, capturing genuine moments as they unfold. We also create beautifully composed editorial portraits that you'll treasure forever. We cover weddings across London and throughout the UK.", features: ["Full day and half day packages available", "Engagement and pre-wedding shoots", "Second photographer option for larger weddings", "Online gallery with high-resolution downloads", "Album design service available", "Available for destination weddings"], icon: <svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z" /></svg> },
    { id: "commercial", title: "Commercial & Product", subtitle: "Brand & E-commerce Photography", description: "From clean product shots on white to styled lifestyle imagery, we create commercial photography that sells. We work with brands, agencies and e-commerce businesses to produce images that drive engagement and conversion.", features: ["Product photography on white or styled", "Lookbook and catalogue shoots", "Brand campaign imagery", "Food and beverage photography", "360-degree and flat-lay options", "High-volume e-commerce packages"], icon: <svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M20 7l-8-4-8 4m16 0l-8 4m8-4v10l-8 4m0-10L4 7m8 4v10M4 7v10l8 4" /></svg> },
    { id: "events", title: "Events & Corporate", subtitle: "Conferences, Launches & Parties", description: "We provide professional event photography for corporate and private events across London. Discreet, efficient and always capturing the key moments, our event photography ensures you have a professional record of your occasion.", features: ["Corporate conferences and seminars", "Awards ceremonies and gala dinners", "Product launches and exhibitions", "Charity events and fundraisers", "Private parties and celebrations", "Same-day image delivery available"], icon: <svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0z" /></svg> },
    { id: "family", title: "Family Photography", subtitle: "Natural, Relaxed Portraits", description: "Our family sessions are all about capturing genuine connections in a relaxed environment. Whether in our studio or on location around Hackney and East London, we make the experience fun for everyone &mdash; including the little ones.", features: ["Studio or on-location sessions", "Newborn and maternity photography", "Generational family portraits", "Child-friendly studio environment", "Print packages and wall art options", "Relaxed, fun atmosphere for all ages"], icon: <svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M12 4.354a4 4 0 110 5.292M15 21H3v-1a6 6 0 0112 0v1zm0 0h6v-1a6 6 0 00-9-5.197M13 7a4 4 0 11-8 0 4 4 0 018 0z" /></svg> },
    { id: "studio-hire", title: "Studio Hire", subtitle: "Professional Space for Creatives", description: "Our fully equipped Hackney studio is available for hire by photographers, filmmakers and creatives. The space features professional lighting rigs, a range of backdrops, props and a comfortable client area.", features: ["800 sq ft studio space", "Profoto lighting system included", "Multiple backdrop options", "Props and styling accessories", "Client lounge and changing area", "Half-day and full-day rates"], icon: <svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M19 21V5a2 2 0 00-2-2H7a2 2 0 00-2 2v16m14 0h2m-2 0h-5m-9 0H3m2 0h5M9 7h1m-1 4h1m4-4h1m-1 4h1m-5 10v-5a1 1 0 011-1h2a1 1 0 011 1v5m-4 0h4" /></svg> },
  ];

  return (
    <>
      <section className="hero-gradient py-20 lg:py-28"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="max-w-3xl"><span className="text-[var(--accent)] font-semibold tracking-wider uppercase text-sm">Our Services</span><h1 className="text-4xl md:text-5xl font-bold text-white mt-4 mb-6">Photography Services</h1><p className="text-xl text-gray-200 leading-relaxed">Professional photography for every occasion. Each session is tailored to your needs with expert direction, professional editing and prompt delivery.</p></div></div></section>
      <section className="py-16 lg:py-24 bg-white"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="text-center mb-16"><h2 className="text-3xl md:text-4xl font-bold text-[var(--primary)] mb-4">What We Offer</h2><div className="w-16 h-1 bg-[var(--accent)] mx-auto mb-6"></div></div><div className="space-y-16">{services.map((service, index) => (<div key={service.id} id={service.id} className={`grid lg:grid-cols-2 gap-12 items-center ${index % 2 === 1 ? "lg:flex-row-reverse" : ""}`}><div className={index % 2 === 1 ? "lg:order-2" : ""}><div className="text-[var(--primary)] mb-4">{service.icon}</div><h3 className="text-2xl md:text-3xl font-bold text-[var(--primary)] mb-2">{service.title}</h3><p className="text-[var(--accent)] font-semibold mb-4">{service.subtitle}</p><p className="text-gray-600 mb-6 leading-relaxed">{service.description}</p><ul className="space-y-3 mb-8">{service.features.map((f, i) => (<li key={i} className="flex items-start gap-3"><svg className="w-5 h-5 text-[var(--accent)] mt-0.5 flex-shrink-0" fill="currentColor" viewBox="0 0 20 20"><path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" /></svg><span className="text-gray-700">{f}</span></li>))}</ul><Link href="/photographer-hackney/contact" className="bg-[var(--accent)] text-white px-6 py-3 font-semibold rounded-sm hover:bg-[var(--accent-light)] transition-colors inline-block">Enquire Now</Link></div><div className={`bg-gray-50 p-8 lg:p-12 rounded-sm ${index % 2 === 1 ? "lg:order-1" : ""}`}><div className="aspect-video bg-gradient-to-br from-[var(--primary)] to-[var(--secondary)] rounded-sm flex items-center justify-center"><div className="text-white opacity-20 scale-150">{service.icon}</div></div></div></div>))}</div></div></section>
      <section className="py-16 lg:py-24 bg-gray-50"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="text-center mb-16"><span className="text-[var(--accent)] font-semibold tracking-wider uppercase text-sm">Our Process</span><h2 className="text-3xl md:text-4xl font-bold text-[var(--primary)] mt-4 mb-4">How We Work</h2><div className="w-16 h-1 bg-[var(--accent)] mx-auto mb-6"></div></div><div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8"><div className="text-center"><div className="w-16 h-16 bg-[var(--primary)] text-white rounded-full flex items-center justify-center mx-auto mb-4 text-2xl font-bold">1</div><h3 className="text-xl font-bold text-[var(--primary)] mb-2">Brief</h3><p className="text-gray-600">We discuss your vision, requirements and any specific needs to plan the perfect shoot.</p></div><div className="text-center"><div className="w-16 h-16 bg-[var(--primary)] text-white rounded-full flex items-center justify-center mx-auto mb-4 text-2xl font-bold">2</div><h3 className="text-xl font-bold text-[var(--primary)] mb-2">Shoot</h3><p className="text-gray-600">On the day, we handle all technical aspects while keeping things relaxed and enjoyable.</p></div><div className="text-center"><div className="w-16 h-16 bg-[var(--primary)] text-white rounded-full flex items-center justify-center mx-auto mb-4 text-2xl font-bold">3</div><h3 className="text-xl font-bold text-[var(--primary)] mb-2">Edit</h3><p className="text-gray-600">Professional colour grading, retouching and editing to bring out the best in every image.</p></div><div className="text-center"><div className="w-16 h-16 bg-[var(--primary)] text-white rounded-full flex items-center justify-center mx-auto mb-4 text-2xl font-bold">4</div><h3 className="text-xl font-bold text-[var(--primary)] mb-2">Deliver</h3><p className="text-gray-600">Your images are delivered via a private online gallery with high-resolution downloads.</p></div></div></div></section>
      <section className="py-16 lg:py-24 bg-[var(--primary)]"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center"><h2 className="text-3xl md:text-4xl font-bold text-white mb-4">Ready to Book Your Shoot?</h2><p className="text-xl text-gray-200 mb-8 max-w-2xl mx-auto">Get in touch to discuss your project or check studio availability.</p><div className="flex flex-col sm:flex-row justify-center gap-4"><Link href="/photographer-hackney/contact" className="bg-[var(--accent)] text-white px-8 py-4 font-semibold rounded-sm hover:bg-[var(--accent-light)] transition-colors">Book a Shoot</Link><a href="tel:02079460134" className="border-2 border-white text-white px-8 py-4 font-semibold rounded-sm hover:bg-white hover:text-[var(--primary)] transition-colors">Call 020 7946 0134</a></div></div></section>
    </>
  );
}
