import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Products & Services | Bread, Pastries, Cakes & Classes",
  description: "Explore our artisan products: sourdough bread, pastries, celebration cakes, wedding cakes, wholesale supply, and baking classes at Notting Hill Bakehouse.",
  openGraph: { title: "Products & Services | Notting Hill Bakehouse", description: "Artisan bread, pastries, celebration cakes, wedding cakes, wholesale supply, and baking classes in Notting Hill." },
};

export default function ServicesPage() {
  const services = [
    { id: "sourdough-bread", title: "Sourdough Bread", subtitle: "The Heart of Our Bakehouse", description: "Our sourdough is the foundation of everything we do. Each loaf begins with our ten-year-old starter — a living culture fed daily with organic stoneground flour. The dough ferments slowly for 24 hours, developing deep, complex flavour and a naturally tangy crumb. We bake in a stone-deck oven imported from France, which gives each loaf its signature blistered crust and extraordinary spring.", features: ["White, wholemeal, rye, and seeded varieties", "24-hour cold fermentation for flavour and digestibility", "Organic stoneground flour from Shipton Mill", "Stone-deck oven for authentic crust", "Sliced and unsliced options available", "Subscription service with weekly home delivery"], icon: (<svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M21 15.546c-.523 0-1.046.151-1.5.454a2.704 2.704 0 01-3 0 2.704 2.704 0 00-3 0 2.704 2.704 0 01-3 0 2.704 2.704 0 00-3 0 2.704 2.704 0 01-3 0A1.75 1.75 0 003 15.546V12a9 9 0 0118 0v3.546z" /></svg>) },
    { id: "pastries-viennoiseries", title: "Pastries & Viennoiseries", subtitle: "Hand-Laminated, French Butter", description: "Our pastry chef arrives at 4am to begin the two-day lamination process that gives our croissants their extraordinary flakiness. We use 83% fat French butter rolled into layer after layer of dough. The result: croissants with a shattering, golden crust and a soft, honeycomb interior. Alongside classic croissants, we bake pain au chocolat, almond croissants, Danish pastries, and seasonal specials.", features: ["Two-day hand lamination process", "French Isigny Sainte-Mere butter", "Classic, almond, and pain au chocolat varieties", "Danish pastries with seasonal fruit", "Ready from 7am daily", "Bulk orders for events and offices"], icon: (<svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1M21 12a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>) },
    { id: "celebration-cakes", title: "Celebration Cakes", subtitle: "Bespoke Cakes for Every Occasion", description: "Our celebration cakes are designed and baked to order. Tell us the occasion, your favourite flavours, and any design ideas, and we will create something unforgettable. Every cake is made with the same quality ingredients we use throughout the bakery — free-range eggs, real vanilla, premium chocolate, and seasonal fruit. We offer everything from elegant single-tier cakes to show-stopping multi-tier creations.", features: ["Bespoke design consultation included", "Flavours: Victoria sponge, chocolate, lemon, carrot, red velvet, and more", "Buttercream, ganache, or fondant finishes", "Dietary options: gluten-free and vegan cakes available", "Delivery available within west London", "Minimum five days notice required"], icon: (<svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M21 15.546c-.523 0-1.046.151-1.5.454a2.704 2.704 0 01-3 0 2.704 2.704 0 00-3 0 2.704 2.704 0 01-3 0 2.704 2.704 0 00-3 0 2.704 2.704 0 01-3 0A1.75 1.75 0 003 15.546V12a9 9 0 0118 0v3.546zM12 2v4m-4 0h8" /></svg>) },
    { id: "wedding-cakes", title: "Wedding Cakes", subtitle: "Your Day, Your Cake", description: "A wedding cake should be as memorable as the day itself. We work closely with every couple to design a cake that reflects their style, taste, and celebration. The process begins with a complimentary consultation and tasting session at the bakery, where you sample our flavour combinations and discuss design options. From classic tiered cakes with sugar flowers to rustic naked cakes adorned with fresh blooms, we bring your vision to life.", features: ["Complimentary consultation and tasting session", "Multi-tier, single-tier, and naked cake options", "Sugar flowers, fresh flowers, and bespoke decorations", "Flavour combinations: ask about our seasonal pairings", "Set-up and delivery to your venue included", "Minimum eight weeks notice recommended"], icon: (<svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z" /></svg>) },
    { id: "wholesale-supply", title: "Wholesale Supply", subtitle: "Fresh Delivery, Every Morning", description: "We supply artisan bread and pastries to restaurants, cafes, delis, and hotels across west London. Our wholesale customers receive the same products we sell in our shop — nothing is made differently or to a lower standard. Deliveries are made fresh every morning before 7am, so your establishment has beautiful bread on the table when doors open.", features: ["Daily delivery before 7am across west London", "Sourdough, baguettes, ciabatta, and focaccia available", "Pastry selection: croissants, pain au chocolat, and Danish", "Minimum order quantities and pricing tailored to your needs", "Dedicated account manager for every client", "Trial delivery available — no commitment"], icon: (<svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M13 16V6a1 1 0 00-1-1H4a1 1 0 00-1 1v10a1 1 0 001 1h1m8-1a1 1 0 01-1 1H9m4-1V8a1 1 0 011-1h2.586a1 1 0 01.707.293l3.414 3.414a1 1 0 01.293.707V16a1 1 0 01-1 1h-1m-6-1a1 1 0 001 1h1M5 17a2 2 0 104 0m-4 0a2 2 0 114 0m6 0a2 2 0 104 0m-4 0a2 2 0 114 0" /></svg>) },
    { id: "baking-classes", title: "Baking Classes", subtitle: "Learn From Our Bakers", description: "Our weekend baking workshops are a chance to learn the craft of real bread-making and pastry from the people who do it every day. Classes are kept small — a maximum of eight people — so everyone gets plenty of hands-on time and individual guidance. You will learn the science behind fermentation, the techniques behind lamination, and the confidence to bake brilliant bread at home.", features: ["Sourdough, croissant, and seasonal bread workshops", "Maximum eight students per class", "All ingredients and equipment provided", "Take your bakes home at the end of the session", "Includes tea, coffee, and a light lunch", "Gift vouchers available for all classes"], icon: (<svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253" /></svg>) },
  ];

  return (
    <>
      <section className="hero-gradient py-20 lg:py-28"><div className="container-width"><div className="max-w-3xl"><span className="text-accent font-semibold tracking-wider uppercase text-sm">From Our Ovens</span><h1 className="text-4xl md:text-5xl font-bold text-white mt-4 mb-6">Products &amp; Services</h1><p className="text-xl text-gray-200 leading-relaxed">Everything is made from scratch in our bakehouse using organic flour, French butter, and time-honoured technique. No shortcuts, no compromises.</p></div></div></section>

      <section className="section-padding bg-white">
        <div className="container-width">
          <div className="text-center mb-16"><h2 className="text-3xl md:text-4xl font-bold text-primary mb-4">What We Offer</h2><div className="gold-line-center mb-6"></div><p className="text-lg text-gray-600 max-w-3xl mx-auto">From our daily sourdough to bespoke wedding cakes and hands-on baking classes, discover what makes Notting Hill Bakehouse special.</p></div>
          <div className="space-y-16">
            {services.map((service, index) => (
              <div key={service.id} id={service.id} className={`grid lg:grid-cols-2 gap-12 items-center ${index % 2 === 1 ? "lg:flex-row-reverse" : ""}`}>
                <div className={index % 2 === 1 ? "lg:order-2" : ""}><div className="text-primary mb-4">{service.icon}</div><h3 className="text-2xl md:text-3xl font-bold text-primary mb-2">{service.title}</h3><p className="text-accent font-semibold mb-4">{service.subtitle}</p><p className="text-gray-600 mb-6 leading-relaxed">{service.description}</p>
                  <ul className="space-y-3 mb-8">{service.features.map((f, i) => (<li key={i} className="flex items-start gap-3"><svg className="w-5 h-5 text-accent mt-0.5 flex-shrink-0" fill="currentColor" viewBox="0 0 20 20"><path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" /></svg><span className="text-gray-700">{f}</span></li>))}</ul>
                  <Link href="/bakery-notting-hill/contact" className="btn-accent">Enquire Now</Link>
                </div>
                <div className={`bg-gray-50 p-8 lg:p-12 rounded-sm ${index % 2 === 1 ? "lg:order-1" : ""}`}><div className="aspect-video bg-gradient-to-br from-primary to-secondary rounded-sm flex items-center justify-center"><div className="text-white opacity-20 scale-150">{service.icon}</div></div></div>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section className="section-padding bg-gray-50"><div className="container-width"><div className="text-center mb-16"><span className="text-accent font-semibold tracking-wider uppercase text-sm">How It Works</span><h2 className="text-3xl md:text-4xl font-bold text-primary mt-4 mb-4">From Flour to You</h2><div className="gold-line-center mb-6"></div></div>
        <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8">
          {[{ n: "1", t: "Mix", d: "Our bakers begin at 3am, mixing organic flour, water, and our living sourdough starter by hand." }, { n: "2", t: "Ferment", d: "The dough rests for up to 24 hours. Slow fermentation develops flavour, texture, and natural keeping quality." }, { n: "3", t: "Shape", d: "Every loaf and pastry is shaped by hand. No machines, no moulds — just skilled hands and years of practice." }, { n: "4", t: "Bake", d: "Into the stone-deck oven at dawn. By 7am, the shop is filled with the aroma of freshly baked bread." }].map((s, i) => (
            <div key={i} className="text-center"><div className="w-16 h-16 bg-primary text-white rounded-full flex items-center justify-center mx-auto mb-4 text-2xl font-bold font-serif">{s.n}</div><h3 className="text-xl font-bold text-primary mb-2">{s.t}</h3><p className="text-gray-600">{s.d}</p></div>
          ))}
        </div>
      </div></section>

      <section className="section-padding bg-primary"><div className="container-width text-center"><h2 className="text-3xl md:text-4xl font-bold text-white mb-4">Ready to Order?</h2><p className="text-xl text-gray-200 mb-8 max-w-2xl mx-auto">Whether you need a daily loaf, a showstopping wedding cake, or want to learn the craft yourself, we would love to hear from you.</p>
        <div className="flex flex-col sm:flex-row justify-center gap-4"><Link href="/bakery-notting-hill/contact" className="btn-accent">Get in Touch</Link><a href="tel:02079462280" className="btn-outline border-white text-white hover:bg-white hover:text-primary">Call 020 7946 2280</a></div>
      </div></section>
    </>
  );
}
