import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "About Us | RCVS Registered Vets in Hampstead",
  description: "Learn about Hampstead Veterinary Clinic - RCVS registered veterinary practice in Hampstead, NW3. Compassionate care from experienced vets and nurses.",
  openGraph: { title: "About Us | Hampstead Veterinary Clinic", description: "RCVS registered veterinary clinic in Hampstead providing compassionate care since 2015." },
};

export default function AboutPage() {
  return (
    <>
      <section className="hero-gradient py-20 lg:py-28"><div className="container-width"><div className="max-w-3xl"><span className="text-accent font-semibold tracking-wider uppercase text-sm">About Us</span><h1 className="text-4xl md:text-5xl font-bold text-white mt-4 mb-6">Passionate About Pet Health</h1><p className="text-xl text-gray-200 leading-relaxed">RCVS registered veterinary clinic providing compassionate, expert care for the pets of Hampstead and North West London since 2015.</p></div></div></section>

      <section className="section-padding bg-white"><div className="container-width"><div className="grid lg:grid-cols-2 gap-16 items-center"><div><span className="text-accent font-semibold tracking-wider uppercase text-sm">Our Story</span><h2 className="text-3xl md:text-4xl font-bold text-primary mt-4 mb-4">Caring for Hampstead&apos;s Pets Since 2015</h2><div className="gold-line mb-6"></div><p className="text-lg text-gray-600 mb-6 leading-relaxed">Hampstead Veterinary Clinic was founded by a team of experienced veterinary surgeons who shared a vision: to create a practice where clinical excellence meets genuine compassion. Located on Heath Street in the heart of Hampstead, we have been privileged to care for thousands of local pets and their families.</p><p className="text-gray-600 mb-6 leading-relaxed">Our modern clinic is equipped with digital radiography, ultrasound, a comprehensive in-house laboratory and a fully equipped surgical theatre. But technology is only part of the story. What truly sets us apart is the care and attention our team provides to every patient and every owner.</p><p className="text-gray-600 leading-relaxed">We are proud to be ISFM Cat Friendly accredited, recognising our commitment to reducing feline stress during veterinary visits. Our separate cat waiting area and consultation rooms mean your cat&apos;s visit is as calm as possible.</p></div><div className="bg-gray-50 p-8 lg:p-12 rounded-sm"><div className="grid grid-cols-2 gap-8"><div className="text-center p-6 bg-white rounded-sm shadow-sm"><div className="stat-number">10+</div><p className="text-gray-600 mt-2 font-medium">Years of Care</p></div><div className="text-center p-6 bg-white rounded-sm shadow-sm"><div className="stat-number">8,000+</div><p className="text-gray-600 mt-2 font-medium">Registered Pets</p></div><div className="text-center p-6 bg-white rounded-sm shadow-sm"><div className="stat-number">7</div><p className="text-gray-600 mt-2 font-medium">Days Open</p></div><div className="text-center p-6 bg-white rounded-sm shadow-sm"><div className="stat-number">4.9/5</div><p className="text-gray-600 mt-2 font-medium">Google Rating</p></div></div></div></div></div></section>

      <section className="section-padding bg-gray-50"><div className="container-width"><div className="text-center mb-16"><span className="text-accent font-semibold tracking-wider uppercase text-sm">Our Values</span><h2 className="text-3xl md:text-4xl font-bold text-primary mt-4 mb-4">What Sets Us Apart</h2><div className="gold-line-center mb-6"></div></div><div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
        <div className="card-premium p-8"><div className="w-16 h-16 bg-primary/10 rounded-full flex items-center justify-center mb-6"><svg className="w-8 h-8 text-primary" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z" /></svg></div><h3 className="text-xl font-bold text-primary mb-3">Compassion First</h3><p className="text-gray-600">We treat every pet with the same care and attention we would give our own. Your pet&apos;s comfort and wellbeing are always our top priority.</p></div>
        <div className="card-premium p-8"><div className="w-16 h-16 bg-primary/10 rounded-full flex items-center justify-center mb-6"><svg className="w-8 h-8 text-primary" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9.75 17L9 20l-1 1h8l-1-1-.75-3M3 13h18M5 17h14a2 2 0 002-2V5a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" /></svg></div><h3 className="text-xl font-bold text-primary mb-3">Modern Equipment</h3><p className="text-gray-600">Digital X-ray, ultrasound, in-house lab and a fully equipped surgical theatre. We invest in technology to provide the best possible care.</p></div>
        <div className="card-premium p-8"><div className="w-16 h-16 bg-primary/10 rounded-full flex items-center justify-center mb-6"><svg className="w-8 h-8 text-primary" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M12 4.354a4 4 0 110 5.292M15 21H3v-1a6 6 0 0112 0v1zm0 0h6v-1a6 6 0 00-9-5.197M13 7a4 4 0 11-8 0 4 4 0 018 0z" /></svg></div><h3 className="text-xl font-bold text-primary mb-3">Experienced Team</h3><p className="text-gray-600">Our vets and nurses bring decades of combined experience across all aspects of companion animal medicine and surgery.</p></div>
        <div className="card-premium p-8"><div className="w-16 h-16 bg-primary/10 rounded-full flex items-center justify-center mb-6"><svg className="w-8 h-8 text-primary" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" /></svg></div><h3 className="text-xl font-bold text-primary mb-3">Convenient Hours</h3><p className="text-gray-600">Open seven days a week with extended hours on weekdays. 24/7 emergency line for urgent out-of-hours situations.</p></div>
        <div className="card-premium p-8"><div className="w-16 h-16 bg-primary/10 rounded-full flex items-center justify-center mb-6"><svg className="w-8 h-8 text-primary" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M8 12h.01M12 12h.01M16 12h.01M21 12c0 4.418-4.03 8-9 8a9.863 9.863 0 01-4.255-.949L3 20l1.395-3.72C3.512 15.042 3 13.574 3 12c0-4.418 4.03-8 9-8s9 3.582 9 8z" /></svg></div><h3 className="text-xl font-bold text-primary mb-3">Clear Communication</h3><p className="text-gray-600">We explain diagnoses and treatment options in plain language, ensuring you can make informed decisions about your pet&apos;s care.</p></div>
        <div className="card-premium p-8"><div className="w-16 h-16 bg-primary/10 rounded-full flex items-center justify-center mb-6"><svg className="w-8 h-8 text-primary" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" /></svg></div><h3 className="text-xl font-bold text-primary mb-3">Cat Friendly</h3><p className="text-gray-600">ISFM Cat Friendly accredited with dedicated cat areas. We understand feline needs and minimise stress at every visit.</p></div>
      </div></div></section>

      <section className="section-padding bg-white"><div className="container-width"><div className="text-center mb-16"><span className="text-accent font-semibold tracking-wider uppercase text-sm">Our Location</span><h2 className="text-3xl md:text-4xl font-bold text-primary mt-4 mb-4">Find Us on Heath Street</h2><div className="gold-line-center mb-6"></div><p className="text-lg text-gray-600 max-w-3xl mx-auto">Our clinic is in the heart of Hampstead village, moments from the Heath and easily accessible from Hampstead tube station.</p></div><div className="bg-gray-50 p-8 lg:p-12 rounded-sm border-t-4 border-accent max-w-2xl mx-auto"><address className="not-italic text-gray-700 text-lg mb-4"><strong>Hampstead Veterinary Clinic</strong><br />52 Heath Street<br />Hampstead, London NW3 1DN</address><p className="text-gray-600 mb-2"><strong>Opening Hours:</strong></p><p className="text-gray-600">Monday &ndash; Friday: 8:00am &ndash; 7:00pm</p><p className="text-gray-600">Saturday: 9:00am &ndash; 5:00pm</p><p className="text-gray-600 mb-4">Sunday: 10:00am &ndash; 2:00pm</p><p className="text-sm text-gray-500">24/7 emergency line available outside these hours. Nearest tube: Hampstead (Northern line). Street parking available.</p></div></div></section>

      <section className="section-padding bg-primary"><div className="container-width text-center"><h2 className="text-3xl md:text-4xl font-bold text-white mb-4">Book Your Pet&apos;s Appointment</h2><p className="text-xl text-gray-200 mb-8 max-w-2xl mx-auto">Whether it&apos;s a routine check-up or a health concern, our team is here to help.</p><div className="flex flex-col sm:flex-row justify-center gap-4"><Link href="/vet-hampstead/contact" className="btn-accent">Book Appointment</Link><a href="tel:02079465670" className="btn-outline border-white text-white hover:bg-white hover:text-primary">Call 020 7946 5670</a></div></div></section>
    </>
  );
}
