import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = { title: "Physiotherapy Services | Sports Injuries, Back Pain & Rehabilitation", description: "Full range of physiotherapy services in Richmond. Sports injuries, back and neck pain, post-surgery rehab, acupuncture, massage therapy, and women's health physio. HCPC registered." };

export default function ServicesPage() {
  const services = [
    { id: "sports-injury-treatment", title: "Sports Injury Treatment", subtitle: "Get Back in the Game", description: "Whether you're a weekend runner or a professional athlete, sports injuries can be frustrating. Our physiotherapists are experienced in diagnosing and treating the full range of sports injuries, from acute trauma to overuse conditions. We'll get you back to your sport safely and help prevent reinjury.", features: ["Ligament sprains and muscle strains", "Tendinopathy and tendon injuries", "Fracture rehabilitation", "Running injury assessment and biomechanics", "Return-to-sport programmes", "Injury prevention screening"], icon: "M13 10V3L4 14h7v7l9-11h-7z" },
    { id: "back-neck-pain", title: "Back & Neck Pain", subtitle: "Expert Spinal Care", description: "Back and neck pain affects most people at some point. Our physiotherapists carry out thorough assessments to identify the root cause of your pain and create a targeted treatment plan. We combine hands-on therapy with exercise prescription and education to give you lasting relief.", features: ["Lower back pain and sciatica", "Neck pain and cervicogenic headaches", "Disc problems and nerve pain", "Postural assessment and correction", "Workplace ergonomic advice", "Chronic pain management strategies"], icon: "M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" },
    { id: "post-surgery-rehabilitation", title: "Post-Surgery Rehabilitation", subtitle: "Optimise Your Recovery", description: "Rehabilitation after surgery is crucial for achieving the best possible outcome. We work closely with surgeons and consultants to deliver structured rehab programmes that restore your strength, mobility, and confidence. From joint replacements to spinal surgery, we guide you through every stage of recovery.", features: ["Hip and knee replacement rehabilitation", "ACL and other knee ligament surgery rehab", "Shoulder surgery recovery programmes", "Spinal surgery rehabilitation", "Milestone-based progression plans", "Regular communication with your surgeon"], icon: "M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z" },
    { id: "acupuncture", title: "Acupuncture", subtitle: "Evidence-Based Pain Relief", description: "Western medical acupuncture is a proven technique for pain relief and enhanced recovery. Unlike traditional Chinese acupuncture, our approach is grounded in anatomy and neurophysiology. Fine needles are inserted at specific points to stimulate the body's natural pain-relieving mechanisms.", features: ["Musculoskeletal pain relief", "Headache and migraine management", "Chronic pain conditions", "Muscle tension and trigger points", "Enhanced recovery from injury", "Delivered by trained physiotherapists"], icon: "M19.428 15.428a2 2 0 00-1.022-.547l-2.387-.477a6 6 0 00-3.86.517l-.318.158a6 6 0 01-3.86.517L6.05 15.21a2 2 0 00-1.806.547M8 4h8l-1 1v5.172a2 2 0 00.586 1.414l5 5c1.26 1.26.367 3.414-1.415 3.414H4.828c-1.782 0-2.674-2.154-1.414-3.414l5-5A2 2 0 009 10.172V5L8 4z" },
    { id: "massage-therapy", title: "Massage Therapy", subtitle: "Hands-On Treatment for Recovery", description: "Our qualified therapists offer sports massage, deep tissue massage, and myofascial release to complement your physiotherapy treatment or as a standalone service. Whether you need recovery from intense training, relief from muscle tension, or treatment for a soft tissue injury, we can help.", features: ["Sports massage for athletes", "Deep tissue therapy", "Myofascial release techniques", "Pre and post-event massage", "Chronic muscle tension treatment", "Flexibility and mobility improvement"], icon: "M7 11.5V14m0-2.5v-6a1.5 1.5 0 113 0m-3 6a1.5 1.5 0 00-3 0v2a7.5 7.5 0 0015 0v-5a1.5 1.5 0 00-3 0m-6-3V11m0-5.5v-1a1.5 1.5 0 013 0v1m0 0V11m0-5.5a1.5 1.5 0 013 0v3m0 0V11" },
    { id: "womens-health-physio", title: "Women's Health Physiotherapy", subtitle: "Specialist Pelvic Health Care", description: "Our women's health physiotherapists provide expert, sensitive care for pelvic floor dysfunction, pregnancy-related conditions, and postnatal recovery. We understand these issues can be difficult to talk about, and we create a supportive, private environment for your treatment.", features: ["Pelvic floor assessment and rehabilitation", "Urinary incontinence treatment", "Pregnancy-related back and pelvic pain", "Postnatal recovery and diastasis recti", "Pelvic organ prolapse management", "Pre and postnatal exercise guidance"], icon: "M12 4.354a4 4 0 110 5.292M15 21H3v-1a6 6 0 0112 0v1zm0 0h6v-1a6 6 0 00-9-5.197M13 7a4 4 0 11-8 0 4 4 0 018 0z" },
  ];

  return (
    <>
      <section className="hero-gradient py-20 lg:py-28"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="max-w-3xl"><span className="text-[var(--accent)] font-semibold tracking-wider uppercase text-sm">Our Services</span><h1 className="text-4xl md:text-5xl font-bold text-white mt-4 mb-6 font-serif">Physiotherapy Services in Richmond</h1><p className="text-xl text-gray-200 leading-relaxed">Evidence-based physiotherapy from HCPC registered practitioners. Self-referral welcome — no GP letter needed.</p></div></div></section>

      <section className="py-16 lg:py-24 bg-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16"><h2 className="text-3xl md:text-4xl font-bold text-[var(--primary)] mb-4 font-serif">Our Treatments</h2><div className="w-16 h-1 bg-[var(--accent)] mx-auto mb-6"></div><p className="text-lg text-gray-600 max-w-3xl mx-auto">From acute sports injuries to chronic conditions, our team of specialist physiotherapists delivers personalised, evidence-based treatment in a modern, welcoming clinic.</p></div>
          <div className="space-y-16">
            {services.map((service, index) => (
              <div key={service.id} id={service.id} className={`grid lg:grid-cols-2 gap-12 items-center`}>
                <div className={index % 2 === 1 ? "lg:order-2" : ""}><div className="text-[var(--primary)] mb-4"><svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d={service.icon} /></svg></div><h3 className="text-2xl md:text-3xl font-bold text-[var(--primary)] mb-2 font-serif">{service.title}</h3><p className="text-[var(--accent)] font-semibold mb-4">{service.subtitle}</p><p className="text-gray-600 mb-6 leading-relaxed">{service.description}</p><ul className="space-y-3 mb-8">{service.features.map((f,i) => (<li key={i} className="flex items-start gap-3"><svg className="w-5 h-5 text-[var(--accent)] mt-0.5 flex-shrink-0" fill="currentColor" viewBox="0 0 20 20"><path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" /></svg><span className="text-gray-700">{f}</span></li>))}</ul><Link href="/physio-richmond/contact" className="bg-[var(--accent)] text-white px-8 py-3 font-semibold rounded-sm hover:bg-[var(--accent-light)] transition-colors inline-block">Book Appointment</Link></div>
                <div className={`bg-gray-50 p-8 lg:p-12 rounded-sm ${index % 2 === 1 ? "lg:order-1" : ""}`}><div className="aspect-video bg-gradient-to-br from-[var(--primary)] to-[var(--secondary)] rounded-sm flex items-center justify-center"><div className="text-white opacity-20 scale-150"><svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d={service.icon} /></svg></div></div></div>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section className="py-16 lg:py-24 bg-gray-50"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="text-center mb-16"><span className="text-[var(--accent)] font-semibold tracking-wider uppercase text-sm">Your Journey</span><h2 className="text-3xl md:text-4xl font-bold text-[var(--primary)] mt-4 mb-4 font-serif">What to Expect</h2><div className="w-16 h-1 bg-[var(--accent)] mx-auto mb-6"></div></div><div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8">{[{ n:"1", t:"Book", d:"Self-refer directly — no GP letter needed. Book online or call us." },{ n:"2", t:"Assessment", d:"Thorough 45-minute initial assessment to understand your condition and goals." },{ n:"3", t:"Treatment", d:"Hands-on therapy, exercise prescription, and education tailored to you." },{ n:"4", t:"Recovery", d:"Ongoing support, progress reviews, and a clear plan to keep you improving." }].map((s) => (<div key={s.n} className="text-center"><div className="w-16 h-16 bg-[var(--primary)] text-white rounded-full flex items-center justify-center mx-auto mb-4 text-2xl font-bold font-serif">{s.n}</div><h3 className="text-xl font-bold text-[var(--primary)] mb-2 font-serif">{s.t}</h3><p className="text-gray-600">{s.d}</p></div>))}</div></div></section>

      <section className="py-16 lg:py-24 bg-[var(--primary)]"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center"><h2 className="text-3xl md:text-4xl font-bold text-white mb-4 font-serif">Ready to Book Your Appointment?</h2><p className="text-xl text-gray-200 mb-8 max-w-2xl mx-auto">Self-referral welcome. No GP letter needed. Early morning and evening appointments available.</p><div className="flex flex-col sm:flex-row justify-center gap-4"><Link href="/physio-richmond/contact" className="bg-[var(--accent)] text-white px-8 py-4 font-semibold rounded-sm hover:bg-[var(--accent-light)] transition-colors inline-block">Book Appointment</Link><a href="tel:02079465678" className="border-2 border-white text-white px-8 py-4 font-semibold rounded-sm hover:bg-white hover:text-[var(--primary)] transition-colors inline-block">Call 020 7946 5678</a></div></div></section>

      <section className="py-8 bg-gray-100"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="bg-gray-50 border border-gray-200 rounded-sm p-4 text-sm text-gray-600"><p><strong>HCPC Registered:</strong> All physiotherapists are HCPC registered and CSP members. Treatments are subject to clinical assessment. Results may vary between individuals.</p></div></div></section>
    </>
  );
}
