import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = { title: "FAQ | Architecture Questions Answered", description: "Frequently asked questions about working with Shoreditch Architecture Studio. Learn about our process, fees, planning applications and what to expect.", openGraph: { title: "FAQ | Shoreditch Architecture Studio", description: "Common questions about our architecture services in Shoreditch." } };

export default function FAQPage() {
  const faqs = [
    { category: "Working With Us", questions: [
      { question: "What happens at the initial consultation?", answer: "We offer a free initial consultation, either at our Shoreditch studio or at your site. We will discuss your project brief, look at the property, talk through your budget and timeline, and give you an honest assessment of what is achievable. There is no obligation — it is simply a chance for us to understand your project and for you to meet us." },
      { question: "How much do architects charge?", answer: "Our fees are typically calculated as a percentage of the construction cost, ranging from 8-12% depending on the project scope and complexity. For smaller projects such as extensions and loft conversions, we offer fixed-fee packages so you know exactly what you will pay from the outset. We always provide a detailed fee proposal before any work begins." },
      { question: "How long does a typical project take?", answer: "Timescales vary significantly depending on the project. A straightforward rear extension might take 3-4 months from initial design to planning approval, while a full renovation or new build could take 6-12 months through the design and planning stages. We will give you a realistic programme at the start of your project." },
      { question: "Do I need an architect for my project?", answer: "While not legally required for most projects, an architect adds significant value. We maximise your space, navigate the planning system, ensure building regulations compliance, manage the construction process and ultimately deliver a better-quality result. For listed buildings and larger developments, professional architectural input is essential." },
    ] },
    { category: "Planning & Regulations", questions: [
      { question: "Do I need planning permission?", answer: "It depends on your project. Many extensions and loft conversions fall under Permitted Development rights and do not require a planning application. However, if your property is in a conservation area, is a listed building, or if the proposed works exceed certain size limits, you will need planning permission. We assess this during the initial consultation." },
      { question: "What is your planning approval rate?", answer: "We have a 95% planning approval rate across all project types. This high success rate comes from our thorough understanding of local planning policies, careful pre-application discussions with planning officers, and design proposals that demonstrate clear design rationale and context sensitivity." },
      { question: "What are building regulations?", answer: "Building regulations are separate from planning permission and ensure that buildings meet minimum standards for structural safety, fire safety, energy efficiency, ventilation and accessibility. Almost all building work requires building regulations approval. We coordinate with structural engineers and building control to ensure full compliance." },
      { question: "Can you help with a listed building?", answer: "Yes, we have extensive experience with listed buildings and properties in conservation areas across East London. Listed building consent is required for any alterations that affect the character of a listed building. We work sensitively with historic fabric and have strong relationships with conservation officers at Hackney and neighbouring boroughs." },
    ] },
    { category: "Design & Construction", questions: [
      { question: "Will I see 3D visuals of my project?", answer: "Yes, we provide 3D visualisations for all projects as part of the design process. These help you understand the spatial qualities of the design, make decisions about materials and finishes, and see exactly what the finished project will look like before construction begins." },
      { question: "Do you manage the building work?", answer: "We offer a full contract administration service where we tender the project to trusted contractors, administer the building contract, carry out regular site inspections and manage the project through to completion. This ensures the design intent is maintained on site and gives you professional oversight of the construction process." },
      { question: "Can you recommend a builder?", answer: "Yes, we have an established network of trusted contractors, structural engineers, quantity surveyors and specialist tradespeople whom we have worked with over many years. We always recommend competitive tendering — typically inviting three contractors to price the project — to ensure you receive best value." },
      { question: "What sustainable design options do you offer?", answer: "Sustainability is integral to our practice. We incorporate passive design strategies, high-performance insulation, air source heat pumps, solar panels, green roofs, natural ventilation and sustainable materials into our projects. We can advise on EPC improvements, retrofit strategies and Passivhaus principles depending on your priorities and budget." },
    ] },
    { category: "Fees & Process", questions: [
      { question: "Is the initial consultation really free?", answer: "Yes, the initial consultation is completely free with no obligation. We believe it is important for both parties to meet, discuss the project and understand whether we are the right fit before any commitment is made." },
      { question: "What are your RIBA work stages?", answer: "We follow the RIBA Plan of Work, the industry-standard framework for architectural projects. The stages are: Stage 0 (Strategic Definition), Stage 1 (Preparation and Briefing), Stage 2 (Concept Design), Stage 3 (Spatial Coordination), Stage 4 (Technical Design), Stage 5 (Manufacturing and Construction), Stage 6 (Handover) and Stage 7 (Use). We explain each stage clearly as your project progresses." },
      { question: "Do you have professional indemnity insurance?", answer: "Yes, we carry full professional indemnity insurance as required by RIBA and ARB. This protects you in the unlikely event of any professional negligence. We are happy to provide details of our cover upon request." },
    ] },
  ];

  const faqSchema = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faqs.flatMap((c) => c.questions.map((q) => ({ "@type": "Question", name: q.question, acceptedAnswer: { "@type": "Answer", text: q.answer } }))) };

  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} />
      <section className="hero-gradient py-20 lg:py-28"><div className="container-width"><div className="max-w-3xl"><span className="text-[var(--accent)] font-semibold tracking-wider uppercase text-sm">FAQ</span><h1 className="text-4xl md:text-5xl font-bold text-white mt-4 mb-6">Frequently Asked Questions</h1><p className="text-xl text-gray-200 leading-relaxed">Everything you need to know about working with our Shoreditch architecture studio.</p></div></div></section>

      <section className="section-padding bg-white"><div className="container-width"><div className="max-w-4xl mx-auto">{faqs.map((category, ci) => (<div key={ci} className="mb-12"><h2 className="text-2xl font-bold text-[var(--primary)] mb-6 flex items-center gap-3"><div className="w-1 h-8 bg-[var(--accent)]"></div>{category.category}</h2><div className="space-y-1">{category.questions.map((faq, fi) => (<details key={fi} className="group bg-gray-50 rounded-sm overflow-hidden"><summary className="faq-question p-6 list-none cursor-pointer"><span className="flex-1 pr-4">{faq.question}</span><svg className="w-5 h-5 text-[var(--accent)] flex-shrink-0 transition-transform duration-300 group-open:rotate-180" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" /></svg></summary><div className="px-6 pb-6"><p className="text-gray-600 leading-relaxed">{faq.answer}</p></div></details>))}</div></div>))}</div></div></section>

      <section className="section-padding bg-gray-50"><div className="container-width"><div className="max-w-3xl mx-auto text-center"><h2 className="text-3xl font-bold text-[var(--primary)] mb-4">Still Have Questions?</h2><div className="gold-line-center mb-6"></div><p className="text-lg text-gray-600 mb-8">We are always happy to discuss your project and answer any questions. Get in touch and we will respond within 24 hours.</p><div className="flex flex-col sm:flex-row justify-center gap-4"><Link href="/architect-shoreditch/contact" className="btn-accent">Contact Us</Link><a href="tel:02079466901" className="btn-outline">Call 020 7946 6901</a></div></div></div></section>

      <section className="section-padding bg-[var(--primary)]"><div className="container-width text-center"><h2 className="text-3xl md:text-4xl font-bold text-white mb-4">Ready to Start Your Project?</h2><p className="text-xl text-gray-200 mb-8 max-w-2xl mx-auto">Book a free initial consultation at our Shoreditch studio. No obligation, just honest advice about your project.</p><Link href="/architect-shoreditch/contact" className="btn-accent">Book a Consultation</Link></div></section>
    </>
  );
}
