import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Reservations & Contact | Book Your Table",
  description: "Reserve a table at Soho Sushi Kitchen on Wardour Street, Soho. Call 020 7946 3380 or book online. Open 7 days a week for lunch and dinner. Private dining available.",
  openGraph: { title: "Reservations | Soho Sushi Kitchen", description: "Book your table at Soho Sushi Kitchen. Call 020 7946 3380 or reserve online. Wardour Street, Soho." },
};

export default function ContactPage() {
  return (
    <>
      <section className="hero-gradient py-20 lg:py-28"><div className="container-width"><div className="max-w-3xl"><span className="text-accent font-semibold tracking-wider uppercase text-sm">Reservations</span><h1 className="text-4xl md:text-5xl font-bold text-white mt-4 mb-6">Reserve Your Table</h1><p className="text-xl text-gray-200 leading-relaxed">Book your table at Soho Sushi Kitchen. For omakase and private dining, please book at least 48 hours in advance. Walk-ins are welcome at the sushi bar for lunch.</p></div></div></section>

      <section className="section-padding bg-white"><div className="container-width"><div className="grid lg:grid-cols-2 gap-16">
        <div><h2 className="text-2xl md:text-3xl font-bold text-primary mb-2">Make a Reservation</h2><p className="text-gray-600 mb-8">Fill in the form below and we&apos;ll confirm your booking by email or phone within two hours.</p>
          <form className="space-y-6">
            <div className="grid md:grid-cols-2 gap-6"><div><label htmlFor="firstName" className="form-label">First Name *</label><input type="text" id="firstName" name="firstName" required className="form-input" placeholder="Alex" /></div><div><label htmlFor="lastName" className="form-label">Last Name *</label><input type="text" id="lastName" name="lastName" required className="form-input" placeholder="Smith" /></div></div>
            <div className="grid md:grid-cols-2 gap-6"><div><label htmlFor="email" className="form-label">Email Address *</label><input type="email" id="email" name="email" required className="form-input" placeholder="alex@example.com" /></div><div><label htmlFor="phone" className="form-label">Phone Number *</label><input type="tel" id="phone" name="phone" required className="form-input" placeholder="07123 456789" /></div></div>
            <div className="grid md:grid-cols-2 gap-6"><div><label htmlFor="date" className="form-label">Preferred Date *</label><input type="date" id="date" name="date" required className="form-input" /></div><div><label htmlFor="time" className="form-label">Preferred Time *</label><select id="time" name="time" required className="form-input"><option value="">Select time</option><option value="12:00">12:00 pm</option><option value="12:30">12:30 pm</option><option value="13:00">1:00 pm</option><option value="13:30">1:30 pm</option><option value="14:00">2:00 pm</option><option value="18:00">6:00 pm</option><option value="18:30">6:30 pm</option><option value="19:00">7:00 pm</option><option value="19:30">7:30 pm</option><option value="20:00">8:00 pm</option><option value="20:30">8:30 pm</option><option value="21:00">9:00 pm</option></select></div></div>
            <div className="grid md:grid-cols-2 gap-6"><div><label htmlFor="guests" className="form-label">Number of Guests *</label><select id="guests" name="guests" required className="form-input"><option value="">Select</option><option value="1">1 Guest</option><option value="2">2 Guests</option><option value="3">3 Guests</option><option value="4">4 Guests</option><option value="5">5 Guests</option><option value="6">6 Guests</option><option value="7-10">7-10 Guests (Private Dining)</option></select></div><div><label htmlFor="experience" className="form-label">Dining Experience</label><select id="experience" name="experience" className="form-input"><option value="">Select experience</option><option value="omakase">Omakase Tasting Menu</option><option value="sushi-bar">Sushi Bar</option><option value="a-la-carte">A La Carte</option><option value="bento">Bento Box</option><option value="private">Private Dining</option></select></div></div>
            <div><label htmlFor="message" className="form-label">Special Requests or Dietary Requirements</label><textarea id="message" name="message" rows={4} className="form-textarea" placeholder="Allergies, celebrations, seating preferences, dietary requirements..."></textarea></div>
            <div className="flex items-start gap-3"><input type="checkbox" id="consent" name="consent" required className="mt-1 w-4 h-4 text-accent border-gray-300 rounded focus:ring-accent" /><label htmlFor="consent" className="text-sm text-gray-600">I consent to Soho Sushi Kitchen contacting me to confirm my reservation. *</label></div>
            <button type="submit" className="btn-accent w-full sm:w-auto">Request Reservation</button>
          </form>
        </div>
        <div><h2 className="text-2xl md:text-3xl font-bold text-primary mb-8">Visit Us</h2>
          <div className="location-card mb-8"><div className="flex items-center gap-3 mb-4"><div className="w-12 h-12 bg-accent/10 rounded-full flex items-center justify-center"><svg className="w-6 h-6 text-accent" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z" /><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 11a3 3 0 11-6 0 3 3 0 016 0z" /></svg></div><div><span className="text-sm text-accent font-semibold">Our Restaurant</span><h3 className="text-xl font-bold text-primary">Wardour Street, Soho</h3></div></div>
            <address className="not-italic text-gray-700 mb-4"><strong>Soho Sushi Kitchen</strong><br />11 Wardour Street<br />Soho<br />London W1D 6PG</address>
            <div className="space-y-2 text-gray-600 mb-4"><p><strong>Opening Hours:</strong><br />Monday - Thursday: 12:00pm - 10:00pm<br />Friday - Saturday: 12:00pm - 11:00pm<br />Sunday: 12:00pm - 9:00pm</p></div>
            <p className="text-sm text-gray-500">2-minute walk from Leicester Square station, 3 minutes from Piccadilly Circus. We are on the east side of Wardour Street between Lisle Street and Shaftesbury Avenue.</p>
          </div>
          <div className="bg-gray-50 p-6 rounded-sm"><h3 className="text-lg font-bold text-primary mb-4">Prefer to Call?</h3><div className="space-y-4">
            <a href="tel:02079463380" className="flex items-center gap-3 text-gray-700 hover:text-accent transition-colors"><div className="w-10 h-10 bg-accent/10 rounded-full flex items-center justify-center"><svg className="w-5 h-5 text-accent" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 5a2 2 0 012-2h3.28a1 1 0 01.948.684l1.498 4.493a1 1 0 01-.502 1.21l-2.257 1.13a11.042 11.042 0 005.516 5.516l1.13-2.257a1 1 0 011.21-.502l4.493 1.498a1 1 0 01.684.949V19a2 2 0 01-2 2h-1C9.716 21 3 14.284 3 6V5z" /></svg></div><div><p className="font-semibold">020 7946 3380</p><p className="text-sm text-gray-500">Call us during opening hours</p></div></a>
            <a href="mailto:reservations@sohosushi.co.uk" className="flex items-center gap-3 text-gray-700 hover:text-accent transition-colors"><div className="w-10 h-10 bg-accent/10 rounded-full flex items-center justify-center"><svg className="w-5 h-5 text-accent" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" /></svg></div><div><p className="font-semibold">reservations@sohosushi.co.uk</p><p className="text-sm text-gray-500">Email us anytime</p></div></a>
          </div></div>
        </div>
      </div></div></section>

      <section className="bg-gray-100"><div className="container-width py-8"><h2 className="text-2xl font-bold text-primary mb-6 text-center">Find Us in Soho</h2><div className="aspect-video bg-gray-200 rounded-sm overflow-hidden"><iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2482.8!2d-0.1315!3d51.5130!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zNTHCsDMwJzQ2LjgiTiAwwrAwNyc1My40Ilc!5e0!3m2!1sen!2suk!4v1234567890" width="100%" height="100%" style={{ border: 0 }} allowFullScreen loading="lazy" referrerPolicy="no-referrer-when-downgrade" title="Soho Sushi Kitchen Location"></iframe></div></div></section>
    </>
  );
}
