import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = { title: "About Us | Professional Photography Studio in Hackney", description: "Meet the team at Hackney Photography Studio. SWPP member, published photographer, fully insured. Professional photography in East London since 2016.", openGraph: { title: "About Us | Hackney Photography Studio", description: "Professional photography studio in Hackney, East London. SWPP accredited, fully insured." } };

export default function AboutPage() {
  return (
    <>
      <section className="hero-gradient py-20 lg:py-28"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="max-w-3xl"><span className="text-[var(--accent)] font-semibold tracking-wider uppercase text-sm">About Us</span><h1 className="text-4xl md:text-5xl font-bold text-white mt-4 mb-6">Our Story</h1><p className="text-xl text-gray-200 leading-relaxed">A creative photography studio in the heart of Hackney, built on a passion for storytelling through images.</p></div></div></section>

      <section className="py-16 lg:py-24 bg-white"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="grid lg:grid-cols-2 gap-16 items-center"><div><span className="text-[var(--accent)] font-semibold tracking-wider uppercase text-sm">Our Story</span><h2 className="text-3xl md:text-4xl font-bold text-[var(--primary)] mt-4 mb-4">Passionate About Photography</h2><div className="w-16 h-1 bg-[var(--accent)] mb-6"></div><p className="text-lg text-gray-600 mb-6 leading-relaxed">Hackney Photography Studio was established in 2016 in the creative heart of East London. What began as a personal passion for documentary photography has grown into a full-service studio covering portraits, weddings, commercial work and events.</p><p className="text-gray-600 mb-6 leading-relaxed">Our photographer is a proud member of the Society of Wedding and Portrait Photographers (SWPP) and has been published in several national and international publications. But titles aside, what matters most to us is delivering images that our clients love.</p><p className="text-gray-600 leading-relaxed">We chose Hackney for its energy, creativity and community. Our Dalston Lane studio is a welcoming, professional space where clients can relax, be themselves and let us capture something genuine.</p></div><div className="bg-gray-50 p-8 lg:p-12 rounded-sm"><div className="grid grid-cols-2 gap-8"><div className="text-center p-6 bg-white rounded-sm shadow-sm"><div className="text-3xl md:text-4xl font-bold text-[var(--accent)]">500+</div><p className="text-gray-600 mt-2 font-medium">Shoots Completed</p></div><div className="text-center p-6 bg-white rounded-sm shadow-sm"><div className="text-3xl md:text-4xl font-bold text-[var(--accent)]">150+</div><p className="text-gray-600 mt-2 font-medium">Weddings</p></div><div className="text-center p-6 bg-white rounded-sm shadow-sm"><div className="text-3xl md:text-4xl font-bold text-[var(--accent)]">SWPP</div><p className="text-gray-600 mt-2 font-medium">Accredited</p></div><div className="text-center p-6 bg-white rounded-sm shadow-sm"><div className="text-3xl md:text-4xl font-bold text-[var(--accent)]">4.9★</div><p className="text-gray-600 mt-2 font-medium">Google Rating</p></div></div></div></div></div></section>

      <section className="py-16 lg:py-24 bg-gray-50"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="text-center mb-16"><span className="text-[var(--accent)] font-semibold tracking-wider uppercase text-sm">Our Values</span><h2 className="text-3xl md:text-4xl font-bold text-[var(--primary)] mt-4 mb-4">What We Believe In</h2><div className="w-16 h-1 bg-[var(--accent)] mx-auto mb-6"></div></div><div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">{[{ title: "Authenticity", desc: "We capture real moments and genuine emotions. Our best work comes from making people feel comfortable and letting the magic happen naturally." },{ title: "Craftsmanship", desc: "Every image is carefully composed, expertly lit and professionally edited. We take pride in the technical quality of our work." },{ title: "Creativity", desc: "We bring fresh ideas and creative vision to every project. No two shoots are the same because no two clients are the same." },{ title: "Professionalism", desc: "SWPP accredited, fully insured and always reliable. We treat every booking with the seriousness it deserves." },{ title: "Collaboration", desc: "Great photography is a partnership. We listen to your ideas, offer guidance and work together to create something special." },{ title: "Community", desc: "We're rooted in Hackney and proud to be part of East London's creative community. We support local businesses and creatives." }].map((v, i) => (<div key={i} className="bg-white p-8 rounded-sm shadow-sm"><h3 className="text-xl font-bold text-[var(--primary)] mb-3">{v.title}</h3><p className="text-gray-600">{v.desc}</p></div>))}</div></div></section>

      <section className="py-16 lg:py-24 bg-white"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center"><span className="text-[var(--accent)] font-semibold tracking-wider uppercase text-sm">The Studio</span><h2 className="text-3xl md:text-4xl font-bold text-[var(--primary)] mt-4 mb-4">Our Hackney Studio</h2><div className="w-16 h-1 bg-[var(--accent)] mx-auto mb-6"></div><p className="text-lg text-gray-600 max-w-3xl mx-auto mb-8">800 square feet of professional studio space on Dalston Lane, fully equipped with Profoto lighting, multiple backdrops and a comfortable client lounge.</p><div className="bg-gradient-to-br from-[var(--primary)] to-[var(--secondary)] p-8 rounded-sm text-white max-w-lg mx-auto"><address className="not-italic text-gray-200 text-lg mb-4">Unit 4, 28 Dalston Lane<br />Hackney, London E8 3AZ</address><p className="text-gray-300 text-sm">Near Hackney Downs and Dalston Junction stations</p></div></div></section>

      <section className="py-16 lg:py-24 bg-[var(--primary)]"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center"><h2 className="text-3xl md:text-4xl font-bold text-white mb-4">Let&apos;s Work Together</h2><p className="text-xl text-gray-200 mb-8 max-w-2xl mx-auto">Get in touch to discuss your project or visit our Hackney studio.</p><div className="flex flex-col sm:flex-row justify-center gap-4"><Link href="/photographer-hackney/contact" className="bg-[var(--accent)] text-white px-8 py-4 font-semibold rounded-sm hover:bg-[var(--accent-light)] transition-colors">Book a Shoot</Link><a href="tel:02079460134" className="border-2 border-white text-white px-8 py-4 font-semibold rounded-sm hover:bg-white hover:text-[var(--primary)] transition-colors">Call 020 7946 0134</a></div></div></section>
    </>
  );
}
