import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Garden Design Services | Design, Landscaping & Planting",
  description: "Complete garden design services including bespoke design, planting plans, landscaping, maintenance, lighting and water features in Richmond and South West London.",
  openGraph: { title: "Garden Design Services | Richmond Garden Design", description: "Award-winning garden design, landscaping and planting services in Richmond, London." },
};

export default function ServicesPage() {
  const services = [
    { id: "garden-design", title: "Garden Design", subtitle: "Your Outdoor Vision, Realised", description: "Our garden design service begins with understanding how you want to use your outdoor space. We consider your lifestyle, your taste and the unique characteristics of your plot to create a design that feels both inspiring and achievable. From intimate courtyard gardens to sweeping country estates, we bring creativity, horticultural knowledge and technical precision to every project.", features: ["Initial site survey and analysis", "Concept mood boards and sketch designs", "Detailed planting and layout plans to scale", "3D visualisations of your finished garden", "Material specification and sourcing", "Contractor briefing and project oversight"], icon: (<svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" /></svg>) },
    { id: "planting-plans", title: "Planting Plans", subtitle: "Year-Round Beauty", description: "Planting is the soul of any garden. Our detailed planting plans are designed to provide colour, texture, scent and structure throughout the seasons. We consider your soil type, aspect, microclimate and maintenance preferences to select plants that will thrive and bring joy for years to come.", features: ["Seasonal interest analysis for 12-month colour", "Soil testing and aspect assessment", "Drought-tolerant and wildlife-friendly options", "Specimen tree and shrub selection", "Bulb planting schedules for spring displays", "Plant sourcing from specialist nurseries"], icon: (<svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M5 3v4M3 5h4M6 17v4m-2-2h4m5-16l2.286 6.857L21 12l-5.714 2.143L13 21l-2.286-6.857L5 12l5.714-2.143L13 3z" /></svg>) },
    { id: "landscaping", title: "Landscaping", subtitle: "From Plans to Reality", description: "We work with a select group of trusted landscaping contractors to turn our designs into reality. From paving and decking to lawns and borders, we oversee every element of the build to ensure the finished garden matches the design vision precisely. Our project management ensures work is completed on time and to the highest standards.", features: ["Natural stone and porcelain paving", "Composite and hardwood decking", "Boundary walls, fences and screens", "Artificial and natural turf installation", "Raised beds and retaining structures", "Drainage solutions and irrigation systems"], icon: (<svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M19 21V5a2 2 0 00-2-2H7a2 2 0 00-2 2v16m14 0h2m-2 0h-5m-9 0H3m2 0h5M9 7h1m-1 4h1m4-4h1m-1 4h1m-5 10v-5a1 1 0 011-1h2a1 1 0 011 1v5m-4 0h4" /></svg>) },
    { id: "garden-maintenance", title: "Garden Maintenance", subtitle: "Keeping Your Garden at Its Best", description: "A beautifully designed garden needs ongoing care to reach its full potential. Our seasonal maintenance programmes are tailored to your garden, ensuring plants are pruned at the right time, borders are kept tidy, and your garden matures gracefully. We offer regular visits or one-off seasonal tidy-ups.", features: ["Seasonal pruning and deadheading", "Lawn care including mowing, feeding and aeration", "Border weeding and mulching", "Hedge trimming and shaping", "Spring and autumn planting top-ups", "Pest and disease monitoring"], icon: (<svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>) },
    { id: "lighting-design", title: "Lighting Design", subtitle: "Extend the Magic Into the Evening", description: "Well-designed garden lighting transforms your outdoor space after dark, creating atmosphere, highlighting key features and extending the usability of your garden well into the evening. We design bespoke lighting schemes using energy-efficient LED technology, working with qualified electricians for safe, compliant installation.", features: ["Uplighting for trees and architectural features", "Path and step lighting for safety", "Festoon and string lighting for entertaining areas", "Underwater lighting for ponds and water features", "Smart control systems and timers", "Energy-efficient LED throughout"], icon: (<svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z" /></svg>) },
    { id: "water-features", title: "Water Features", subtitle: "Serenity in Sound and Motion", description: "Water brings a unique dimension to any garden: the sound of trickling water, the reflections of light, the wildlife it attracts. We design bespoke water features ranging from simple bubbling stones to formal reflecting pools and naturalistic ponds. Every feature is designed for both beauty and ease of maintenance.", features: ["Reflecting pools and formal rills", "Natural wildlife ponds", "Contemporary fountain designs", "Bubbling stone and boulder features", "Pond planting and ecosystem design", "Filtration and pump specification"], icon: (<svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M3 15a4 4 0 004 4h9a5 5 0 10-.1-9.999 5.002 5.002 0 10-9.78 2.096A4.001 4.001 0 003 15z" /></svg>) },
  ];

  return (
    <>
      <section className="hero-gradient py-20 lg:py-28"><div className="container-width"><div className="max-w-3xl"><span className="text-accent font-semibold tracking-wider uppercase text-sm">Our Services</span><h1 className="text-4xl md:text-5xl font-bold text-white mt-4 mb-6">Garden Design Services</h1><p className="text-xl text-gray-200 leading-relaxed">From concept sketches to finished gardens, we offer a comprehensive range of design, landscaping and horticultural services.</p></div></div></section>
      <section className="section-padding bg-white"><div className="container-width"><div className="text-center mb-16"><h2 className="text-3xl md:text-4xl font-bold text-primary mb-4">What We Offer</h2><div className="gold-line-center mb-6"></div><p className="text-lg text-gray-600 max-w-3xl mx-auto">With 3 expert designers and over 150 gardens completed, we bring creativity and horticultural expertise to every project.</p></div>
        <div className="space-y-16">{services.map((service, index) => (<div key={service.id} id={service.id} className={`grid lg:grid-cols-2 gap-12 items-center ${index % 2 === 1 ? "lg:flex-row-reverse" : ""}`}><div className={index % 2 === 1 ? "lg:order-2" : ""}><div className="text-primary mb-4">{service.icon}</div><h3 className="text-2xl md:text-3xl font-bold text-primary mb-2">{service.title}</h3><p className="text-accent font-semibold mb-4">{service.subtitle}</p><p className="text-gray-600 mb-6 leading-relaxed">{service.description}</p><ul className="space-y-3 mb-8">{service.features.map((f, i) => (<li key={i} className="flex items-start gap-3"><svg className="w-5 h-5 text-accent mt-0.5 flex-shrink-0" fill="currentColor" viewBox="0 0 20 20"><path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" /></svg><span className="text-gray-700">{f}</span></li>))}</ul><Link href="/garden-designer-richmond/contact" className="btn-accent">Discuss Your Project</Link></div><div className={`bg-gray-50 p-8 lg:p-12 rounded-sm ${index % 2 === 1 ? "lg:order-1" : ""}`}><div className="aspect-video bg-gradient-to-br from-primary to-secondary rounded-sm flex items-center justify-center"><div className="text-white opacity-20 scale-150">{service.icon}</div></div></div></div>))}</div>
      </div></section>
      <section className="section-padding bg-gray-50"><div className="container-width"><div className="text-center mb-16"><span className="text-accent font-semibold tracking-wider uppercase text-sm">Our Process</span><h2 className="text-3xl md:text-4xl font-bold text-primary mt-4 mb-4">From Idea to Garden</h2><div className="gold-line-center mb-6"></div></div>
        <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8">
          <div className="text-center"><div className="w-16 h-16 bg-primary text-white rounded-full flex items-center justify-center mx-auto mb-4 text-2xl font-bold font-serif">1</div><h3 className="text-xl font-bold text-primary mb-2">Consultation</h3><p className="text-gray-600">We visit your garden, listen to your ideas and discuss how you want to use the space.</p></div>
          <div className="text-center"><div className="w-16 h-16 bg-primary text-white rounded-full flex items-center justify-center mx-auto mb-4 text-2xl font-bold font-serif">2</div><h3 className="text-xl font-bold text-primary mb-2">Concept Design</h3><p className="text-gray-600">We develop initial concepts with mood boards, sketches and 3D visuals for your feedback.</p></div>
          <div className="text-center"><div className="w-16 h-16 bg-primary text-white rounded-full flex items-center justify-center mx-auto mb-4 text-2xl font-bold font-serif">3</div><h3 className="text-xl font-bold text-primary mb-2">Detailed Plans</h3><p className="text-gray-600">We produce detailed technical drawings and planting plans ready for construction.</p></div>
          <div className="text-center"><div className="w-16 h-16 bg-primary text-white rounded-full flex items-center justify-center mx-auto mb-4 text-2xl font-bold font-serif">4</div><h3 className="text-xl font-bold text-primary mb-2">Build & Plant</h3><p className="text-gray-600">We oversee the landscaping and planting, ensuring every detail matches the design.</p></div>
        </div>
      </div></section>
      <section className="section-padding bg-primary"><div className="container-width text-center"><h2 className="text-3xl md:text-4xl font-bold text-white mb-4">Ready to Design Your Dream Garden?</h2><p className="text-xl text-gray-200 mb-8 max-w-2xl mx-auto">Book a free consultation to discuss your garden, your ideas and how we can bring them to life.</p><div className="flex flex-col sm:flex-row justify-center gap-4"><Link href="/garden-designer-richmond/contact" className="btn-accent">Book Consultation</Link><a href="tel:02079463340" className="btn-outline border-white text-white hover:bg-white hover:text-primary">Call 020 7946 3340</a></div></div></section>
    </>
  );
}
