import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "About Us | REPS Registered Personal Trainers in Shoreditch",
  description: "Learn about Shoreditch Fitness Studio - REPS registered personal training studio in Shoreditch, E1. Expert trainers, premium equipment and a results-driven approach since 2018.",
  openGraph: { title: "About Us | Shoreditch Fitness Studio", description: "REPS registered personal training studio in Shoreditch delivering results-driven fitness since 2018." },
};

export default function AboutPage() {
  return (
    <>
      <section className="hero-gradient py-20 lg:py-28"><div className="container-width"><div className="max-w-3xl"><span className="text-accent font-semibold tracking-wider uppercase text-sm">About Us</span><h1 className="text-4xl md:text-5xl font-bold text-white mt-4 mb-6">Built for Results</h1><p className="text-xl text-gray-200 leading-relaxed">REPS registered personal training studio in the heart of Shoreditch. Expert coaches, premium equipment and a community that turns up and gets it done.</p></div></div></section>

      <section className="section-padding bg-white"><div className="container-width"><div className="grid lg:grid-cols-2 gap-16 items-center"><div><span className="text-accent font-semibold tracking-wider uppercase text-sm">Our Story</span><h2 className="text-3xl md:text-4xl font-bold text-primary mt-4 mb-4">Training Shoreditch Since 2018</h2><div className="gold-line mb-6"></div><p className="text-lg text-gray-600 mb-6 leading-relaxed">Shoreditch Fitness Studio was founded with a simple idea: personal training should be personal. Too many gyms sell memberships and leave people to figure it out alone. We built a studio where every session is coached, every programme is tailored and every client is treated as an individual.</p><p className="text-gray-600 mb-6 leading-relaxed">Located on Rivington Street in the heart of Shoreditch, our studio is equipped with premium Eleiko barbells, calibrated plates, functional rigs, assault bikes, rowers and a full range of conditioning equipment. It is a serious training environment without the ego of a commercial gym.</p><p className="text-gray-600 leading-relaxed">Our team of seven trainers brings a wide range of specialisms including strength and conditioning, Olympic lifting, boxing, yoga and pre and postnatal fitness. Every one of them is REPS registered, Level 3 qualified and holds a current First Aid certificate. We invest heavily in continued professional development because better coaches mean better results for you.</p></div><div className="bg-gray-50 p-8 lg:p-12 rounded-sm"><div className="grid grid-cols-2 gap-8"><div className="text-center p-6 bg-white rounded-sm shadow-sm"><div className="stat-number">7+</div><p className="text-gray-600 mt-2 font-medium">Years of Training</p></div><div className="text-center p-6 bg-white rounded-sm shadow-sm"><div className="stat-number">500+</div><p className="text-gray-600 mt-2 font-medium">Clients Trained</p></div><div className="text-center p-6 bg-white rounded-sm shadow-sm"><div className="stat-number">7</div><p className="text-gray-600 mt-2 font-medium">Expert Trainers</p></div><div className="text-center p-6 bg-white rounded-sm shadow-sm"><div className="stat-number">4.9/5</div><p className="text-gray-600 mt-2 font-medium">Google Rating</p></div></div></div></div></div></section>

      <section className="section-padding bg-gray-50"><div className="container-width"><div className="text-center mb-16"><span className="text-accent font-semibold tracking-wider uppercase text-sm">Our Values</span><h2 className="text-3xl md:text-4xl font-bold text-primary mt-4 mb-4">What Sets Us Apart</h2><div className="gold-line-center mb-6"></div></div><div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
        <div className="card-premium p-8"><div className="w-16 h-16 bg-primary/10 rounded-full flex items-center justify-center mb-6"><svg className="w-8 h-8 text-primary" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" /></svg></div><h3 className="text-xl font-bold text-primary mb-3">Qualified Coaches</h3><p className="text-gray-600">Every trainer is REPS registered with a minimum Level 3 qualification. We invest in ongoing education so our coaching stays at the highest standard.</p></div>
        <div className="card-premium p-8"><div className="w-16 h-16 bg-primary/10 rounded-full flex items-center justify-center mb-6"><svg className="w-8 h-8 text-primary" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M13 10V3L4 14h7v7l9-11h-7z" /></svg></div><h3 className="text-xl font-bold text-primary mb-3">Results-Driven</h3><p className="text-gray-600">We measure progress, track results and adjust programmes. Our approach is evidence-based and focused entirely on getting you where you want to be.</p></div>
        <div className="card-premium p-8"><div className="w-16 h-16 bg-primary/10 rounded-full flex items-center justify-center mb-6"><svg className="w-8 h-8 text-primary" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z" /></svg></div><h3 className="text-xl font-bold text-primary mb-3">Community</h3><p className="text-gray-600">Our clients support each other. The group classes build genuine camaraderie, and many of our clients train together outside sessions too.</p></div>
        <div className="card-premium p-8"><div className="w-16 h-16 bg-primary/10 rounded-full flex items-center justify-center mb-6"><svg className="w-8 h-8 text-primary" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M19.428 15.428a2 2 0 00-1.022-.547l-2.387-.477a6 6 0 00-3.86.517l-.318.158a6 6 0 01-3.86.517L6.05 15.21a2 2 0 00-1.806.547M8 4h8l-1 1v5.172a2 2 0 00.586 1.414l5 5c1.26 1.26.367 3.414-1.415 3.414H4.828c-1.782 0-2.674-2.154-1.414-3.414l5-5A2 2 0 009 10.172V5L8 4z" /></svg></div><h3 className="text-xl font-bold text-primary mb-3">Premium Equipment</h3><p className="text-gray-600">Eleiko barbells, calibrated plates, functional rigs, assault bikes and more. Our studio has everything you need for serious training, nothing you do not.</p></div>
        <div className="card-premium p-8"><div className="w-16 h-16 bg-primary/10 rounded-full flex items-center justify-center mb-6"><svg className="w-8 h-8 text-primary" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" /></svg></div><h3 className="text-xl font-bold text-primary mb-3">Flexible Schedule</h3><p className="text-gray-600">Open from 6am on weekdays with early morning, lunchtime and evening sessions. We work around your schedule, not the other way round.</p></div>
        <div className="card-premium p-8"><div className="w-16 h-16 bg-primary/10 rounded-full flex items-center justify-center mb-6"><svg className="w-8 h-8 text-primary" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z" /></svg></div><h3 className="text-xl font-bold text-primary mb-3">Inclusive Environment</h3><p className="text-gray-600">All fitness levels are welcome. Whether you have never set foot in a gym or you have been training for years, our coaches meet you where you are.</p></div>
      </div></div></section>

      <section className="section-padding bg-white"><div className="container-width"><div className="text-center mb-16"><span className="text-accent font-semibold tracking-wider uppercase text-sm">Our Location</span><h2 className="text-3xl md:text-4xl font-bold text-primary mt-4 mb-4">Find Us on Rivington Street</h2><div className="gold-line-center mb-6"></div><p className="text-lg text-gray-600 max-w-3xl mx-auto">Our studio is in the heart of Shoreditch, minutes from Old Street and Shoreditch High Street stations.</p></div><div className="bg-gray-50 p-8 lg:p-12 rounded-sm border-t-4 border-accent max-w-2xl mx-auto"><address className="not-italic text-gray-700 text-lg mb-4"><strong>Shoreditch Fitness Studio</strong><br />18 Rivington Street<br />Shoreditch, London EC2A 3DU</address><p className="text-gray-600 mb-2"><strong>Opening Hours:</strong></p><p className="text-gray-600">Monday &ndash; Friday: 6:00am &ndash; 9:00pm</p><p className="text-gray-600">Saturday: 7:00am &ndash; 6:00pm</p><p className="text-gray-600 mb-4">Sunday: 8:00am &ndash; 2:00pm</p><p className="text-sm text-gray-500">Nearest stations: Old Street (Northern line, 5 min walk) and Shoreditch High Street (Overground, 3 min walk). Cycle parking available outside the studio.</p></div></div></section>

      <section className="section-padding bg-primary"><div className="container-width text-center"><h2 className="text-3xl md:text-4xl font-bold text-white mb-4">Ready to Train With Us?</h2><p className="text-xl text-gray-200 mb-8 max-w-2xl mx-auto">Book your free trial session and experience the difference expert coaching makes.</p><div className="flex flex-col sm:flex-row justify-center gap-4"><Link href="/personal-trainer-shoreditch/contact" className="btn-accent">Book Free Trial</Link><a href="tel:02079466789" className="btn-outline border-white text-white hover:bg-white hover:text-primary">Call 020 7946 6789</a></div></div></section>
    </>
  );
}
