import type { Metadata } from "next";
import Link from "next/link";
export const metadata: Metadata = { title: "About Us | Award-Winning Garden Design Studio", description: "Learn about Richmond Garden Design - award-winning garden design studio with 3 expert designers, RHS Chelsea medal and 150+ gardens designed since 2013.", openGraph: { title: "About Us | Richmond Garden Design", description: "Award-winning garden design studio in Richmond, London since 2013." } };

export default function AboutPage() {
  return (
    <>
      <section className="hero-gradient py-20 lg:py-28"><div className="container-width"><div className="max-w-3xl"><span className="text-accent font-semibold tracking-wider uppercase text-sm">About Us</span><h1 className="text-4xl md:text-5xl font-bold text-white mt-4 mb-6">Gardens That Live and Breathe</h1><p className="text-xl text-gray-200 leading-relaxed">An award-winning garden design studio creating beautiful, sustainable outdoor spaces from our base in Richmond, London.</p></div></div></section>

      <section className="section-padding bg-white"><div className="container-width"><div className="grid lg:grid-cols-2 gap-16 items-center"><div><span className="text-accent font-semibold tracking-wider uppercase text-sm">Our Story</span><h2 className="text-3xl md:text-4xl font-bold text-primary mt-4 mb-4">Rooted in Richmond Since 2013</h2><div className="gold-line mb-6"></div>
        <p className="text-lg text-gray-600 mb-6 leading-relaxed">Richmond Garden Design was founded by a passionate horticulturalist who had spent years designing gardens for a large landscape firm before deciding to establish a studio that placed creativity and client relationships above volume. Based in The Quadrant in the heart of Richmond, we have been designing gardens that people genuinely love to spend time in.</p>
        <p className="text-gray-600 mb-6 leading-relaxed">Our RHS Chelsea Flower Show medal in 2018 was a proud milestone, but the real reward is seeing clients step into their newly completed gardens for the first time. That moment of delight is what drives us every day.</p>
        <p className="text-gray-600 leading-relaxed">Today our team of three designers brings together expertise in horticulture, landscape architecture and spatial design. We have completed over 150 gardens ranging from compact urban courtyards to expansive country properties, and each one has been designed with the same attention to detail and genuine love of the craft.</p>
      </div><div className="bg-gray-50 p-8 lg:p-12 rounded-sm"><div className="grid grid-cols-2 gap-8"><div className="text-center p-6 bg-white rounded-sm shadow-sm"><div className="stat-number">150+</div><p className="text-gray-600 mt-2 font-medium">Gardens Designed</p></div><div className="text-center p-6 bg-white rounded-sm shadow-sm"><div className="stat-number">3</div><p className="text-gray-600 mt-2 font-medium">Expert Designers</p></div><div className="text-center p-6 bg-white rounded-sm shadow-sm"><div className="stat-number">12+</div><p className="text-gray-600 mt-2 font-medium">Years Experience</p></div><div className="text-center p-6 bg-white rounded-sm shadow-sm"><div className="stat-number">RHS</div><p className="text-gray-600 mt-2 font-medium">Chelsea Medal</p></div></div></div></div></div></section>

      <section className="section-padding bg-gray-50"><div className="container-width"><div className="text-center mb-16"><span className="text-accent font-semibold tracking-wider uppercase text-sm">Our Values</span><h2 className="text-3xl md:text-4xl font-bold text-primary mt-4 mb-4">What We Believe In</h2><div className="gold-line-center mb-6"></div></div>
        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
          {[{t:"Design for Living",d:"Gardens should be used, not just admired. We design practical spaces that enhance your daily life."},{t:"Seasonal Thinking",d:"Every garden should be beautiful in every season. We plan for year-round interest, colour and structure."},{t:"Sustainability",d:"We champion native planting, water-wise design and sustainable materials wherever possible."},{t:"Collaboration",d:"The best gardens emerge from a genuine dialogue between designer and client. Your input shapes everything."},{t:"Attention to Detail",d:"From the angle of a path to the position of a single bulb, the details are what elevate a garden from good to exceptional."},{t:"Long-Term Beauty",d:"We design gardens that mature gracefully, becoming more beautiful with every passing year."}].map((v) => (
            <div key={v.t} className="card-premium p-8"><div className="w-16 h-16 bg-primary/10 rounded-full flex items-center justify-center mb-6"><svg className="w-8 h-8 text-primary" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" /></svg></div><h3 className="text-xl font-bold text-primary mb-3">{v.t}</h3><p className="text-gray-600">{v.d}</p></div>
          ))}
        </div>
      </div></section>

      <section className="section-padding bg-white"><div className="container-width"><div className="text-center mb-16"><span className="text-accent font-semibold tracking-wider uppercase text-sm">Our Studio</span><h2 className="text-3xl md:text-4xl font-bold text-primary mt-4 mb-4">Visit Us in Richmond</h2><div className="gold-line-center mb-6"></div><p className="text-lg text-gray-600 max-w-3xl mx-auto">Our studio on The Quadrant is in the heart of Richmond, surrounded by the parks, river walks and beautiful gardens that inspire our work.</p></div>
        <div className="bg-gray-50 p-8 lg:p-12 rounded-sm border-t-4 border-accent max-w-3xl mx-auto"><address className="not-italic text-gray-700 mb-6 text-lg"><strong>Richmond Garden Design</strong><br />22 The Quadrant<br />Richmond, London TW9 1BP</address><div className="space-y-2 text-gray-600"><p><strong>Richmond Station:</strong> 4-minute walk</p><p><strong>North Sheen:</strong> 7-minute walk</p><p><strong>Kew Gardens:</strong> 10-minute walk</p></div></div>
      </div></section>

      <section className="section-padding bg-primary"><div className="container-width text-center"><h2 className="text-3xl md:text-4xl font-bold text-white mb-4">Ready to Start Your Garden Journey?</h2><p className="text-xl text-gray-200 mb-8 max-w-2xl mx-auto">Book a free initial consultation to discuss your garden and discover what is possible.</p><div className="flex flex-col sm:flex-row justify-center gap-4"><Link href="/garden-designer-richmond/contact" className="btn-accent">Book Consultation</Link><a href="tel:02079463340" className="btn-outline border-white text-white hover:bg-white hover:text-primary">Call 020 7946 3340</a></div></div></section>
    </>
  );
}
