import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "FAQ | Mortgage Questions Answered",
  description: "Common questions about mortgages, our broker service, and the home-buying process. Expert answers from Stratford Mortgage Solutions, your FCA regulated mortgage broker in East London.",
  openGraph: { title: "FAQ | Stratford Mortgage Solutions", description: "Everything you need to know about mortgages and our broker service in Stratford, East London." },
};

export default function FAQPage() {
  const faqs = [
    { category: "About Our Service", questions: [
      { question: "Why should I use a mortgage broker instead of going direct to a bank?", answer: "A bank can only offer you their own mortgage products. As a whole of market broker, we compare deals from over 90 lenders — including banks, building societies and specialist lenders — many of which don't deal directly with the public. We often find rates and products you simply wouldn't have access to on your own. Plus, we handle all the paperwork and application management, saving you significant time and stress." },
      { question: "How much does your service cost?", answer: "Your initial consultation is completely free with no obligation to proceed. If you choose to go ahead, there may be a fee for our mortgage advice. The actual amount depends on your circumstances, but a typical fee is up to 1% of the mortgage amount. We also receive a procuration fee from the lender. We'll always be transparent about our fees before you commit to anything." },
      { question: "Are you regulated?", answer: "Yes. Stratford Mortgage Solutions Ltd is authorised and regulated by the Financial Conduct Authority (FCA). This means we must follow strict rules about the advice we give, how we handle your data, and how we treat you as a customer. You also have access to the Financial Ombudsman Service and the Financial Services Compensation Scheme (FSCS) if anything goes wrong." },
      { question: "What does 'whole of market' actually mean?", answer: "Whole of market means we have access to mortgage products from across the entire lending market — not just a limited panel of lenders. This includes high street banks like Barclays, Santander and NatWest, building societies like Nationwide and Leeds, and specialist lenders who only work through brokers. We search all of them to find the best deal for your specific situation." },
    ] },
    { category: "First-Time Buyers", questions: [
      { question: "How much deposit do I need to buy my first home?", answer: "The minimum deposit for most lenders is 5% of the property's purchase price. So for a £300,000 property, you'd need at least £15,000. However, the more you can put down, the better the interest rates available to you. The best rates typically start at 25% deposit (75% LTV). We can help you understand exactly what you can afford based on your savings and income." },
      { question: "What is an agreement in principle and do I need one?", answer: "An agreement in principle (AIP), also called a decision in principle (DIP), is a conditional indication from a lender of how much they'd be willing to lend you. It's not a guaranteed offer, but it shows estate agents and sellers that you're a serious buyer with finance in place. We strongly recommend getting one before you start viewing properties — we can usually arrange one within 24 hours." },
      { question: "Can I buy with a friend or partner who isn't married to me?", answer: "Absolutely. Joint mortgages are available for married couples, civil partners, unmarried partners, friends, and family members. The key consideration is that all parties are jointly and severally liable for the mortgage. We'd also recommend you take legal advice about a declaration of trust to protect everyone's interests, especially if you're contributing different deposit amounts." },
    ] },
    { category: "Remortgaging", questions: [
      { question: "When should I start thinking about remortgaging?", answer: "We recommend starting the process around 6 months before your current deal ends. Most mortgage offers are valid for 3-6 months, so you can secure a new rate well in advance without any penalty. If you wait until your deal actually ends, you'll be moved onto your lender's standard variable rate (SVR), which is almost always significantly higher. We proactively contact our clients before their deals expire." },
      { question: "Can I remortgage to release equity from my home?", answer: "Yes, this is a very common reason for remortgaging. You can release equity to fund home improvements, consolidate debts, help a family member onto the property ladder, or for other purposes. The amount you can release depends on your property's current value and what you owe on your existing mortgage. We'll assess your options and find lenders offering the best terms for capital raising." },
      { question: "Will I have to pay an early repayment charge if I switch?", answer: "If you're still within a fixed-rate or discounted-rate period, there will usually be an early repayment charge (ERC) for leaving early. These can be substantial — typically 1-5% of your outstanding balance. However, if you're at or near the end of your deal period, there's usually no charge. We'll check your existing mortgage terms and factor any ERCs into our comparison to make sure switching genuinely saves you money." },
    ] },
    { category: "Buy-to-Let & Investment", questions: [
      { question: "How is a buy-to-let mortgage different from a residential one?", answer: "Buy-to-let mortgages typically require a larger deposit (usually 25% minimum), carry slightly higher interest rates, and are assessed differently. Instead of basing affordability primarily on your income, lenders look at the expected rental income — usually requiring rent to cover 125-145% of the mortgage payment. Many are interest-only, meaning your monthly payments are lower but you'll need a repayment strategy. We know which lenders suit which scenarios." },
      { question: "Should I buy in my personal name or a limited company?", answer: "This is an increasingly important question due to changes in tax relief for landlords. Since April 2020, individual landlords can no longer deduct mortgage interest from rental income — they receive a 20% tax credit instead. For higher-rate taxpayers, buying through a limited company (Special Purpose Vehicle) can be more tax efficient. However, the answer depends on your personal circumstances, the number of properties you own, and your long-term plans. We can advise on the mortgage implications; we'd recommend speaking to a tax adviser for the full picture." },
      { question: "Can I get a mortgage on an HMO (house in multiple occupation)?", answer: "Yes, but HMO mortgages are a specialist area. Not all lenders will finance HMOs, and those that do have specific criteria around licensing, room numbers, property type and rental income. We have experience sourcing HMO mortgages and know which lenders are most flexible. Whether it's a small HMO (3-6 rooms) or a large licensed HMO (7+ rooms), we can find suitable options." },
    ] },
    { category: "The Mortgage Process", questions: [
      { question: "How long does the mortgage process take?", answer: "From initial application to receiving a formal mortgage offer typically takes 2-4 weeks, depending on the lender and the complexity of your case. The full process from offer acceptance to completion (including legal work and surveys) usually takes 8-12 weeks for a purchase. Remortgages are often quicker — sometimes 4-6 weeks. We manage the process actively to avoid unnecessary delays." },
      { question: "What documents will I need to provide?", answer: "Typically you'll need: proof of identity (passport or driving licence), proof of address (utility bill or bank statement), 3 months' payslips (or 2 years' accounts/SA302s if self-employed), 3 months' bank statements, proof of deposit, and details of any existing financial commitments. Self-employed applicants and company directors may need additional documentation. We'll give you a clear checklist at your initial consultation." },
      { question: "What happens if my mortgage application is declined?", answer: "A decline doesn't mean you can't get a mortgage — it usually means that particular lender's criteria didn't match your circumstances. Every lender has different criteria, and what one declines, another may approve. As whole of market brokers, we know each lender's specific requirements and can often identify the issue and find an alternative. We'll always discuss the reason for the decline with you and explain your options." },
    ] },
  ];

  const faqSchema = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faqs.flatMap((c) => c.questions.map((q) => ({ "@type": "Question", name: q.question, acceptedAnswer: { "@type": "Answer", text: q.answer } }))) };

  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} />
      <section className="hero-gradient py-20 lg:py-28"><div className="container-width"><div className="max-w-3xl"><span className="text-accent font-semibold tracking-wider uppercase text-sm">FAQ</span><h1 className="text-4xl md:text-5xl font-bold text-white mt-4 mb-6">Frequently Asked Questions</h1><p className="text-xl text-gray-200 leading-relaxed">Answers to common questions about mortgages, our broker service, and the home-buying process.</p></div></div></section>

      <section className="section-padding bg-white"><div className="container-width"><div className="max-w-4xl mx-auto">
        {faqs.map((cat, ci) => (<div key={ci} className="mb-12"><h2 className="text-2xl font-bold text-primary mb-6 flex items-center gap-3"><div className="w-1 h-8 bg-accent"></div>{cat.category}</h2><div className="space-y-1">{cat.questions.map((faq, fi) => (<details key={fi} className="group bg-gray-50 rounded-sm overflow-hidden"><summary className="faq-question p-6 list-none cursor-pointer"><span className="flex-1 pr-4">{faq.question}</span><svg className="w-5 h-5 text-accent flex-shrink-0 transition-transform duration-300 group-open:rotate-180" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" /></svg></summary><div className="px-6 pb-6"><p className="text-gray-600 leading-relaxed">{faq.answer}</p></div></details>))}</div></div>))}
      </div></div></section>

      <section className="section-padding bg-gray-50"><div className="container-width"><div className="max-w-3xl mx-auto text-center"><h2 className="text-3xl font-bold text-primary mb-4">Still Have Questions?</h2><div className="gold-line-center mb-6"></div><p className="text-lg text-gray-600 mb-8">We&apos;re always happy to answer your questions. Get in touch for a free, no-obligation chat about your mortgage options.</p><div className="flex flex-col sm:flex-row justify-center gap-4"><Link href="/mortgage-broker-stratford/contact" className="btn-accent">Contact Us</Link><a href="tel:02079466901" className="btn-outline">Call 020 7946 6901</a></div></div></div></section>

      <section className="section-padding bg-primary"><div className="container-width text-center"><h2 className="text-3xl md:text-4xl font-bold text-white mb-4">Ready to Find Your Best Mortgage Deal?</h2><p className="text-xl text-gray-200 mb-8 max-w-2xl mx-auto">Book a free consultation at our Stratford office or by phone. No jargon, no pressure, just honest mortgage advice.</p><Link href="/mortgage-broker-stratford/contact" className="btn-accent">Book Free Consultation</Link></div></section>
    </>
  );
}
