import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Legal Services | Conveyancing, Family Law & Wills in Wimbledon",
  description: "Expert legal services in Wimbledon, SW19. Conveyancing, family law, wills & probate, employment law, commercial law and immigration from SRA regulated solicitors.",
  openGraph: { title: "Legal Services | Wimbledon Legal Services", description: "SRA regulated legal services in Wimbledon. Conveyancing, family law, wills, employment, commercial and immigration." },
};

export default function ServicesPage() {
  const services = [
    { id: "conveyancing", title: "Conveyancing", subtitle: "Smooth Property Transactions", description: "Our conveyancing team handles residential and commercial property transactions with efficiency and attention to detail. Whether you are buying your first home, selling an investment property or remortgaging, we manage the legal process from instruction to completion.", features: ["Freehold and leasehold purchases and sales", "Remortgage and transfer of equity", "New build and off-plan transactions", "Shared ownership and Help to Buy", "Commercial property transactions", "Auction purchases with rapid turnaround"], icon: <svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6" /></svg> },
    { id: "family-law", title: "Family Law", subtitle: "Compassionate, Practical Guidance", description: "Family matters require sensitivity and understanding alongside firm legal expertise. Our family law solicitors guide you through divorce, separation, child arrangements and financial disputes with compassion, always focusing on achieving the best outcome for you and your family.", features: ["Divorce and judicial separation", "Child arrangement orders and custody", "Financial settlements and consent orders", "Pre-nuptial and post-nuptial agreements", "Domestic violence and non-molestation orders", "Mediation and collaborative law"], icon: <svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z" /></svg> },
    { id: "wills-probate", title: "Wills & Probate", subtitle: "Protect Your Legacy", description: "Planning for the future gives you peace of mind. Our wills and probate team helps you create legally sound wills, establish powers of attorney and administer estates with care and efficiency, ensuring your wishes are carried out exactly as intended.", features: ["Will drafting and review", "Lasting Powers of Attorney (LPA)", "Estate administration and probate applications", "Inheritance Tax planning", "Trusts and trust administration", "Contested wills and inheritance disputes"], icon: <svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" /></svg> },
    { id: "employment-law", title: "Employment Law", subtitle: "Your Rights at Work", description: "Whether you are an employee facing unfair treatment or an employer needing HR legal support, our employment law team provides clear, decisive advice. We handle everything from contract reviews to Employment Tribunal representation.", features: ["Unfair and constructive dismissal claims", "Settlement agreements (formerly compromise agreements)", "Employment contracts and restrictive covenants", "Discrimination and harassment claims", "Redundancy advice and TUPE transfers", "Employment Tribunal representation"], icon: <svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M21 13.255A23.931 23.931 0 0112 15c-3.183 0-6.22-.62-9-1.745M16 6V4a2 2 0 00-2-2h-4a2 2 0 00-2 2v2m4 6h.01M5 20h14a2 2 0 002-2V8a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" /></svg> },
    { id: "commercial-law", title: "Commercial Law", subtitle: "Practical Business Legal Advice", description: "We support businesses of all sizes with practical, commercial legal advice. From drafting contracts and partnership agreements to resolving disputes and managing business sales, our commercial team helps you protect and grow your business.", features: ["Commercial contracts and terms of business", "Partnership and shareholder agreements", "Business sales and acquisitions", "Commercial lease negotiations", "Debt recovery and dispute resolution", "Company and director compliance"], icon: <svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M19 21V5a2 2 0 00-2-2H7a2 2 0 00-2 2v16m14 0h2m-2 0h-5m-9 0H3m2 0h5M9 7h1m-1 4h1m4-4h1m-1 4h1m-5 10v-5a1 1 0 011-1h2a1 1 0 011 1v5m-4 0h4" /></svg> },
    { id: "immigration", title: "Immigration", subtitle: "Navigate the UK Immigration System", description: "The UK immigration system is complex and constantly changing. Our specialist immigration solicitors guide individuals and businesses through visa applications, settlement, citizenship and appeals with expertise and a high success rate.", features: ["Spouse, partner and family visas", "Skilled Worker and Global Talent visas", "Indefinite Leave to Remain (ILR) applications", "British citizenship and naturalisation", "Sponsor licence applications for employers", "Immigration appeals and judicial reviews"], icon: <svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M3.055 11H5a2 2 0 012 2v1a2 2 0 002 2 2 2 0 012 2v2.945M8 3.935V5.5A2.5 2.5 0 0010.5 8h.5a2 2 0 012 2 2 2 0 104 0 2 2 0 012-2h1.064M15 20.488V18a2 2 0 012-2h3.064M21 12a9 9 0 11-18 0 9 9 0 0118 0z" /></svg> },
  ];

  return (
    <>
      <section className="hero-gradient py-20 lg:py-28"><div className="container-width"><div className="max-w-3xl"><span className="text-accent font-semibold tracking-wider uppercase text-sm">Our Services</span><h1 className="text-4xl md:text-5xl font-bold text-white mt-4 mb-6">Comprehensive Legal Services</h1><p className="text-xl text-gray-200 leading-relaxed">Expert legal advice across a wide range of practice areas, delivered by SRA regulated solicitors with a commitment to clear communication and outstanding results.</p></div></div></section>

      <section className="section-padding bg-white">
        <div className="container-width">
          <div className="text-center mb-16"><h2 className="text-3xl md:text-4xl font-bold text-primary mb-4">Expert Legal Advice</h2><div className="gold-line-center mb-6"></div><p className="text-lg text-gray-600 max-w-3xl mx-auto">As SRA regulated solicitors and Law Society members, we uphold the highest standards of professional conduct in every matter we handle.</p></div>
          <div className="space-y-16">
            {services.map((service, index) => (
              <div key={service.id} id={service.id} className={`grid lg:grid-cols-2 gap-12 items-center ${index % 2 === 1 ? "lg:flex-row-reverse" : ""}`}>
                <div className={index % 2 === 1 ? "lg:order-2" : ""}><div className="text-primary mb-4">{service.icon}</div><h3 className="text-2xl md:text-3xl font-bold text-primary mb-2">{service.title}</h3><p className="text-accent font-semibold mb-4">{service.subtitle}</p><p className="text-gray-600 mb-6 leading-relaxed">{service.description}</p><ul className="space-y-3 mb-8">{service.features.map((feature, i) => (<li key={i} className="flex items-start gap-3"><svg className="w-5 h-5 text-accent mt-0.5 flex-shrink-0" fill="currentColor" viewBox="0 0 20 20"><path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" /></svg><span className="text-gray-700">{feature}</span></li>))}</ul><Link href="/solicitor-wimbledon/contact" className="btn-accent">Discuss Your Case</Link></div>
                <div className={`bg-gray-50 p-8 lg:p-12 rounded-sm ${index % 2 === 1 ? "lg:order-1" : ""}`}><div className="aspect-video bg-gradient-to-br from-primary to-secondary rounded-sm flex items-center justify-center"><div className="text-white opacity-20 scale-150">{service.icon}</div></div></div>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section className="section-padding bg-gray-50"><div className="container-width"><div className="text-center mb-16"><span className="text-accent font-semibold tracking-wider uppercase text-sm">Our Process</span><h2 className="text-3xl md:text-4xl font-bold text-primary mt-4 mb-4">How We Work</h2><div className="gold-line-center mb-6"></div></div><div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8"><div className="text-center"><div className="w-16 h-16 bg-primary text-white rounded-full flex items-center justify-center mx-auto mb-4 text-2xl font-bold">1</div><h3 className="text-xl font-bold text-primary mb-2">Free Consultation</h3><p className="text-gray-600">We discuss your situation, explain the law in plain English and outline your options with no obligation.</p></div><div className="text-center"><div className="w-16 h-16 bg-primary text-white rounded-full flex items-center justify-center mx-auto mb-4 text-2xl font-bold">2</div><h3 className="text-xl font-bold text-primary mb-2">Clear Fee Quote</h3><p className="text-gray-600">We provide a detailed, transparent fee estimate so you know exactly what your legal costs will be.</p></div><div className="text-center"><div className="w-16 h-16 bg-primary text-white rounded-full flex items-center justify-center mx-auto mb-4 text-2xl font-bold">3</div><h3 className="text-xl font-bold text-primary mb-2">Expert Handling</h3><p className="text-gray-600">Your dedicated solicitor manages your case with skill, keeping you informed at every stage.</p></div><div className="text-center"><div className="w-16 h-16 bg-primary text-white rounded-full flex items-center justify-center mx-auto mb-4 text-2xl font-bold">4</div><h3 className="text-xl font-bold text-primary mb-2">Successful Outcome</h3><p className="text-gray-600">We work tirelessly to achieve the best possible outcome and ensure you are completely satisfied.</p></div></div></div></section>

      <section className="section-padding bg-primary"><div className="container-width text-center"><h2 className="text-3xl md:text-4xl font-bold text-white mb-4">Need Legal Advice Today?</h2><p className="text-xl text-gray-200 mb-8 max-w-2xl mx-auto">Book a free initial consultation and speak directly with an experienced solicitor about your legal matter.</p><div className="flex flex-col sm:flex-row justify-center gap-4"><Link href="/solicitor-wimbledon/contact" className="btn-accent">Free Initial Consultation</Link><a href="tel:02079464567" className="btn-outline border-white text-white hover:bg-white hover:text-primary">Call 020 7946 4567</a></div></div></section>

      <section className="py-8 bg-gray-100"><div className="container-width"><div className="fca-notice"><p><strong>Regulatory Notice:</strong> Wimbledon Legal Services is authorised and regulated by the Solicitors Regulation Authority (SRA). All work is covered by professional indemnity insurance. Legal aid is available for eligible cases.</p></div></div></section>
    </>
  );
}
