import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "About Us | Eco-Friendly Dry Cleaning Since 2008",
  description: "Learn about Kensington Dry Cleaners - premium eco-friendly dry cleaning on Kensington High Street since 2008. 15,000+ garments per year, free collection and delivery.",
  openGraph: { title: "About Us | Kensington Dry Cleaners", description: "Premium eco-friendly dry cleaning on Kensington High Street since 2008." },
};

export default function AboutPage() {
  return (
    <>
      <section className="hero-gradient py-20 lg:py-28"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="max-w-3xl"><span className="text-[var(--accent)] font-semibold tracking-wider uppercase text-sm">About Us</span><h1 className="text-4xl md:text-5xl font-bold text-white mt-4 mb-6">Kensington&apos;s Trusted Dry Cleaner</h1><p className="text-xl text-gray-200 leading-relaxed">Since 2008, we have been providing premium garment care to the residents and businesses of Kensington and the surrounding boroughs.</p></div></div></section>

      <section className="py-16 lg:py-24 bg-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="grid lg:grid-cols-2 gap-16 items-center">
          <div><span className="text-[var(--accent)] font-semibold tracking-wider uppercase text-sm">Our Story</span><h2 className="text-3xl md:text-4xl font-bold text-[var(--primary)] mt-4 mb-4">From a Local Shop to a Trusted Name in Garment Care</h2><div className="w-16 h-1 bg-[var(--accent)] mb-6"></div>
            <p className="text-lg text-gray-600 mb-6 leading-relaxed">Kensington Dry Cleaners was founded in 2008 with a simple promise: to provide garment care of the highest standard, using methods that are kind to both fabrics and the environment. At a time when most dry cleaners still relied on harsh chemical solvents, we were one of the first in London to adopt GreenEarth eco-friendly technology.</p>
            <p className="text-gray-600 mb-6 leading-relaxed">Our reputation grew through word of mouth. Customers appreciated the quality of our cleaning, the convenience of our collection and delivery service, and the genuine care we took with every garment. From a favourite cashmere jumper to a couture evening gown, we treat every item as though it were our own.</p>
            <p className="text-gray-600 leading-relaxed">Today, we process over 15,000 garments per year and serve customers across Kensington, Chelsea, Notting Hill, Holland Park and beyond. Our team includes an experienced in-house seamstress and a specialist bridal care consultant. We remain a proudly independent, family-run business.</p>
          </div>
          <div className="bg-gray-50 p-8 lg:p-12 rounded-sm"><div className="grid grid-cols-2 gap-8">
            <div className="text-center p-6 bg-white rounded-sm shadow-sm"><div className="text-4xl font-bold text-[var(--accent)] font-serif">17+</div><p className="text-gray-600 mt-2 font-medium">Years of Service</p></div>
            <div className="text-center p-6 bg-white rounded-sm shadow-sm"><div className="text-4xl font-bold text-[var(--accent)] font-serif">15k+</div><p className="text-gray-600 mt-2 font-medium">Garments/Year</p></div>
            <div className="text-center p-6 bg-white rounded-sm shadow-sm"><div className="text-4xl font-bold text-[var(--accent)] font-serif">Free</div><p className="text-gray-600 mt-2 font-medium">Collection &amp; Delivery</p></div>
            <div className="text-center p-6 bg-white rounded-sm shadow-sm"><div className="text-4xl font-bold text-[var(--accent)] font-serif">100%</div><p className="text-gray-600 mt-2 font-medium">Eco-Friendly</p></div>
          </div></div>
        </div></div>
      </section>

      <section className="py-16 lg:py-24 bg-gray-50"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="text-center mb-16"><span className="text-[var(--accent)] font-semibold tracking-wider uppercase text-sm">Our Values</span><h2 className="text-3xl md:text-4xl font-bold text-[var(--primary)] mt-4 mb-4">What Drives Us</h2><div className="w-16 h-1 bg-[var(--accent)] mx-auto mb-6"></div></div>
        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
          <div className="bg-white p-8 rounded-sm shadow-sm"><div className="w-16 h-16 bg-[var(--primary)]/10 rounded-full flex items-center justify-center mb-6"><svg className="w-8 h-8 text-[var(--primary)]" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M3.055 11H5a2 2 0 012 2v1a2 2 0 002 2 2 2 0 012 2v2.945M8 3.935V5.5A2.5 2.5 0 0010.5 8h.5a2 2 0 012 2 2 2 0 104 0 2 2 0 012-2h1.064M15 20.488V18a2 2 0 012-2h3.064M21 12a9 9 0 11-18 0 9 9 0 0118 0z" /></svg></div><h3 className="text-xl font-bold text-[var(--primary)] mb-3">Environmental Care</h3><p className="text-gray-600">Our GreenEarth solvents are silicone-based, non-toxic and biodegradable. We recycle hangers, minimise packaging and continuously look for ways to reduce our environmental footprint.</p></div>
          <div className="bg-white p-8 rounded-sm shadow-sm"><div className="w-16 h-16 bg-[var(--primary)]/10 rounded-full flex items-center justify-center mb-6"><svg className="w-8 h-8 text-[var(--primary)]" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" /></svg></div><h3 className="text-xl font-bold text-[var(--primary)] mb-3">Quality First</h3><p className="text-gray-600">Every garment passes through a multi-point quality check before it leaves our premises. We would rather redo a job than let anything leave that does not meet our standards.</p></div>
          <div className="bg-white p-8 rounded-sm shadow-sm"><div className="w-16 h-16 bg-[var(--primary)]/10 rounded-full flex items-center justify-center mb-6"><svg className="w-8 h-8 text-[var(--primary)]" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" /></svg></div><h3 className="text-xl font-bold text-[var(--primary)] mb-3">Convenience</h3><p className="text-gray-600">Free collection and delivery, same-day express and long opening hours. We fit around your life, not the other way around.</p></div>
          <div className="bg-white p-8 rounded-sm shadow-sm"><div className="w-16 h-16 bg-[var(--primary)]/10 rounded-full flex items-center justify-center mb-6"><svg className="w-8 h-8 text-[var(--primary)]" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z" /></svg></div><h3 className="text-xl font-bold text-[var(--primary)] mb-3">Personal Service</h3><p className="text-gray-600">We are a family-run business and treat every customer as we would treat our own family. You will see the same friendly faces every time you visit.</p></div>
          <div className="bg-white p-8 rounded-sm shadow-sm"><div className="w-16 h-16 bg-[var(--primary)]/10 rounded-full flex items-center justify-center mb-6"><svg className="w-8 h-8 text-[var(--primary)]" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M19.428 15.428a2 2 0 00-1.022-.547l-2.387-.477a6 6 0 00-3.86.517l-.318.158a6 6 0 01-3.86.517L6.05 15.21a2 2 0 00-1.806.547M8 4h8l-1 1v5.172a2 2 0 00.586 1.414l5 5c1.26 1.26.367 3.414-1.415 3.414H4.828c-1.782 0-2.674-2.154-1.414-3.414l5-5A2 2 0 009 10.172V5L8 4z" /></svg></div><h3 className="text-xl font-bold text-[var(--primary)] mb-3">Expertise</h3><p className="text-gray-600">With 17 years of experience and specialist training in fabric care, stain removal and garment restoration, we handle the most delicate and valuable items with confidence.</p></div>
          <div className="bg-white p-8 rounded-sm shadow-sm"><div className="w-16 h-16 bg-[var(--primary)]/10 rounded-full flex items-center justify-center mb-6"><svg className="w-8 h-8 text-[var(--primary)]" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-6 9l2 2 4-4" /></svg></div><h3 className="text-xl font-bold text-[var(--primary)] mb-3">Transparency</h3><p className="text-gray-600">Clear pricing, honest advice and no hidden charges. If we spot an issue with your garment, we will tell you before we proceed and give you options.</p></div>
        </div>
      </div></section>

      <section className="py-16 lg:py-24 bg-white"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="text-center mb-16"><span className="text-[var(--accent)] font-semibold tracking-wider uppercase text-sm">Our Location</span><h2 className="text-3xl md:text-4xl font-bold text-[var(--primary)] mt-4 mb-4">On Kensington High Street</h2><div className="w-16 h-1 bg-[var(--accent)] mx-auto mb-6"></div><p className="text-lg text-gray-600 max-w-3xl mx-auto">Conveniently located on Kensington High Street, just one minute from High Street Kensington Underground station. Easy to find, easy to reach.</p></div>
        <div className="bg-gray-50 p-8 lg:p-12 rounded-sm max-w-3xl mx-auto"><div className="grid md:grid-cols-2 gap-8">
          <div><h3 className="text-xl font-bold text-[var(--primary)] mb-4">Getting Here</h3><address className="not-italic text-gray-700 mb-4"><strong>112 Kensington High Street</strong><br />Kensington, London W8 7RW</address><ul className="space-y-2 text-gray-600"><li className="flex items-center gap-2"><svg className="w-4 h-4 text-[var(--accent)]" fill="currentColor" viewBox="0 0 20 20"><path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" /></svg>High Street Kensington - 1 min walk</li><li className="flex items-center gap-2"><svg className="w-4 h-4 text-[var(--accent)]" fill="currentColor" viewBox="0 0 20 20"><path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" /></svg>Kensington Olympia - 6 min walk</li></ul></div>
          <div><h3 className="text-xl font-bold text-[var(--primary)] mb-4">Opening Hours</h3><div className="space-y-2 text-gray-600"><p><strong>Monday - Friday:</strong> 7:30am - 7pm</p><p><strong>Saturday:</strong> 8am - 5pm</p><p><strong>Sunday:</strong> Closed</p></div></div>
        </div></div>
      </div></section>

      <section className="py-16 lg:py-24 bg-[var(--primary)]"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center"><h2 className="text-3xl md:text-4xl font-bold text-white mb-4">Experience the Difference</h2><p className="text-xl text-gray-200 mb-8 max-w-2xl mx-auto">Book a free collection or drop in today. We look forward to taking care of your wardrobe.</p><div className="flex flex-col sm:flex-row justify-center gap-4"><Link href="/dry-cleaner-kensington/contact" className="bg-[var(--accent)] text-white px-8 py-4 font-semibold rounded-sm hover:bg-[var(--accent-light)] transition-colors">Book a Collection</Link><a href="tel:02079465530" className="border-2 border-white text-white px-8 py-4 font-semibold rounded-sm hover:bg-white hover:text-[var(--primary)] transition-colors">Call 020 7946 5530</a></div></div></section>
    </>
  );
}
