import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "About Us | Professional Decorators Since 2012",
  description: "Learn about Brixton Decorating Services - professional painters and decorators on Atlantic Road since 2012. Eight experienced decorators, Dulux Select Decorator accreditation, fully insured.",
  openGraph: { title: "About Us | Brixton Decorating Services", description: "Professional painters and decorators in Brixton since 2012. Dulux Select Decorator, fully insured, over 2,500 projects completed." },
};

export default function AboutPage() {
  return (
    <>
      <section className="hero-gradient py-20 lg:py-28"><div className="container-width"><div className="max-w-3xl"><span className="text-accent font-semibold tracking-wider uppercase text-sm">About Us</span><h1 className="text-4xl md:text-5xl font-bold text-white mt-4 mb-6">Brixton&apos;s Trusted Decorators</h1><p className="text-xl text-gray-200 leading-relaxed">Since 2012, Brixton Decorating Services has been transforming homes and businesses across South London with professional painting and decorating.</p></div></div></section>

      <section className="section-padding bg-white"><div className="container-width"><div className="grid lg:grid-cols-2 gap-16 items-center">
        <div><span className="text-accent font-semibold tracking-wider uppercase text-sm">Our Story</span><h2 className="text-3xl md:text-4xl font-bold text-primary mt-4 mb-4">Honest Work Since 2012</h2><div className="gold-line mb-6"></div>
          <p className="text-lg text-gray-600 mb-6 leading-relaxed">Brixton Decorating Services was founded by two friends who had spent years working for large decorating firms and knew there was a better way to do things. Too many decorating companies cut corners on preparation, use cheap materials, and leave customers with finishes that start to look tired within months. We set out to be different.</p>
          <p className="text-gray-600 mb-6 leading-relaxed">We started with just the two of us working out of a van. Word of mouth spread quickly, and within a couple of years we had more work than we could handle. Today our team of eight experienced decorators covers all of South London, from Brixton and Herne Hill to Dulwich, Clapham, Streatham and beyond. We still run every job the same way we did on day one &mdash; thorough preparation, premium materials and a finish we&apos;re proud to put our name to.</p>
          <p className="text-gray-600 leading-relaxed">In 2016 we were accepted into the Dulux Select Decorators scheme, which means our work is independently vetted and we commit to the highest standards in the industry. We&apos;re fully insured, we provide free detailed estimates, and we never start a job until you&apos;re completely happy with the plan and the price.</p>
        </div>
        <div className="bg-gray-50 p-8 lg:p-12 rounded-sm"><div className="grid grid-cols-2 gap-8">
          <div className="text-center p-6 bg-white rounded-sm shadow-sm"><div className="stat-number">13+</div><p className="text-gray-600 mt-2 font-medium">Years in Business</p></div>
          <div className="text-center p-6 bg-white rounded-sm shadow-sm"><div className="stat-number">2,500+</div><p className="text-gray-600 mt-2 font-medium">Projects Completed</p></div>
          <div className="text-center p-6 bg-white rounded-sm shadow-sm"><div className="stat-number">8</div><p className="text-gray-600 mt-2 font-medium">Expert Decorators</p></div>
          <div className="text-center p-6 bg-white rounded-sm shadow-sm"><div className="stat-number">4.9</div><p className="text-gray-600 mt-2 font-medium">Google Rating</p></div>
        </div></div>
      </div></div></section>

      <section className="section-padding bg-gray-50"><div className="container-width"><div className="text-center mb-16"><span className="text-accent font-semibold tracking-wider uppercase text-sm">Our Values</span><h2 className="text-3xl md:text-4xl font-bold text-primary mt-4 mb-4">What Sets Us Apart</h2><div className="gold-line-center mb-6"></div></div>
        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
          <div className="card-premium p-8"><div className="w-16 h-16 bg-primary/10 rounded-full flex items-center justify-center mb-6"><svg className="w-8 h-8 text-primary" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" /></svg></div><h3 className="text-xl font-bold text-primary mb-3">Preparation is Everything</h3><p className="text-gray-600">A beautiful finish starts with proper preparation. We never skip steps &mdash; every crack is filled, every surface is sanded, and every edge is masked before a brush touches a wall.</p></div>
          <div className="card-premium p-8"><div className="w-16 h-16 bg-primary/10 rounded-full flex items-center justify-center mb-6"><svg className="w-8 h-8 text-primary" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M19.428 15.428a2 2 0 00-1.022-.547l-2.387-.477a6 6 0 00-3.86.517l-.318.158a6 6 0 01-3.86.517L6.05 15.21a2 2 0 00-1.806.547M8 4h8l-1 1v5.172a2 2 0 00.586 1.414l5 5c1.26 1.26.367 3.414-1.415 3.414H4.828c-1.782 0-2.674-2.154-1.414-3.414l5-5A2 2 0 009 10.172V5L8 4z" /></svg></div><h3 className="text-xl font-bold text-primary mb-3">Premium Materials</h3><p className="text-gray-600">We use only professional-grade paints and materials from brands like Dulux, Farrow &amp; Ball and Little Greene. Quality products mean a better finish that lasts longer.</p></div>
          <div className="card-premium p-8"><div className="w-16 h-16 bg-primary/10 rounded-full flex items-center justify-center mb-6"><svg className="w-8 h-8 text-primary" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1M21 12a9 9 0 11-18 0 9 9 0 0118 0z" /></svg></div><h3 className="text-xl font-bold text-primary mb-3">Transparent Pricing</h3><p className="text-gray-600">Our detailed written estimates break down every cost. The price we quote is the price you pay &mdash; no hidden extras, no surprises, no awkward conversations at the end.</p></div>
          <div className="card-premium p-8"><div className="w-16 h-16 bg-primary/10 rounded-full flex items-center justify-center mb-6"><svg className="w-8 h-8 text-primary" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" /></svg></div><h3 className="text-xl font-bold text-primary mb-3">Reliable &amp; Punctual</h3><p className="text-gray-600">We turn up when we say we will and finish when we say we will. We respect your time and your home, and we keep you informed throughout every project.</p></div>
          <div className="card-premium p-8"><div className="w-16 h-16 bg-primary/10 rounded-full flex items-center justify-center mb-6"><svg className="w-8 h-8 text-primary" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6" /></svg></div><h3 className="text-xl font-bold text-primary mb-3">Clean &amp; Tidy</h3><p className="text-gray-600">We protect your belongings thoroughly, clean up at the end of each day, and leave your property spotless when the job is finished. You will barely know we have been there.</p></div>
          <div className="card-premium p-8"><div className="w-16 h-16 bg-primary/10 rounded-full flex items-center justify-center mb-6"><svg className="w-8 h-8 text-primary" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z" /><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M15 11a3 3 0 11-6 0 3 3 0 016 0z" /></svg></div><h3 className="text-xl font-bold text-primary mb-3">Local Knowledge</h3><p className="text-gray-600">Based on Atlantic Road in the heart of Brixton, we know South London&apos;s housing stock inside out &mdash; from Victorian terraces to modern new builds.</p></div>
        </div>
      </div></section>

      <section className="section-padding bg-white"><div className="container-width"><div className="text-center mb-16"><span className="text-accent font-semibold tracking-wider uppercase text-sm">Our Location</span><h2 className="text-3xl md:text-4xl font-bold text-primary mt-4 mb-4">Atlantic Road, Brixton</h2><div className="gold-line-center mb-6"></div><p className="text-lg text-gray-600 max-w-3xl mx-auto">Our office is on Atlantic Road, right in the heart of Brixton. We cover all of South London and are easy to reach by tube, bus or car.</p></div>
        <div className="grid md:grid-cols-3 gap-8">
          <div className="text-center p-8 bg-gray-50 rounded-sm"><svg className="w-10 h-10 text-accent mx-auto mb-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z" /><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M15 11a3 3 0 11-6 0 3 3 0 016 0z" /></svg><h3 className="text-lg font-bold text-primary mb-2">Brixton</h3><p className="text-gray-600">3-minute walk</p></div>
          <div className="text-center p-8 bg-gray-50 rounded-sm"><svg className="w-10 h-10 text-accent mx-auto mb-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z" /><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M15 11a3 3 0 11-6 0 3 3 0 016 0z" /></svg><h3 className="text-lg font-bold text-primary mb-2">Stockwell</h3><p className="text-gray-600">8-minute walk</p></div>
          <div className="text-center p-8 bg-gray-50 rounded-sm"><svg className="w-10 h-10 text-accent mx-auto mb-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z" /><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M15 11a3 3 0 11-6 0 3 3 0 016 0z" /></svg><h3 className="text-lg font-bold text-primary mb-2">Oval</h3><p className="text-gray-600">10-minute walk</p></div>
        </div>
      </div></section>

      <section className="section-padding bg-primary"><div className="container-width text-center"><h2 className="text-3xl md:text-4xl font-bold text-white mb-4">Need a Decorator? Let&apos;s Talk</h2><p className="text-xl text-gray-200 mb-8 max-w-2xl mx-auto">Get in touch for a free, no-obligation estimate. We&apos;ll visit your property, discuss what you need, and provide a detailed written quote.</p><div className="flex flex-col sm:flex-row justify-center gap-4"><Link href="/painter-decorator-brixton/contact" className="btn-accent">Get a Free Quote</Link><a href="tel:02079462270" className="btn-outline border-white text-white hover:bg-white hover:text-primary">Call 020 7946 2270</a></div></div></section>
    </>
  );
}
