import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Treatments | Traditional Acupuncture, Fertility, Pain & Stress Relief",
  description: "Full range of acupuncture treatments at Marylebone Acupuncture Clinic. Traditional acupuncture, fertility support, pain management, stress relief, cosmetic acupuncture and cupping therapy.",
  openGraph: { title: "Treatments | Marylebone Acupuncture Clinic", description: "Expert acupuncture treatments from a BAcC registered practitioner in Marylebone, London W1." },
};

export default function ServicesPage() {
  const services = [
    { id: "traditional-acupuncture", title: "Traditional Acupuncture", subtitle: "Restoring Balance, Promoting Wellness", description: "Traditional acupuncture works by stimulating specific points on the body to restore the natural flow of Qi (vital energy). Drawing on both five-element and TCM (Traditional Chinese Medicine) approaches, we treat the root cause of illness rather than just managing symptoms. Treatment is gentle, deeply relaxing, and effective for a wide range of conditions including digestive issues, headaches, fatigue, insomnia and general wellbeing.", features: ["Five-element and TCM diagnostic approaches", "Gentle needling technique with ultra-fine sterile needles", "Treats digestive, respiratory and immune conditions", "Addresses fatigue, insomnia and low energy", "Supports overall wellbeing and prevention", "Often combined with moxibustion for enhanced effect"], icon: <svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1M21 12a9 9 0 11-18 0 9 9 0 0118 0z" /></svg> },
    { id: "fertility-acupuncture", title: "Fertility Acupuncture", subtitle: "Supporting Your Journey to Parenthood", description: "Our fertility acupuncture programme supports both natural conception and assisted reproduction (IVF/ICSI). Research shows that acupuncture can improve blood flow to the reproductive organs, regulate hormones, reduce stress and enhance the uterine lining. We work alongside your fertility clinic to provide complementary support throughout your treatment cycle.", features: ["Evidence-based fertility protocols", "Support for natural conception and IVF/ICSI", "Hormone regulation and cycle optimisation", "Pre- and post-embryo transfer treatments", "Male fertility support also available", "Close liaison with London fertility clinics"], icon: <svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z" /></svg> },
    { id: "pain-management", title: "Pain Management", subtitle: "Natural, Effective Pain Relief", description: "Acupuncture is recognised by NICE (National Institute for Health and Care Excellence) as an effective treatment for chronic pain. We treat a wide range of pain conditions including lower back pain, neck and shoulder pain, migraines, sciatica, arthritis, tennis elbow and post-surgical pain. Treatment works by stimulating the body's natural pain-relieving mechanisms and reducing inflammation.", features: ["NICE-recommended for chronic pain", "Back pain, neck pain and sciatica", "Migraine and tension headache relief", "Arthritis and joint pain management", "Sports injuries and rehabilitation", "Often effective where other treatments have failed"], icon: <svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M13 10V3L4 14h7v7l9-11h-7z" /></svg> },
    { id: "stress-anxiety", title: "Stress & Anxiety Treatment", subtitle: "Find Your Calm", description: "In our fast-paced London lives, stress and anxiety have become epidemic. Acupuncture offers a powerful, drug-free way to calm the nervous system, reduce cortisol levels and restore a sense of inner peace. Many patients report improvements after just one or two sessions, with cumulative benefits over a course of treatment.", features: ["Regulates the nervous system naturally", "Reduces cortisol and stress hormones", "Improves sleep quality and duration", "Supports those reducing anxiety medication", "Combines acupuncture with auricular (ear) points", "Deeply relaxing — many patients fall asleep during treatment"], icon: <svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M14.828 14.828a4 4 0 01-5.656 0M9 10h.01M15 10h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" /></svg> },
    { id: "cosmetic-acupuncture", title: "Cosmetic Acupuncture", subtitle: "Natural Facial Rejuvenation", description: "Cosmetic acupuncture is a natural, non-invasive alternative to Botox and fillers. Fine needles are inserted into specific facial points to stimulate collagen and elastin production, improve blood flow to the skin, and reduce the appearance of fine lines, wrinkles and sagging. The result is a healthy, radiant complexion that looks naturally youthful.", features: ["Stimulates natural collagen production", "Reduces fine lines and wrinkles", "Improves skin tone, texture and elasticity", "Reduces puffiness and dark circles", "No chemicals, toxins or downtime", "Course of 10 sessions recommended for best results"], icon: <svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M5 3v4M3 5h4M6 17v4m-2-2h4m5-16l2.286 6.857L21 12l-5.714 2.143L13 21l-2.286-6.857L5 12l5.714-2.143L13 3z" /></svg> },
    { id: "cupping-therapy", title: "Cupping Therapy", subtitle: "Deep Muscle Relief & Detoxification", description: "Cupping is an ancient therapy that uses suction cups on the skin to relieve deep muscle tension, improve blood circulation and support the body's natural detoxification processes. It's particularly effective for back and shoulder pain, respiratory conditions, and recovery from physical exertion. Often combined with acupuncture for enhanced results.", features: ["Relieves deep muscular tension and knots", "Improves blood circulation and lymphatic drainage", "Supports respiratory health and immune function", "Effective for back, neck and shoulder pain", "Both static and sliding cupping techniques", "Can be combined with acupuncture treatment"], icon: <svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" /></svg> },
  ];

  return (
    <>
      <section className="hero-gradient py-20 lg:py-28"><div className="container-width"><div className="max-w-3xl">
        <span className="text-accent font-semibold tracking-wider uppercase text-sm">Our Treatments</span>
        <h1 className="text-4xl md:text-5xl font-bold text-white mt-4 mb-6">Acupuncture Treatments</h1>
        <p className="text-xl text-gray-200 leading-relaxed">Evidence-based acupuncture treatments tailored to your individual needs. Every session is personalised to address your specific health concerns.</p>
      </div></div></section>

      <section className="section-padding bg-white"><div className="container-width">
        <div className="text-center mb-16"><h2 className="text-3xl md:text-4xl font-bold text-primary mb-4">How Acupuncture Can Help You</h2><div className="gold-line-center mb-6"></div><p className="text-lg text-gray-600 max-w-3xl mx-auto">As a BAcC registered practitioner with a BSc in Acupuncture, I combine traditional Chinese medicine knowledge with modern clinical evidence to deliver safe, effective treatments.</p></div>
        <div className="space-y-16">
          {services.map((service, index) => (
            <div key={service.id} id={service.id} className={`grid lg:grid-cols-2 gap-12 items-center ${index % 2 === 1 ? "lg:flex-row-reverse" : ""}`}>
              <div className={index % 2 === 1 ? "lg:order-2" : ""}><div className="text-primary mb-4">{service.icon}</div><h3 className="text-2xl md:text-3xl font-bold text-primary mb-2">{service.title}</h3><p className="text-accent font-semibold mb-4">{service.subtitle}</p><p className="text-gray-600 mb-6 leading-relaxed">{service.description}</p>
                <ul className="space-y-3 mb-8">{service.features.map((f, i) => (<li key={i} className="flex items-start gap-3"><svg className="w-5 h-5 text-accent mt-0.5 flex-shrink-0" fill="currentColor" viewBox="0 0 20 20"><path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" /></svg><span className="text-gray-700">{f}</span></li>))}</ul>
                <Link href="/acupuncture-marylebone/contact" className="btn-accent">Book This Treatment</Link>
              </div>
              <div className={`bg-gray-50 p-8 lg:p-12 rounded-sm ${index % 2 === 1 ? "lg:order-1" : ""}`}><div className="aspect-video bg-gradient-to-br from-primary to-secondary rounded-sm flex items-center justify-center"><div className="text-white opacity-20 scale-150">{service.icon}</div></div></div>
            </div>
          ))}
        </div>
      </div></section>

      <section className="section-padding bg-gray-50"><div className="container-width"><div className="text-center mb-16"><span className="text-accent font-semibold tracking-wider uppercase text-sm">Your Treatment</span><h2 className="text-3xl md:text-4xl font-bold text-primary mt-4 mb-4">What to Expect</h2><div className="gold-line-center mb-6"></div></div>
        <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8">
          {[{ s: "1", t: "Consultation", d: "A thorough initial consultation covering your health history, lifestyle and treatment goals." }, { s: "2", t: "Diagnosis", d: "Traditional Chinese medicine diagnosis including pulse and tongue assessment." }, { s: "3", t: "Treatment", d: "Gentle, relaxing acupuncture treatment using ultra-fine sterile disposable needles." }, { s: "4", t: "Aftercare", d: "Personalised lifestyle and dietary advice to support your treatment between sessions." }].map((step) => (
            <div key={step.s} className="text-center"><div className="w-16 h-16 bg-primary text-white rounded-full flex items-center justify-center mx-auto mb-4 text-2xl font-bold font-serif">{step.s}</div><h3 className="text-xl font-bold text-primary mb-2">{step.t}</h3><p className="text-gray-600">{step.d}</p></div>
          ))}
        </div>
      </div></section>

      <section className="section-padding bg-primary"><div className="container-width text-center">
        <h2 className="text-3xl md:text-4xl font-bold text-white mb-4">Ready to Start Feeling Better?</h2>
        <p className="text-xl text-gray-200 mb-8 max-w-2xl mx-auto">Book your initial consultation and take the first step towards better health.</p>
        <div className="flex flex-col sm:flex-row justify-center gap-4"><Link href="/acupuncture-marylebone/contact" className="btn-accent">Book Appointment</Link><a href="tel:02079465890" className="btn-outline border-white text-white hover:bg-white hover:text-primary">Call 020 7946 5890</a></div>
      </div></section>
    </>
  );
}
