import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = { title: "About Us | Fulham Yoga Studio", description: "Meet the team at Fulham Yoga Studio. Yoga Alliance registered, 12 qualified instructors, purpose-built studio in SW6. Yoga for every body since 2018.", openGraph: { title: "About Us | Fulham Yoga Studio", description: "Yoga Alliance registered studio in Fulham. Qualified instructors, purpose-built space, all levels welcome." } };

export default function AboutPage() {
  return (
    <>
      <section className="hero-gradient py-20 lg:py-28"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="max-w-3xl"><span className="text-[var(--accent)] font-semibold tracking-wider uppercase text-sm">About Us</span><h1 className="text-4xl md:text-5xl font-bold text-white mt-4 mb-6">Our Story</h1><p className="text-xl text-gray-200 leading-relaxed">A purpose-built yoga studio in the heart of Fulham, created with the belief that yoga should be accessible, inclusive and genuinely transformative.</p></div></div></section>

      <section className="py-16 lg:py-24 bg-white"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="grid lg:grid-cols-2 gap-16 items-center"><div><span className="text-[var(--accent)] font-semibold tracking-wider uppercase text-sm">Our Story</span><h2 className="text-3xl md:text-4xl font-bold text-[var(--primary)] mt-4 mb-4">From a Passion to a Practice</h2><div className="w-16 h-1 bg-[var(--accent)] mb-6"></div><p className="text-lg text-gray-600 mb-6 leading-relaxed">Fulham Yoga Studio was founded in 2018 by a group of friends who shared a simple vision: a studio where everyone feels welcome, regardless of age, ability or experience. We wanted to create a space that felt warm and approachable, not intimidating.</p><p className="text-gray-600 mb-6 leading-relaxed">Today, our team of 12 Yoga Alliance registered instructors teach over 40 classes a week across six distinct styles. From energising Vinyasa Flow to deeply nourishing Yin, from heated sessions to specialist pregnancy classes, there is truly something for every body.</p><p className="text-gray-600 leading-relaxed">Our purpose-built studio on Wandsworth Bridge Road features a heated room, a dedicated Yin/restorative space, full changing facilities with showers, and a relaxation lounge where members gather before and after class. We are proud to be part of the Fulham community and to play a small role in helping our members live healthier, happier lives.</p></div><div className="bg-gray-50 p-8 lg:p-12 rounded-sm"><div className="grid grid-cols-2 gap-8"><div className="text-center p-6 bg-white rounded-sm shadow-sm"><div className="text-3xl md:text-4xl font-bold text-[var(--accent)]">40+</div><p className="text-gray-600 mt-2 font-medium">Weekly Classes</p></div><div className="text-center p-6 bg-white rounded-sm shadow-sm"><div className="text-3xl md:text-4xl font-bold text-[var(--accent)]">12</div><p className="text-gray-600 mt-2 font-medium">Instructors</p></div><div className="text-center p-6 bg-white rounded-sm shadow-sm"><div className="text-3xl md:text-4xl font-bold text-[var(--accent)]">2,500+</div><p className="text-gray-600 mt-2 font-medium">Members</p></div><div className="text-center p-6 bg-white rounded-sm shadow-sm"><div className="text-3xl md:text-4xl font-bold text-[var(--accent)]">4.9★</div><p className="text-gray-600 mt-2 font-medium">Google Rating</p></div></div></div></div></div></section>

      <section className="py-16 lg:py-24 bg-gray-50"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="text-center mb-16"><span className="text-[var(--accent)] font-semibold tracking-wider uppercase text-sm">Our Values</span><h2 className="text-3xl md:text-4xl font-bold text-[var(--primary)] mt-4 mb-4">What We Stand For</h2><div className="w-16 h-1 bg-[var(--accent)] mx-auto mb-6"></div></div><div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">{[{ title: "Inclusivity", desc: "Yoga is for every body. We welcome all ages, abilities and backgrounds. Every class is taught with modifications and progressions so everyone can participate fully." },{ title: "Authenticity", desc: "We honour the traditions and philosophy of yoga while making it relevant and accessible for modern life. Our teaching is grounded, sincere and free of pretension." },{ title: "Community", desc: "Our studio is more than a place to practise. It is a community of like-minded people who support and inspire one another on and off the mat." },{ title: "Excellence", desc: "Every instructor is Yoga Alliance registered with extensive training and continuing professional development. We hold ourselves to the highest standards of teaching." },{ title: "Wellbeing", desc: "We believe in the holistic benefits of yoga — physical, mental and emotional. Our classes are designed to nourish the whole person, not just build flexibility." },{ title: "Sustainability", desc: "We are committed to reducing our environmental impact. Our studio uses eco-friendly materials, sustainable products and we actively minimise waste." }].map((v, i) => (<div key={i} className="bg-white p-8 rounded-sm shadow-sm"><h3 className="text-xl font-bold text-[var(--primary)] mb-3">{v.title}</h3><p className="text-gray-600">{v.desc}</p></div>))}</div></div></section>

      <section className="py-16 lg:py-24 bg-white"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center"><span className="text-[var(--accent)] font-semibold tracking-wider uppercase text-sm">The Studio</span><h2 className="text-3xl md:text-4xl font-bold text-[var(--primary)] mt-4 mb-4">Our Fulham Studio</h2><div className="w-16 h-1 bg-[var(--accent)] mx-auto mb-6"></div><p className="text-lg text-gray-600 max-w-3xl mx-auto mb-8">A purpose-built space on Wandsworth Bridge Road featuring a heated yoga room, a dedicated Yin studio, full changing facilities with showers, and a welcoming relaxation lounge.</p><div className="bg-gradient-to-br from-[var(--primary)] to-[var(--secondary)] p-8 rounded-sm text-white max-w-lg mx-auto"><address className="not-italic text-gray-200 text-lg mb-4">34 Wandsworth Bridge Road<br />Fulham, London SW6 2TH</address><p className="text-gray-300 text-sm">A short walk from Fulham Broadway and Parsons Green stations</p></div></div></section>

      <section className="py-16 lg:py-24 bg-[var(--primary)]"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center"><h2 className="text-3xl md:text-4xl font-bold text-white mb-4">Come and Practise With Us</h2><p className="text-xl text-gray-200 mb-8 max-w-2xl mx-auto">Your first class is free. Book a taster session and experience the Fulham Yoga Studio difference.</p><div className="flex flex-col sm:flex-row justify-center gap-4"><Link href="/yoga-fulham/contact" className="bg-[var(--accent)] text-white px-8 py-4 font-semibold rounded-sm hover:bg-[var(--accent-light)] transition-colors">Book a Free Taster</Link><a href="tel:02079461456" className="border-2 border-white text-white px-8 py-4 font-semibold rounded-sm hover:bg-white hover:text-[var(--primary)] transition-colors">Call 020 7946 1456</a></div></div></section>
    </>
  );
}
