import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Flooring Services | Carpets, LVT, Laminate & Hardwood",
  description: "Complete flooring services in Croydon including carpet fitting, luxury vinyl tiles, laminate, hardwood, commercial flooring and free home estimates.",
  openGraph: { title: "Flooring Services | Croydon Carpet & Flooring", description: "Expert flooring services in Croydon. Carpets, LVT, laminate, hardwood and commercial flooring." },
};

export default function ServicesPage() {
  const services = [
    { id: "carpet-fitting", title: "Carpet Fitting", subtitle: "Warmth, Comfort and Style", description: "From plush bedroom carpets to hardwearing stair runners, we supply and fit carpets from all the leading manufacturers. Our showroom on London Road has hundreds of samples to touch and feel, and our fitters deliver a precision finish with invisible seams and perfectly trimmed edges.", features: ["Twist, loop, saxony, berber and natural fibre carpets", "Stair carpets and runners professionally fitted", "Heavy-duty options for rental properties and high-traffic areas", "Underlay supply including premium brands", "Old carpet uplift and disposal included", "Furniture moving assistance available"], icon: (<svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6" /></svg>) },
    { id: "luxury-vinyl-tiles", title: "Luxury Vinyl Tiles", subtitle: "Premium Design, Practical Performance", description: "Luxury vinyl tiles combine stunning aesthetics with exceptional durability and easy maintenance. We are approved installers of Karndean, Amtico and other premium LVT brands, offering the look of natural wood or stone without the drawbacks. Perfect for kitchens, bathrooms and living spaces.", features: ["Karndean, Amtico, Moduleo and more", "Wood-effect and stone-effect designs", "Waterproof and suitable for kitchens and bathrooms", "Warm underfoot with underfloor heating compatibility", "Click-fit and glue-down options available", "Samples brought to your home for colour matching"], icon: (<svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M4 5a1 1 0 011-1h14a1 1 0 011 1v2a1 1 0 01-1 1H5a1 1 0 01-1-1V5zM4 13a1 1 0 011-1h6a1 1 0 011 1v6a1 1 0 01-1 1H5a1 1 0 01-1-1v-6zM16 13a1 1 0 011-1h2a1 1 0 011 1v6a1 1 0 01-1 1h-2a1 1 0 01-1-1v-6z" /></svg>) },
    { id: "laminate-flooring", title: "Laminate Flooring", subtitle: "Great Looks at a Great Price", description: "Modern laminate flooring offers remarkable realism and durability at a fraction of the cost of real wood. Quick to install and easy to maintain, it is ideal for busy family homes. We stock a wide range of finishes from light oak to rich walnut, all with click-fit installation for a smooth, gap-free result.", features: ["Wide range of wood and stone-effect finishes", "Quick click-fit installation with minimal disruption", "Scratch-resistant and easy to clean", "Suitable for underfloor heating systems", "Moisture-resistant options for kitchens", "Budget-friendly without compromising on style"], icon: (<svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10" /></svg>) },
    { id: "hardwood-floors", title: "Hardwood Floors", subtitle: "Timeless Natural Beauty", description: "Nothing compares to the warmth and character of real wood flooring. We supply and install solid and engineered hardwood in oak, walnut, ash and other species. We also offer sanding, staining and refinishing services for existing wood floors, bringing tired boards back to life.", features: ["Solid and engineered hardwood boards", "Oak, walnut, ash, maple and more", "Lacquered, oiled and brushed finishes", "Floor sanding and refinishing of existing boards", "Herringbone and parquet pattern installation", "Compatible with underfloor heating (engineered)"], icon: (<svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M5 3v4M3 5h4M6 17v4m-2-2h4m5-16l2.286 6.857L21 12l-5.714 2.143L13 21l-2.286-6.857L5 12l5.714-2.143L13 3z" /></svg>) },
    { id: "commercial-flooring", title: "Commercial Flooring", subtitle: "Built to Perform", description: "We provide commercial flooring solutions for offices, retail units, schools, care homes and public buildings. Our range includes contract carpet tiles, safety flooring, vinyl sheet and entrance matting systems. We work outside business hours to minimise disruption to your operations.", features: ["Contract carpet tiles from major manufacturers", "Safety flooring for wet areas and commercial kitchens", "Vinyl sheet flooring for healthcare and education", "Entrance matting and barrier systems", "Out-of-hours installation to minimise disruption", "Maintenance advice and warranty support"], icon: (<svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M19 21V5a2 2 0 00-2-2H7a2 2 0 00-2 2v16m14 0h2m-2 0h-5m-9 0H3m2 0h5M9 7h1m-1 4h1m4-4h1m-1 4h1m-5 10v-5a1 1 0 011-1h2a1 1 0 011 1v5m-4 0h4" /></svg>) },
    { id: "free-home-estimates", title: "Free Home Estimates", subtitle: "No Obligation, No Pressure", description: "Our free home estimate service makes it easy to get started. One of our experienced estimators will visit your home at a time that suits you, measure every room accurately, show you samples in your own lighting and provide a detailed written quote. There is absolutely no obligation to proceed.", features: ["Convenient appointments including evenings", "Accurate laser measuring of all rooms", "Samples shown in your home for perfect colour matching", "Detailed written quote with no hidden costs", "Advice on the best flooring for each room", "Absolutely no obligation or pressure to buy"], icon: (<svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 7h6m0 10v-3m-3 3h.01M9 17h.01M9 14h.01M12 14h.01M15 11h.01M12 11h.01M9 11h.01M7 21h10a2 2 0 002-2V5a2 2 0 00-2-2H7a2 2 0 00-2 2v14a2 2 0 002 2z" /></svg>) },
  ];

  return (
    <>
      <section className="hero-gradient py-20 lg:py-28"><div className="container-width"><div className="max-w-3xl"><span className="text-accent font-semibold tracking-wider uppercase text-sm">Our Services</span><h1 className="text-4xl md:text-5xl font-bold text-white mt-4 mb-6">Flooring Services</h1><p className="text-xl text-gray-200 leading-relaxed">From carpets to hardwood, we supply and fit every type of flooring with expert craftsmanship and honest pricing.</p></div></div></section>

      <section className="section-padding bg-white">
        <div className="container-width">
          <div className="text-center mb-16"><h2 className="text-3xl md:text-4xl font-bold text-primary mb-4">Complete Flooring Solutions</h2><div className="gold-line-center mb-6"></div><p className="text-lg text-gray-600 max-w-3xl mx-auto">With 6 expert fitters and over 15 years in the trade, we have the skills and experience to transform any room in your home or business.</p></div>
          <div className="space-y-16">
            {services.map((service, index) => (
              <div key={service.id} id={service.id} className={`grid lg:grid-cols-2 gap-12 items-center ${index % 2 === 1 ? "lg:flex-row-reverse" : ""}`}>
                <div className={index % 2 === 1 ? "lg:order-2" : ""}><div className="text-primary mb-4">{service.icon}</div><h3 className="text-2xl md:text-3xl font-bold text-primary mb-2">{service.title}</h3><p className="text-accent font-semibold mb-4">{service.subtitle}</p><p className="text-gray-600 mb-6 leading-relaxed">{service.description}</p>
                  <ul className="space-y-3 mb-8">{service.features.map((feature, i) => (<li key={i} className="flex items-start gap-3"><svg className="w-5 h-5 text-accent mt-0.5 flex-shrink-0" fill="currentColor" viewBox="0 0 20 20"><path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" /></svg><span className="text-gray-700">{feature}</span></li>))}</ul>
                  <Link href="/carpet-fitter-croydon/contact" className="btn-accent">Get a Quote</Link>
                </div>
                <div className={`bg-gray-50 p-8 lg:p-12 rounded-sm ${index % 2 === 1 ? "lg:order-1" : ""}`}><div className="aspect-video bg-gradient-to-br from-primary to-secondary rounded-sm flex items-center justify-center"><div className="text-white opacity-20 scale-150">{service.icon}</div></div></div>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section className="section-padding bg-gray-50"><div className="container-width"><div className="text-center mb-16"><span className="text-accent font-semibold tracking-wider uppercase text-sm">Our Process</span><h2 className="text-3xl md:text-4xl font-bold text-primary mt-4 mb-4">How It Works</h2><div className="gold-line-center mb-6"></div></div>
        <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8">
          <div className="text-center"><div className="w-16 h-16 bg-primary text-white rounded-full flex items-center justify-center mx-auto mb-4 text-2xl font-bold font-serif">1</div><h3 className="text-xl font-bold text-primary mb-2">Choose Your Floor</h3><p className="text-gray-600">Visit our showroom or book a home visit to browse samples and find the perfect flooring.</p></div>
          <div className="text-center"><div className="w-16 h-16 bg-primary text-white rounded-full flex items-center justify-center mx-auto mb-4 text-2xl font-bold font-serif">2</div><h3 className="text-xl font-bold text-primary mb-2">Free Estimate</h3><p className="text-gray-600">We measure accurately and provide a detailed written quote with no hidden costs.</p></div>
          <div className="text-center"><div className="w-16 h-16 bg-primary text-white rounded-full flex items-center justify-center mx-auto mb-4 text-2xl font-bold font-serif">3</div><h3 className="text-xl font-bold text-primary mb-2">Expert Fitting</h3><p className="text-gray-600">Our experienced fitters install your flooring at a date that suits you, with minimal disruption.</p></div>
          <div className="text-center"><div className="w-16 h-16 bg-primary text-white rounded-full flex items-center justify-center mx-auto mb-4 text-2xl font-bold font-serif">4</div><h3 className="text-xl font-bold text-primary mb-2">Enjoy</h3><p className="text-gray-600">Walk on your beautiful new floor knowing it has been fitted to the highest standard.</p></div>
        </div>
      </div></section>

      <section className="section-padding bg-primary"><div className="container-width text-center"><h2 className="text-3xl md:text-4xl font-bold text-white mb-4">Ready for New Flooring?</h2><p className="text-xl text-gray-200 mb-8 max-w-2xl mx-auto">Book a free home estimate or visit our Croydon showroom to see our full range.</p>
        <div className="flex flex-col sm:flex-row justify-center gap-4"><Link href="/carpet-fitter-croydon/contact" className="btn-accent">Book Free Estimate</Link><a href="tel:02079461170" className="btn-outline border-white text-white hover:bg-white hover:text-primary">Call 020 7946 1170</a></div>
      </div></section>
    </>
  );
}
