import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Services | Wedding Flowers, Bouquets & Event Styling",
  description: "Full range of floristry services from Chelsea Blooms. Wedding flowers, funeral tributes, luxury bouquets, corporate arrangements, event styling and flower subscriptions.",
  openGraph: { title: "Services | Chelsea Blooms", description: "Luxury floristry services in Chelsea. Weddings, bouquets, corporate flowers and same day delivery." },
};

export default function ServicesPage() {
  const services = [
    { id: "wedding-flowers", title: "Wedding Flowers", subtitle: "Your Dream Day, Beautifully Realised", description: "Your wedding flowers set the tone for your entire day. We work closely with you from the initial consultation through to the day itself, creating bespoke floral designs that perfectly complement your venue, colour palette and personal style.", features: ["Bridal bouquets and bridesmaid posies", "Buttonholes and corsages", "Table centrepieces and top table arrangements", "Ceremony arch and aisle styling", "Venue installation and breakdown", "Pre-wedding consultation and mood boarding"], icon: <svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z" /></svg> },
    { id: "funeral-tributes", title: "Funeral Tributes", subtitle: "Respectful, Heartfelt Tributes", description: "We understand how important funeral flowers are during a difficult time. Our team creates beautiful, respectful tributes with care and sensitivity, working with you or your funeral director to ensure everything is perfect.", features: ["Traditional wreaths and sprays", "Casket arrangements", "Bespoke tribute designs and lettering", "Sympathy bouquets and arrangements", "Church and venue flowers", "Direct delivery to funeral directors"], icon: <svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253" /></svg> },
    { id: "luxury-bouquets", title: "Luxury Bouquets", subtitle: "Hand-Tied with Love", description: "Our signature hand-tied bouquets are made to order using the finest seasonal blooms. From romantic roses to wild meadow styles, each bouquet is a one-off creation designed to delight.", features: ["Made to order, never pre-made", "Premium seasonal flowers", "Choose your colour palette and style", "Gift wrapping and personal message", "Same day delivery across London", "Vase arrangements also available"], icon: <svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M5 3v4M3 5h4M6 17v4m-2-2h4m5-16l2.286 6.857L21 12l-5.714 2.143L13 21l-2.286-6.857L5 12l5.714-2.143L13 3z" /></svg> },
    { id: "corporate-flowers", title: "Corporate Flowers", subtitle: "Fresh Impressions, Every Week", description: "First impressions matter. Our corporate flower service delivers fresh, beautifully designed arrangements to your office, reception or meeting rooms on a regular schedule. Contract pricing available for regular clients.", features: ["Weekly or fortnightly deliveries", "Reception and lobby displays", "Meeting room arrangements", "Contract pricing available", "Seasonal and themed designs", "Setup and maintenance included"], icon: <svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M19 21V5a2 2 0 00-2-2H7a2 2 0 00-2 2v16m14 0h2m-2 0h-5m-9 0H3m2 0h5M9 7h1m-1 4h1m4-4h1m-1 4h1m-5 10v-5a1 1 0 011-1h2a1 1 0 011 1v5m-4 0h4" /></svg> },
    { id: "event-styling", title: "Event Styling", subtitle: "From Concept to Installation", description: "We provide complete floral styling for events of all sizes. Product launches, dinner parties, charity galas, exhibitions and more. Our team handles everything from concept development to on-site installation and breakdown.", features: ["Concept development and mood boards", "Large-scale floral installations", "Table styling and centrepieces", "Entrance and feature displays", "On-site installation team", "Post-event breakdown and removal"], icon: <svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M21 15.546c-.523 0-1.046.151-1.5.454a2.704 2.704 0 01-3 0 2.704 2.704 0 00-3 0 2.704 2.704 0 01-3 0 2.704 2.704 0 00-3 0 2.704 2.704 0 01-3 0A1.75 1.75 0 013 15.546" /></svg> },
    { id: "flower-subscriptions", title: "Flower Subscriptions", subtitle: "Fresh Blooms on Your Schedule", description: "Enjoy fresh flowers at home or in the office without the hassle. Choose your frequency, style preference and budget, and we will deliver a beautiful seasonal arrangement straight to your door.", features: ["Weekly, fortnightly or monthly options", "Seasonal flower selection", "Choose your style: classic, wild or modern", "Free delivery included", "Pause or cancel any time", "Gift subscriptions available"], icon: <svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M20 7l-8-4-8 4m16 0l-8 4m8-4v10l-8 4m0-10L4 7m8 4v10M4 7v10l8 4" /></svg> },
  ];

  return (
    <>
      <section className="hero-gradient py-20 lg:py-28"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="max-w-3xl"><span className="text-[var(--accent)] font-semibold tracking-wider uppercase text-sm">Our Services</span><h1 className="text-4xl md:text-5xl font-bold text-white mt-4 mb-6">Floristry Services</h1><p className="text-xl text-gray-200 leading-relaxed">From intimate bouquets to grand wedding installations, every arrangement is designed with artistry, sourced sustainably and delivered with care.</p></div></div></section>

      <section className="py-16 lg:py-24 bg-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16"><h2 className="text-3xl md:text-4xl font-bold text-[var(--primary)] mb-4">What We Create</h2><div className="w-16 h-1 bg-[var(--accent)] mx-auto mb-6"></div><p className="text-lg text-gray-600 max-w-3xl mx-auto">Every arrangement is made to order using the finest seasonal blooms. We never use pre-made bouquets &mdash; everything is crafted fresh in our Chelsea studio.</p></div>
          <div className="space-y-16">
            {services.map((service, index) => (
              <div key={service.id} id={service.id} className={`grid lg:grid-cols-2 gap-12 items-center ${index % 2 === 1 ? "lg:flex-row-reverse" : ""}`}>
                <div className={index % 2 === 1 ? "lg:order-2" : ""}><div className="text-[var(--primary)] mb-4">{service.icon}</div><h3 className="text-2xl md:text-3xl font-bold text-[var(--primary)] mb-2">{service.title}</h3><p className="text-[var(--accent)] font-semibold mb-4">{service.subtitle}</p><p className="text-gray-600 mb-6 leading-relaxed">{service.description}</p><ul className="space-y-3 mb-8">{service.features.map((f, i) => (<li key={i} className="flex items-start gap-3"><svg className="w-5 h-5 text-[var(--accent)] mt-0.5 flex-shrink-0" fill="currentColor" viewBox="0 0 20 20"><path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" /></svg><span className="text-gray-700">{f}</span></li>))}</ul><Link href="/florist-chelsea/contact" className="bg-[var(--accent)] text-white px-6 py-3 font-semibold rounded-sm hover:bg-[var(--accent-light)] transition-colors inline-block">Enquire Now</Link></div>
                <div className={`bg-gray-50 p-8 lg:p-12 rounded-sm ${index % 2 === 1 ? "lg:order-1" : ""}`}><div className="aspect-video bg-gradient-to-br from-[var(--primary)] to-[var(--secondary)] rounded-sm flex items-center justify-center"><div className="text-white opacity-20 scale-150">{service.icon}</div></div></div>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section className="py-16 lg:py-24 bg-gray-50"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="text-center mb-16"><span className="text-[var(--accent)] font-semibold tracking-wider uppercase text-sm">How It Works</span><h2 className="text-3xl md:text-4xl font-bold text-[var(--primary)] mt-4 mb-4">Our Process</h2><div className="w-16 h-1 bg-[var(--accent)] mx-auto mb-6"></div></div><div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8">
        <div className="text-center"><div className="w-16 h-16 bg-[var(--primary)] text-white rounded-full flex items-center justify-center mx-auto mb-4 text-2xl font-bold">1</div><h3 className="text-xl font-bold text-[var(--primary)] mb-2">Consultation</h3><p className="text-gray-600">We discuss your vision, occasion and preferences to understand exactly what you need.</p></div>
        <div className="text-center"><div className="w-16 h-16 bg-[var(--primary)] text-white rounded-full flex items-center justify-center mx-auto mb-4 text-2xl font-bold">2</div><h3 className="text-xl font-bold text-[var(--primary)] mb-2">Design</h3><p className="text-gray-600">Our designers create a bespoke concept using the finest seasonal flowers available.</p></div>
        <div className="text-center"><div className="w-16 h-16 bg-[var(--primary)] text-white rounded-full flex items-center justify-center mx-auto mb-4 text-2xl font-bold">3</div><h3 className="text-xl font-bold text-[var(--primary)] mb-2">Create</h3><p className="text-gray-600">Each arrangement is hand-crafted in our Chelsea studio with care and artistry.</p></div>
        <div className="text-center"><div className="w-16 h-16 bg-[var(--primary)] text-white rounded-full flex items-center justify-center mx-auto mb-4 text-2xl font-bold">4</div><h3 className="text-xl font-bold text-[var(--primary)] mb-2">Deliver</h3><p className="text-gray-600">We deliver across London with same day options available. Installation included for events.</p></div>
      </div></div></section>

      <section className="py-16 lg:py-24 bg-[var(--primary)]"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center"><h2 className="text-3xl md:text-4xl font-bold text-white mb-4">Ready to Order?</h2><p className="text-xl text-gray-200 mb-8 max-w-2xl mx-auto">Get in touch to discuss your requirements or place an order for same day delivery.</p><div className="flex flex-col sm:flex-row justify-center gap-4"><Link href="/florist-chelsea/contact" className="bg-[var(--accent)] text-white px-8 py-4 font-semibold rounded-sm hover:bg-[var(--accent-light)] transition-colors">Order Flowers</Link><a href="tel:02079469012" className="border-2 border-white text-white px-8 py-4 font-semibold rounded-sm hover:bg-white hover:text-[var(--primary)] transition-colors">Call 020 7946 9012</a></div></div></section>
    </>
  );
}
