import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Veterinary Services | Consultations, Surgery & Dental Care",
  description: "Comprehensive veterinary services in Hampstead, NW3. Consultations, vaccinations, surgery, dental care, microchipping and pet health plans from RCVS registered vets.",
  openGraph: { title: "Veterinary Services | Hampstead Veterinary Clinic", description: "RCVS registered veterinary services in Hampstead including consultations, surgery and dental care." },
};

export default function ServicesPage() {
  const services = [
    { id: "consultations", title: "Consultations & Check-ups", subtitle: "Thorough, Compassionate Examinations", description: "Every consultation begins with a comprehensive nose-to-tail examination. Our vets take the time to listen to your concerns, discuss your pet's lifestyle and provide a thorough assessment. We believe prevention is better than cure, which is why we recommend annual wellness checks for all pets.", features: ["Full physical examination and health assessment", "Weight management and nutritional advice", "Senior pet wellness screening", "Puppy and kitten health checks", "Behavioural consultations", "Second opinion consultations"], icon: <svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-3 7h3m-3 4h3m-6-4h.01M9 16h.01" /></svg> },
    { id: "vaccinations", title: "Vaccinations", subtitle: "Protection Against Preventable Disease", description: "We provide tailored vaccination programmes for dogs, cats and rabbits based on their individual risk factors and lifestyle. Our vets will advise on core and non-core vaccines to ensure your pet is protected without unnecessary treatments.", features: ["Core vaccinations for dogs (Distemper, Parvovirus, Leptospirosis)", "Core vaccinations for cats (Panleucopenia, Calicivirus, Herpesvirus)", "Rabbit vaccinations (Myxomatosis, RVHD1 & RVHD2)", "Kennel cough vaccination", "Titre testing for dogs as an alternative to annual boosters", "Puppy and kitten primary vaccination courses"], icon: <svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" /></svg> },
    { id: "surgery", title: "Surgery", subtitle: "Modern Theatre, Experienced Surgeons", description: "Our fully equipped surgical theatre allows us to perform a wide range of routine and complex procedures. Every surgical patient benefits from pre-operative blood testing, modern anaesthetic protocols, dedicated monitoring and attentive post-operative care.", features: ["Neutering (spaying and castration)", "Soft tissue surgery (lump removals, wound repair)", "Orthopaedic procedures", "Laparoscopic (keyhole) surgery", "Emergency surgical intervention", "Full pre-and post-operative care"], icon: <svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z" /></svg> },
    { id: "dental-care", title: "Dental Care", subtitle: "Healthy Mouth, Healthy Pet", description: "Dental disease is one of the most common health problems in pets, yet it is often overlooked. Our dental service includes full oral examinations, professional scaling and polishing under general anaesthetic, extractions when necessary and advice on home dental care.", features: ["Dental health assessments during consultations", "Professional scaling and polishing", "Dental radiography (X-rays)", "Tooth extractions when required", "Home dental care advice and products", "Dental awareness programmes"], icon: <svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M14.828 14.828a4 4 0 01-5.656 0M9 10h.01M15 10h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" /></svg> },
    { id: "microchipping", title: "Microchipping", subtitle: "Permanent, Reliable Identification", description: "Microchipping is a quick, safe procedure that provides permanent identification for your pet. It is a legal requirement for all dogs in England and is strongly recommended for cats and rabbits. The tiny chip is implanted under the skin and can be scanned by any vet or rescue centre.", features: ["Quick, virtually painless implantation", "Legal requirement for all dogs in England", "Compliant with UK pet travel regulations", "Registered on national databases", "Can be done during a routine consultation", "Lifetime identification and peace of mind"], icon: <svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M7 7h.01M7 3h5c.512 0 1.024.195 1.414.586l7 7a2 2 0 010 2.828l-7 7a2 2 0 01-2.828 0l-7-7A1.994 1.994 0 013 12V7a4 4 0 014-4z" /></svg> },
    { id: "health-plans", title: "Pet Health Plans", subtitle: "Affordable Preventive Care", description: "Our pet health plans spread the cost of essential preventive care into manageable monthly payments. Members save up to 30% compared to paying individually for vaccinations, flea and worm treatments, health checks and more. Plans are available for dogs, cats and rabbits.", features: ["Annual vaccination and booster included", "Year-round flea and worm treatment", "Annual health check and dental assessment", "Microchipping included for new puppies and kittens", "Discounts on additional treatments and products", "No lock-in contracts - cancel anytime"], icon: <svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1M21 12a9 9 0 11-18 0 9 9 0 0118 0z" /></svg> },
  ];

  return (
    <>
      <section className="hero-gradient py-20 lg:py-28"><div className="container-width"><div className="max-w-3xl"><span className="text-accent font-semibold tracking-wider uppercase text-sm">Our Services</span><h1 className="text-4xl md:text-5xl font-bold text-white mt-4 mb-6">Comprehensive Veterinary Care</h1><p className="text-xl text-gray-200 leading-relaxed">From routine wellness checks to complex surgery, our RCVS registered team provides the full range of veterinary services your pet needs.</p></div></div></section>

      <section className="section-padding bg-white"><div className="container-width"><div className="text-center mb-16"><h2 className="text-3xl md:text-4xl font-bold text-primary mb-4">Expert Veterinary Services</h2><div className="gold-line-center mb-6"></div><p className="text-lg text-gray-600 max-w-3xl mx-auto">Our modern clinic is equipped with digital X-ray, ultrasound, in-house laboratory and a full surgical theatre. Every pet receives the highest standard of care.</p></div>
        <div className="space-y-16">{services.map((service, index) => (<div key={service.id} id={service.id} className={`grid lg:grid-cols-2 gap-12 items-center ${index % 2 === 1 ? "lg:flex-row-reverse" : ""}`}><div className={index % 2 === 1 ? "lg:order-2" : ""}><div className="text-primary mb-4">{service.icon}</div><h3 className="text-2xl md:text-3xl font-bold text-primary mb-2">{service.title}</h3><p className="text-accent font-semibold mb-4">{service.subtitle}</p><p className="text-gray-600 mb-6 leading-relaxed">{service.description}</p><ul className="space-y-3 mb-8">{service.features.map((f, i) => (<li key={i} className="flex items-start gap-3"><svg className="w-5 h-5 text-accent mt-0.5 flex-shrink-0" fill="currentColor" viewBox="0 0 20 20"><path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" /></svg><span className="text-gray-700">{f}</span></li>))}</ul><Link href="/vet-hampstead/contact" className="btn-accent">Book Appointment</Link></div><div className={`bg-gray-50 p-8 lg:p-12 rounded-sm ${index % 2 === 1 ? "lg:order-1" : ""}`}><div className="aspect-video bg-gradient-to-br from-primary to-secondary rounded-sm flex items-center justify-center"><div className="text-white opacity-20 scale-150">{service.icon}</div></div></div></div>))}</div>
      </div></section>

      <section className="section-padding bg-gray-50"><div className="container-width"><div className="text-center mb-16"><span className="text-accent font-semibold tracking-wider uppercase text-sm">Our Process</span><h2 className="text-3xl md:text-4xl font-bold text-primary mt-4 mb-4">Your Pet&apos;s Visit</h2><div className="gold-line-center mb-6"></div></div><div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8"><div className="text-center"><div className="w-16 h-16 bg-primary text-white rounded-full flex items-center justify-center mx-auto mb-4 text-2xl font-bold">1</div><h3 className="text-xl font-bold text-primary mb-2">Book Online</h3><p className="text-gray-600">Book your appointment online or by phone. We offer same-day appointments for urgent cases.</p></div><div className="text-center"><div className="w-16 h-16 bg-primary text-white rounded-full flex items-center justify-center mx-auto mb-4 text-2xl font-bold">2</div><h3 className="text-xl font-bold text-primary mb-2">Warm Welcome</h3><p className="text-gray-600">Our friendly team greets you and your pet. Cats enjoy our separate waiting area for a stress-free visit.</p></div><div className="text-center"><div className="w-16 h-16 bg-primary text-white rounded-full flex items-center justify-center mx-auto mb-4 text-2xl font-bold">3</div><h3 className="text-xl font-bold text-primary mb-2">Thorough Care</h3><p className="text-gray-600">Your vet conducts a full examination, discusses findings and recommends the best course of action.</p></div><div className="text-center"><div className="w-16 h-16 bg-primary text-white rounded-full flex items-center justify-center mx-auto mb-4 text-2xl font-bold">4</div><h3 className="text-xl font-bold text-primary mb-2">Follow-Up</h3><p className="text-gray-600">We provide clear aftercare instructions and follow up to ensure your pet is recovering well.</p></div></div></div></section>

      <section className="section-padding bg-primary"><div className="container-width text-center"><h2 className="text-3xl md:text-4xl font-bold text-white mb-4">Ready to Book?</h2><p className="text-xl text-gray-200 mb-8 max-w-2xl mx-auto">Book an appointment online or call us. Same-day appointments available for urgent cases.</p><div className="flex flex-col sm:flex-row justify-center gap-4"><Link href="/vet-hampstead/contact" className="btn-accent">Book Appointment</Link><a href="tel:02079465670" className="btn-outline border-white text-white hover:bg-white hover:text-primary">Call 020 7946 5670</a></div></div></section>

      <section className="py-8 bg-gray-100"><div className="container-width"><div className="fca-notice"><p><strong>Professional Standards:</strong> Hampstead Veterinary Clinic is registered with the Royal College of Veterinary Surgeons (RCVS). All our vets and nurses are RCVS registered professionals committed to the highest standards of animal care.</p></div></div></section>
    </>
  );
}
