import Link from "next/link";

export default function Home() {
  return (
    <>
      <section className="hero-gradient min-h-[90vh] flex items-center relative overflow-hidden">
        <div className="absolute inset-0 opacity-5"><div className="absolute inset-0" style={{ backgroundImage: `url("data:image/svg+xml,%3Csvg width='60' height='60' viewBox='0 0 60 60' xmlns='http://www.w3.org/2000/svg'%3E%3Cg fill='none' fill-rule='evenodd'%3E%3Cg fill='%23ffffff' fill-opacity='1'%3E%3Cpath d='M36 34v-4h-2v4h-4v2h4v4h2v-4h4v-2h-4zm0-30V0h-2v4h-4v2h4v4h2V6h4V4h-4zM6 34v-4H4v4H0v2h4v4h2v-4h4v-2H6zM6 4V0H4v4H0v2h4v4h2V6h4V4H6z'/%3E%3C/g%3E%3C/g%3E%3C/svg%3E")` }} /></div>
        <div className="container-width relative z-10"><div className="max-w-4xl">
          <div className="flex items-center gap-3 mb-6"><div className="w-12 h-px bg-accent"></div><span className="text-accent font-semibold tracking-wider uppercase text-sm">Hampstead&apos;s Trusted Veterinary Clinic</span></div>
          <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold text-white mb-6 leading-tight">Compassionate Care,{" "}<span className="text-gold-gradient">Healthy Pets</span></h1>
          <p className="text-xl md:text-2xl text-gray-200 mb-8 leading-relaxed max-w-3xl">Hampstead Veterinary Clinic provides exceptional care for dogs, cats, rabbits and small animals. RCVS registered, Cat Friendly accredited and open seven days a week with 24/7 emergency cover.</p>
          <div className="flex flex-col sm:flex-row gap-4 mb-12"><Link href="/vet-hampstead/contact" className="btn-accent text-lg">Book Appointment</Link><Link href="/vet-hampstead/services" className="btn-outline border-white text-white hover:bg-white hover:text-primary text-lg">Our Services</Link></div>
          <div className="flex flex-wrap items-center gap-8 text-white/80">
            <div className="flex items-center gap-2"><svg className="w-5 h-5 text-accent" fill="currentColor" viewBox="0 0 20 20"><path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" /></svg><span>RCVS Registered</span></div>
            <div className="flex items-center gap-2"><svg className="w-5 h-5 text-accent" fill="currentColor" viewBox="0 0 20 20"><path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" /></svg><span>24/7 Emergency</span></div>
            <div className="flex items-center gap-2"><svg className="w-5 h-5 text-accent" fill="currentColor" viewBox="0 0 20 20"><path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" /></svg><span>Cat Friendly Clinic</span></div>
          </div>
        </div></div>
        <div className="absolute bottom-0 right-0 w-1/3 h-full opacity-10"><svg viewBox="0 0 400 400" className="w-full h-full"><circle cx="200" cy="200" r="180" stroke="#40916c" strokeWidth="2" fill="none" /><circle cx="200" cy="200" r="140" stroke="#40916c" strokeWidth="1" fill="none" /><circle cx="200" cy="200" r="100" stroke="#40916c" strokeWidth="0.5" fill="none" /></svg></div>
      </section>

      <section className="section-padding bg-gray-50"><div className="container-width">
        <div className="text-center mb-16"><span className="text-accent font-semibold tracking-wider uppercase text-sm">Our Services</span><h2 className="text-3xl md:text-4xl font-bold text-primary mt-4 mb-4">Complete Veterinary Care</h2><div className="gold-line-center mb-6"></div><p className="text-lg text-gray-600 max-w-2xl mx-auto">From routine check-ups and vaccinations to advanced surgery and emergency care, we provide everything your pet needs under one roof.</p></div>
        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
          <div className="card-premium p-8"><div className="service-icon"><svg className="w-8 h-8" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-3 7h3m-3 4h3m-6-4h.01M9 16h.01" /></svg></div><h3 className="text-xl font-bold text-primary mb-3">Consultations &amp; Check-ups</h3><p className="text-gray-600 mb-4">Thorough health examinations and wellness checks to catch problems early and keep your pet in peak condition year-round.</p><Link href="/vet-hampstead/services" className="text-accent font-semibold inline-flex items-center gap-2">Learn More <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" /></svg></Link></div>
          <div className="card-premium p-8"><div className="service-icon"><svg className="w-8 h-8" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" /></svg></div><h3 className="text-xl font-bold text-primary mb-3">Vaccinations</h3><p className="text-gray-600 mb-4">Core and lifestyle vaccinations for dogs, cats and rabbits. Tailored vaccination schedules to protect your pet against preventable diseases.</p><Link href="/vet-hampstead/services" className="text-accent font-semibold inline-flex items-center gap-2">Learn More <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" /></svg></Link></div>
          <div className="card-premium p-8"><div className="service-icon"><svg className="w-8 h-8" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z" /></svg></div><h3 className="text-xl font-bold text-primary mb-3">Surgery</h3><p className="text-gray-600 mb-4">From routine neutering to complex soft tissue and orthopaedic procedures, performed in our modern surgical theatre with full anaesthetic monitoring.</p><Link href="/vet-hampstead/services" className="text-accent font-semibold inline-flex items-center gap-2">Learn More <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" /></svg></Link></div>
          <div className="card-premium p-8"><div className="service-icon"><svg className="w-8 h-8" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M14.828 14.828a4 4 0 01-5.656 0M9 10h.01M15 10h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" /></svg></div><h3 className="text-xl font-bold text-primary mb-3">Dental Care</h3><p className="text-gray-600 mb-4">Professional dental scaling, polishing, extractions and oral health assessments. Good dental health is essential for your pet&apos;s overall wellbeing.</p><Link href="/vet-hampstead/services" className="text-accent font-semibold inline-flex items-center gap-2">Learn More <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" /></svg></Link></div>
          <div className="card-premium p-8"><div className="service-icon"><svg className="w-8 h-8" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M7 7h.01M7 3h5c.512 0 1.024.195 1.414.586l7 7a2 2 0 010 2.828l-7 7a2 2 0 01-2.828 0l-7-7A1.994 1.994 0 013 12V7a4 4 0 014-4z" /></svg></div><h3 className="text-xl font-bold text-primary mb-3">Microchipping</h3><p className="text-gray-600 mb-4">Quick, safe permanent identification for your pet. A legal requirement for dogs in England and highly recommended for cats and rabbits.</p><Link href="/vet-hampstead/services" className="text-accent font-semibold inline-flex items-center gap-2">Learn More <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" /></svg></Link></div>
          <div className="card-premium p-8"><div className="service-icon"><svg className="w-8 h-8" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1M21 12a9 9 0 11-18 0 9 9 0 0118 0z" /></svg></div><h3 className="text-xl font-bold text-primary mb-3">Pet Health Plans</h3><p className="text-gray-600 mb-4">Affordable monthly plans spreading the cost of vaccinations, flea and worm treatments, health checks and more. Save up to 30% on preventive care.</p><Link href="/vet-hampstead/services" className="text-accent font-semibold inline-flex items-center gap-2">Learn More <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" /></svg></Link></div>
        </div>
        <div className="text-center mt-12"><Link href="/vet-hampstead/services" className="btn-primary">View All Services</Link></div>
      </div></section>

      <section className="section-padding bg-white"><div className="container-width"><div className="grid lg:grid-cols-2 gap-16 items-center">
        <div>
          <span className="text-accent font-semibold tracking-wider uppercase text-sm">Why Hampstead Vet</span>
          <h2 className="text-3xl md:text-4xl font-bold text-primary mt-4 mb-4">Where Pets Come First</h2><div className="gold-line mb-6"></div>
          <p className="text-lg text-gray-600 mb-8">Our team of experienced veterinary surgeons and nurses is passionate about animal welfare. We treat every pet as if they were our own, providing gentle, thorough care in a calm, welcoming environment.</p>
          <div className="space-y-6">
            <div className="flex gap-4"><div className="w-12 h-12 bg-accent/10 rounded-full flex items-center justify-center flex-shrink-0"><svg className="w-6 h-6 text-accent" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" /></svg></div><div><h3 className="text-lg font-bold text-primary mb-1">RCVS Registered</h3><p className="text-gray-600">Registered with the Royal College of Veterinary Surgeons, meeting the highest standards of veterinary practice and professional conduct.</p></div></div>
            <div className="flex gap-4"><div className="w-12 h-12 bg-accent/10 rounded-full flex items-center justify-center flex-shrink-0"><svg className="w-6 h-6 text-accent" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" /></svg></div><div><h3 className="text-lg font-bold text-primary mb-1">24/7 Emergency Care</h3><p className="text-gray-600">Accidents and emergencies do not keep office hours. Our emergency line is available around the clock for urgent veterinary situations.</p></div></div>
            <div className="flex gap-4"><div className="w-12 h-12 bg-accent/10 rounded-full flex items-center justify-center flex-shrink-0"><svg className="w-6 h-6 text-accent" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z" /></svg></div><div><h3 className="text-lg font-bold text-primary mb-1">Cat Friendly Clinic</h3><p className="text-gray-600">ISFM Cat Friendly accredited with separate cat waiting areas and consultation rooms to minimise feline stress during visits.</p></div></div>
          </div>
        </div>
        <div className="bg-gray-50 p-8 lg:p-12 rounded-sm"><div className="grid grid-cols-2 gap-8">
          <div className="text-center"><div className="stat-number">10+</div><p className="text-gray-600 mt-2">Years of Care</p></div>
          <div className="text-center"><div className="stat-number">8,000+</div><p className="text-gray-600 mt-2">Registered Pets</p></div>
          <div className="text-center"><div className="stat-number">7</div><p className="text-gray-600 mt-2">Days a Week</p></div>
          <div className="text-center"><div className="stat-number">4.9/5</div><p className="text-gray-600 mt-2">Google Rating</p></div>
        </div></div>
      </div></div></section>

      <section className="section-padding bg-primary"><div className="container-width">
        <div className="text-center mb-16"><span className="text-accent font-semibold tracking-wider uppercase text-sm">Client Testimonials</span><h2 className="text-3xl md:text-4xl font-bold text-white mt-4 mb-4">What Pet Owners Say</h2><div className="gold-line-center mb-6"></div></div>
        <div className="grid md:grid-cols-3 gap-8">
          <div className="testimonial-card"><p className="text-gray-600 mb-6 italic">&quot;The team at Hampstead Vet are incredible. They looked after our Labrador through a complex surgery and kept us informed and reassured throughout. Truly outstanding care.&quot;</p><div className="flex items-center gap-3"><div className="w-12 h-12 bg-primary/10 rounded-full flex items-center justify-center"><span className="text-primary font-bold">CH</span></div><div><p className="font-semibold text-primary">Caroline H.</p><p className="text-sm text-gray-500">Dog Owner, Hampstead</p></div></div></div>
          <div className="testimonial-card"><p className="text-gray-600 mb-6 italic">&quot;Our cat absolutely hates the vet, but the Cat Friendly rooms here make such a difference. The staff are gentle, patient and genuinely care about every animal they see.&quot;</p><div className="flex items-center gap-3"><div className="w-12 h-12 bg-primary/10 rounded-full flex items-center justify-center"><span className="text-primary font-bold">TW</span></div><div><p className="font-semibold text-primary">Tom W.</p><p className="text-sm text-gray-500">Cat Owner, Belsize Park</p></div></div></div>
          <div className="testimonial-card"><p className="text-gray-600 mb-6 italic">&quot;The pet health plan saves us a fortune on vaccinations and flea treatments. Plus the annual check-up caught a dental issue early. Worth every penny of the monthly fee.&quot;</p><div className="flex items-center gap-3"><div className="w-12 h-12 bg-primary/10 rounded-full flex items-center justify-center"><span className="text-primary font-bold">NB</span></div><div><p className="font-semibold text-primary">Nina B.</p><p className="text-sm text-gray-500">Pet Owner, Swiss Cottage</p></div></div></div>
        </div>
      </div></section>

      <section className="section-padding bg-gray-50"><div className="container-width"><div className="bg-white rounded-sm shadow-2xl p-8 lg:p-16 text-center border-t-4 border-accent"><h2 className="text-3xl md:text-4xl font-bold text-primary mb-4">Book Your Pet&apos;s Appointment</h2><p className="text-lg text-gray-600 mb-8 max-w-2xl mx-auto">Whether it&apos;s a routine check-up, vaccinations or a health concern, our friendly team is here to help. Book online or call us today.</p><div className="flex flex-col sm:flex-row justify-center gap-4"><Link href="/vet-hampstead/contact" className="btn-accent">Book Appointment</Link><a href="tel:02079465670" className="btn-outline">Call 020 7946 5670</a></div></div></div></section>

      <section className="py-8 bg-gray-100"><div className="container-width"><div className="fca-notice"><p><strong>Professional Standards:</strong> Hampstead Veterinary Clinic is registered with the Royal College of Veterinary Surgeons (RCVS). All our veterinary surgeons and nurses are RCVS registered professionals. We are ISFM Cat Friendly accredited.</p></div></div></section>
    </>
  );
}
