import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Services | Bespoke Rings, Diamonds, Repair & Valuations",
  description: "Bespoke engagement rings, wedding bands, diamond sourcing, jewellery repair, remodelling and valuations at Hatton Garden Fine Jewellers.",
  openGraph: { title: "Services | Hatton Garden Fine Jewellers", description: "Bespoke jewellery, diamond sourcing, repair and valuations in Hatton Garden." },
};

export default function ServicesPage() {
  const services = [
    { id: "engagement-rings", title: "Bespoke Engagement Rings", subtitle: "As Unique as Your Love Story", description: "Every engagement ring we create is entirely bespoke — designed from scratch to reflect your personal story, style and budget. Our process begins with a relaxed consultation where we listen to your vision, then our designers create detailed sketches and 3D renders. Once you are happy, our master craftspeople bring your ring to life using hand-selected diamonds and precious metals.", features: ["Complimentary design consultation at our Hatton Garden workshop", "Detailed sketches and 3D renders before any crafting begins", "GIA-certified diamonds hand-selected to your specifications", "Choice of platinum, white gold, yellow gold or rose gold", "Typical turnaround of 4-6 weeks from approval to completion", "Lifetime warranty on all bespoke engagement rings"], icon: (<svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M5 3v4M3 5h4M6 17v4m-2-2h4m5-16l2.286 6.857L21 12l-5.714 2.143L13 21l-2.286-6.857L5 12l5.714-2.143L13 3z" /></svg>) },
    { id: "wedding-bands", title: "Wedding Bands", subtitle: "Symbols of Forever", description: "Our wedding bands are handcrafted in our Hatton Garden workshop using traditional techniques refined over three generations. Whether you prefer a classic court profile, a modern flat band, or something completely unique, we create bands that are comfortable, durable and beautiful. Matching sets, engraving and bespoke finishes are all available.", features: ["Handcrafted in platinum, 18ct gold or palladium", "Classic, contemporary and bespoke designs available", "Matching his and hers or his and his sets", "Personal engraving: names, dates or meaningful symbols", "Comfort-fit profiles for all-day wearability", "Try before you buy with our sample ring collection"], icon: (<svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z" /></svg>) },
    { id: "diamond-sourcing", title: "Diamond Sourcing", subtitle: "Ethical Brilliance, Expert Selection", description: "Our GIA-certified gemologists source diamonds directly from the world&apos;s most reputable cutters and dealers. We hand-select each stone based on the four Cs — cut, colour, clarity and carat — ensuring you receive exceptional quality and value. All our diamonds are ethically sourced and come with full certification.", features: ["GIA-certified diamonds with full documentation", "Ethically sourced, conflict-free stones guaranteed", "Expert guidance on the four Cs to match your budget", "Access to rare and exceptional stones through our network", "Comparison viewing of multiple diamonds before purchase", "Lab-grown diamond options also available"], icon: (<svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" /></svg>) },
    { id: "jewellery-repair", title: "Jewellery Repair", subtitle: "Restoring What Matters", description: "From ring resizing and stone replacement to clasp repair and full restoration, our workshop handles all jewellery repairs with the care and precision you would expect from a Hatton Garden jeweller. We treat every piece as though it were our own, understanding the sentimental value that often far exceeds monetary worth.", features: ["Ring resizing, reshaping and reinforcing", "Stone replacement and re-setting", "Chain and clasp repair for necklaces and bracelets", "Rhodium plating and polishing to restore shine", "Pearl restringing and repairing", "Most repairs completed within 5-7 working days"], icon: (<svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z" /><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" /></svg>) },
    { id: "remodelling", title: "Remodelling & Redesign", subtitle: "New Life for Treasured Pieces", description: "Do you have inherited jewellery sitting unworn in a drawer? Our remodelling service transforms outdated or sentimental pieces into stunning contemporary designs. We can incorporate existing stones and metals into entirely new creations, honouring the original piece while giving it fresh purpose and beauty.", features: ["Free consultation to discuss design possibilities", "Existing stones and metals incorporated into new designs", "Detailed design sketches before any work begins", "Sympathetic approach to sentimental family pieces", "Mix and combine multiple pieces into one new creation", "Full before and after documentation provided"], icon: (<svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" /></svg>) },
    { id: "valuations", title: "Valuations", subtitle: "Professional, Certified, Trusted", description: "Our GIA-certified gemologists provide detailed, professional valuations for insurance, probate, resale and family division purposes. Each valuation includes a comprehensive written report with photographs, detailed descriptions and current market values. We are trusted by solicitors, insurers and private clients across London.", features: ["Insurance valuations accepted by all major insurers", "Probate valuations for estate administration", "Resale valuations and purchasing advice", "Detailed written reports with photographs", "Conducted by GIA-certified gemologists", "While-you-wait service available for single items"], icon: (<svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>) },
  ];

  return (
    <>
      <section className="hero-gradient py-20 lg:py-28"><div className="container-width"><div className="max-w-3xl"><span className="text-accent font-semibold tracking-wider uppercase text-sm">Our Services</span><h1 className="text-4xl md:text-5xl font-bold text-white mt-4 mb-6">Expert Jewellery Services</h1><p className="text-xl text-gray-200 leading-relaxed">From bespoke commissions to expert repairs, our GIA-certified team brings three generations of Hatton Garden expertise to every piece.</p></div></div></section>

      <section className="section-padding bg-white"><div className="container-width"><div className="text-center mb-16"><h2 className="text-3xl md:text-4xl font-bold text-primary mb-4">Craftsmanship You Can Trust</h2><div className="gold-line-center mb-6"></div><p className="text-lg text-gray-600 max-w-3xl mx-auto">Every service is delivered with the care, expertise and personal attention that has defined our family business for three generations.</p></div>
        <div className="space-y-16">{services.map((service, index) => (
          <div key={service.id} id={service.id} className={`grid lg:grid-cols-2 gap-12 items-center ${index % 2 === 1 ? "lg:flex-row-reverse" : ""}`}>
            <div className={index % 2 === 1 ? "lg:order-2" : ""}><div className="text-primary mb-4">{service.icon}</div><h3 className="text-2xl md:text-3xl font-bold text-primary mb-2">{service.title}</h3><p className="text-accent font-semibold mb-4">{service.subtitle}</p><p className="text-gray-600 mb-6 leading-relaxed">{service.description}</p><ul className="space-y-3 mb-8">{service.features.map((f, i) => (<li key={i} className="flex items-start gap-3"><svg className="w-5 h-5 text-accent mt-0.5 flex-shrink-0" fill="currentColor" viewBox="0 0 20 20"><path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" /></svg><span className="text-gray-700">{f}</span></li>))}</ul><Link href="/jeweller-hatton-garden/contact" className="btn-accent">Book Consultation</Link></div>
            <div className={`bg-gray-50 p-8 lg:p-12 rounded-sm ${index % 2 === 1 ? "lg:order-1" : ""}`}><div className="aspect-video bg-gradient-to-br from-primary to-secondary rounded-sm flex items-center justify-center"><div className="text-white opacity-20 scale-150">{service.icon}</div></div></div>
          </div>))}</div></div></section>

      <section className="section-padding bg-gray-50"><div className="container-width"><div className="text-center mb-16"><span className="text-accent font-semibold tracking-wider uppercase text-sm">Our Process</span><h2 className="text-3xl md:text-4xl font-bold text-primary mt-4 mb-4">From Vision to Reality</h2><div className="gold-line-center mb-6"></div></div>
        <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8">
          <div className="text-center"><div className="w-16 h-16 bg-primary text-white rounded-full flex items-center justify-center mx-auto mb-4 text-2xl font-bold font-serif">1</div><h3 className="text-xl font-bold text-primary mb-2">Consultation</h3><p className="text-gray-600">We meet to discuss your vision, preferences and budget. This initial consultation is always complimentary.</p></div>
          <div className="text-center"><div className="w-16 h-16 bg-primary text-white rounded-full flex items-center justify-center mx-auto mb-4 text-2xl font-bold font-serif">2</div><h3 className="text-xl font-bold text-primary mb-2">Design</h3><p className="text-gray-600">Our designers create detailed sketches and 3D renders. You approve every detail before we proceed.</p></div>
          <div className="text-center"><div className="w-16 h-16 bg-primary text-white rounded-full flex items-center justify-center mx-auto mb-4 text-2xl font-bold font-serif">3</div><h3 className="text-xl font-bold text-primary mb-2">Crafting</h3><p className="text-gray-600">Our master craftspeople bring your design to life in our Hatton Garden workshop using traditional techniques.</p></div>
          <div className="text-center"><div className="w-16 h-16 bg-primary text-white rounded-full flex items-center justify-center mx-auto mb-4 text-2xl font-bold font-serif">4</div><h3 className="text-xl font-bold text-primary mb-2">Presentation</h3><p className="text-gray-600">Your finished piece is presented to you beautifully packaged, with full certification and a lifetime warranty.</p></div>
        </div></div></section>

      <section className="section-padding bg-primary"><div className="container-width text-center"><h2 className="text-3xl md:text-4xl font-bold text-white mb-4">Ready to Create Something Extraordinary?</h2><p className="text-xl text-gray-200 mb-8 max-w-2xl mx-auto">Book your complimentary consultation at our Hatton Garden workshop. Let us help you bring your vision to life.</p><div className="flex flex-col sm:flex-row justify-center gap-4"><Link href="/jeweller-hatton-garden/contact" className="btn-accent">Book Free Consultation</Link><a href="tel:02079467750" className="btn-outline border-white text-white hover:bg-white hover:text-primary">Call 020 7946 7750</a></div></div></section>
    </>
  );
}
