import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "About Us | Nobu-Trained Chef, Sustainably Sourced Fish",
  description: "Learn about Soho Sushi Kitchen - an intimate 45-cover Japanese restaurant on Wardour Street. Our head chef trained for 15 years at Nobu London. Sustainably sourced fish, open 7 days.",
  openGraph: { title: "About Us | Soho Sushi Kitchen", description: "Authentic Japanese sushi in Soho by a Nobu-trained head chef. Sustainably sourced, 45 intimate covers." },
};

export default function AboutPage() {
  return (
    <>
      <section className="hero-gradient py-20 lg:py-28"><div className="container-width"><div className="max-w-3xl"><span className="text-accent font-semibold tracking-wider uppercase text-sm">About Us</span><h1 className="text-4xl md:text-5xl font-bold text-white mt-4 mb-6">The Art of Sushi in Soho</h1><p className="text-xl text-gray-200 leading-relaxed">Soho Sushi Kitchen is an intimate Japanese restaurant where fifteen years of Nobu training meets a passion for sustainably sourced fish.</p></div></div></section>

      <section className="section-padding bg-white"><div className="container-width"><div className="grid lg:grid-cols-2 gap-16 items-center">
        <div><span className="text-accent font-semibold tracking-wider uppercase text-sm">Our Story</span><h2 className="text-3xl md:text-4xl font-bold text-primary mt-4 mb-4">From Nobu to Soho</h2><div className="gold-line mb-6"></div>
          <p className="text-lg text-gray-600 mb-6 leading-relaxed">Chef Takeshi Yamamoto spent fifteen years at Nobu London, rising through the ranks from commis chef to senior sushi master. During that time he refined his craft under some of the world&apos;s most demanding sushi chefs, learning the discipline, precision and deep respect for ingredients that defines Japanese culinary culture.</p>
          <p className="text-gray-600 mb-6 leading-relaxed">In 2020, Chef Takeshi opened Soho Sushi Kitchen on Wardour Street with a simple mission: to serve the finest quality sushi in an intimate, welcoming setting, using only sustainably sourced fish. There are no gimmicks here &mdash; just exceptional ingredients, prepared with years of expertise, and served with genuine warmth.</p>
          <p className="text-gray-600 leading-relaxed">With just 45 covers including an eight-seat cypress wood sushi bar, we keep things deliberately small. This allows us to give every guest the attention they deserve, and it means every piece of sushi is prepared fresh to order. Our fish arrives daily from sustainable fisheries, and Chef Takeshi personally inspects each delivery before it enters the kitchen.</p>
        </div>
        <div className="bg-gray-50 p-8 lg:p-12 rounded-sm"><div className="grid grid-cols-2 gap-8">
          <div className="text-center p-6 bg-white rounded-sm shadow-sm"><div className="stat-number">15</div><p className="text-gray-600 mt-2 font-medium">Years Nobu Training</p></div>
          <div className="text-center p-6 bg-white rounded-sm shadow-sm"><div className="stat-number">45</div><p className="text-gray-600 mt-2 font-medium">Intimate Covers</p></div>
          <div className="text-center p-6 bg-white rounded-sm shadow-sm"><div className="stat-number">30+</div><p className="text-gray-600 mt-2 font-medium">Premium Sakes</p></div>
          <div className="text-center p-6 bg-white rounded-sm shadow-sm"><div className="stat-number">4.8</div><p className="text-gray-600 mt-2 font-medium">Google Rating</p></div>
        </div></div>
      </div></div></section>

      <section className="section-padding bg-gray-50"><div className="container-width"><div className="text-center mb-16"><span className="text-accent font-semibold tracking-wider uppercase text-sm">Our Values</span><h2 className="text-3xl md:text-4xl font-bold text-primary mt-4 mb-4">What We Stand For</h2><div className="gold-line-center mb-6"></div></div>
        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
          <div className="card-premium p-8"><div className="w-16 h-16 bg-primary/10 rounded-full flex items-center justify-center mb-6"><svg className="w-8 h-8 text-primary" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M5 3v4M3 5h4M6 17v4m-2-2h4m5-16l2.286 6.857L21 12l-5.714 2.143L13 21l-2.286-6.857L5 12l5.714-2.143L13 3z" /></svg></div><h3 className="text-xl font-bold text-primary mb-3">Precision</h3><p className="text-gray-600">Every cut, every portion of rice, every brush of soy is executed with the precision that comes from fifteen years of professional training. There are no shortcuts.</p></div>
          <div className="card-premium p-8"><div className="w-16 h-16 bg-primary/10 rounded-full flex items-center justify-center mb-6"><svg className="w-8 h-8 text-primary" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M3.055 11H5a2 2 0 012 2v1a2 2 0 002 2 2 2 0 012 2v2.945M8 3.935V5.5A2.5 2.5 0 0010.5 8h.5a2 2 0 012 2 2 2 0 104 0 2 2 0 012-2h1.064M15 20.488V18a2 2 0 012-2h3.064M21 12a9 9 0 11-18 0 9 9 0 0118 0z" /></svg></div><h3 className="text-xl font-bold text-primary mb-3">Sustainability</h3><p className="text-gray-600">We source from sustainable fisheries and seasonal markets. Every piece of fish is traceable and responsibly caught, because the ocean&apos;s future matters to us.</p></div>
          <div className="card-premium p-8"><div className="w-16 h-16 bg-primary/10 rounded-full flex items-center justify-center mb-6"><svg className="w-8 h-8 text-primary" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" /></svg></div><h3 className="text-xl font-bold text-primary mb-3">Seasonality</h3><p className="text-gray-600">Our menu changes with the seasons, showcasing each ingredient at its absolute peak. What is on the plate today reflects what was best at the market this morning.</p></div>
          <div className="card-premium p-8"><div className="w-16 h-16 bg-primary/10 rounded-full flex items-center justify-center mb-6"><svg className="w-8 h-8 text-primary" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M12 4.354a4 4 0 110 5.292M15 21H3v-1a6 6 0 0112 0v1zm0 0h6v-1a6 6 0 00-9-5.197M13 7a4 4 0 11-8 0 4 4 0 018 0z" /></svg></div><h3 className="text-xl font-bold text-primary mb-3">Intimacy</h3><p className="text-gray-600">With just 45 covers, we keep things deliberately small. This means every guest receives genuine attention, and every piece of sushi is made fresh to order.</p></div>
          <div className="card-premium p-8"><div className="w-16 h-16 bg-primary/10 rounded-full flex items-center justify-center mb-6"><svg className="w-8 h-8 text-primary" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" /></svg></div><h3 className="text-xl font-bold text-primary mb-3">Tradition</h3><p className="text-gray-600">We honour the centuries-old traditions of Japanese sushi-making. Our techniques, tools and philosophy are rooted in authentic practice, not trends.</p></div>
          <div className="card-premium p-8"><div className="w-16 h-16 bg-primary/10 rounded-full flex items-center justify-center mb-6"><svg className="w-8 h-8 text-primary" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z" /><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M15 11a3 3 0 11-6 0 3 3 0 016 0z" /></svg></div><h3 className="text-xl font-bold text-primary mb-3">Soho Spirit</h3><p className="text-gray-600">We are proud to be part of Soho&apos;s vibrant dining scene. Our Wardour Street location is central, easy to reach, and open seven days a week.</p></div>
        </div>
      </div></section>

      <section className="section-padding bg-white"><div className="container-width"><div className="text-center mb-16"><span className="text-accent font-semibold tracking-wider uppercase text-sm">Our Location</span><h2 className="text-3xl md:text-4xl font-bold text-primary mt-4 mb-4">Wardour Street, Soho</h2><div className="gold-line-center mb-6"></div><p className="text-lg text-gray-600 max-w-3xl mx-auto">We&apos;re on Wardour Street in the heart of Soho, steps from Leicester Square and Piccadilly Circus. Easy to reach, open every day.</p></div>
        <div className="grid md:grid-cols-3 gap-8">
          <div className="text-center p-8 bg-gray-50 rounded-sm"><svg className="w-10 h-10 text-accent mx-auto mb-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z" /><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M15 11a3 3 0 11-6 0 3 3 0 016 0z" /></svg><h3 className="text-lg font-bold text-primary mb-2">Leicester Square</h3><p className="text-gray-600">2-minute walk</p></div>
          <div className="text-center p-8 bg-gray-50 rounded-sm"><svg className="w-10 h-10 text-accent mx-auto mb-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z" /><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M15 11a3 3 0 11-6 0 3 3 0 016 0z" /></svg><h3 className="text-lg font-bold text-primary mb-2">Piccadilly Circus</h3><p className="text-gray-600">3-minute walk</p></div>
          <div className="text-center p-8 bg-gray-50 rounded-sm"><svg className="w-10 h-10 text-accent mx-auto mb-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z" /><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M15 11a3 3 0 11-6 0 3 3 0 016 0z" /></svg><h3 className="text-lg font-bold text-primary mb-2">Tottenham Court Road</h3><p className="text-gray-600">5-minute walk</p></div>
        </div>
      </div></section>

      <section className="section-padding bg-primary"><div className="container-width text-center"><h2 className="text-3xl md:text-4xl font-bold text-white mb-4">Ready to Dine With Us?</h2><p className="text-xl text-gray-200 mb-8 max-w-2xl mx-auto">Reserve your table and experience authentic Japanese sushi in the heart of Soho. Open seven days a week for lunch and dinner.</p><div className="flex flex-col sm:flex-row justify-center gap-4"><Link href="/sushi-soho/contact" className="btn-accent">Reserve a Table</Link><a href="tel:02079463380" className="btn-outline border-white text-white hover:bg-white hover:text-primary">Call 020 7946 3380</a></div></div></section>
    </>
  );
}
