import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Treatments | Massage, Facials, Body Wraps & More",
  description: "Explore our luxury spa treatments including deep tissue massage, facials, body wraps, aromatherapy, and couples packages at Mayfair Wellness Spa.",
  openGraph: { title: "Treatments | Mayfair Wellness Spa", description: "Luxury spa treatments in Mayfair. Massage, facials, body wraps, aromatherapy, and couples packages." },
};

export default function ServicesPage() {
  const services = [
    { id: "deep-tissue-massage", title: "Deep Tissue Massage", subtitle: "Release, Restore, Recover", description: "Our signature deep tissue massage targets the deeper layers of muscle and connective tissue. Using sustained pressure and slow strokes, your therapist works to release chronic tension, break down adhesions, and restore natural movement patterns. Ideal for those with persistent muscle tightness, postural imbalances, or sports-related tension.", features: ["60 or 90-minute sessions available", "Pre-treatment consultation to identify problem areas", "Combination of deep tissue, trigger point, and myofascial release", "Hot towels and aromatherapy oils included", "Post-treatment stretching recommendations", "Regular booking discounts for ongoing maintenance"], icon: (<svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z" /></svg>) },
    { id: "facial-treatments", title: "Facial Treatments", subtitle: "Glow From Within", description: "Our luxury facials go beyond the surface. Each treatment begins with a thorough skin analysis, followed by a bespoke protocol using premium organic products. Whether you are looking to combat ageing, brighten dull skin, or deeply hydrate, our facialists create a treatment plan that delivers visible results.", features: ["Express, signature, and advanced facial options", "Skin analysis with personalised product recommendations", "LED light therapy and microcurrent technology available", "Premium Elemis and ESPA product lines", "Eye treatments and lip renewal add-ons", "Seasonal facial menus throughout the year"], icon: (<svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M5.121 17.804A13.937 13.937 0 0112 16c2.5 0 4.847.655 6.879 1.804M15 10a3 3 0 11-6 0 3 3 0 016 0zm6 2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>) },
    { id: "body-wraps", title: "Body Wraps", subtitle: "Total Body Renewal", description: "Our body wrap treatments cocoon your body in nourishing ingredients to detoxify, hydrate, and smooth. From marine algae detox wraps to rich shea butter hydration treatments, each wrap is designed to leave your skin glowing and your body feeling lighter and more energised.", features: ["Marine algae detox wrap for purification", "Shea butter hydration wrap for dry skin", "Slimming seaweed wrap with body sculpting massage", "Full-body exfoliation included before every wrap", "Thermal blanket for deep product absorption", "Complimentary herbal tea and relaxation time after treatment"], icon: (<svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M20 7l-8-4-8 4m16 0l-8 4m8-4v10l-8 4m0-10L4 7m8 4v10M4 7v10l8 4" /></svg>) },
    { id: "aromatherapy", title: "Aromatherapy", subtitle: "Healing Through Scent", description: "Aromatherapy combines therapeutic massage with the healing power of essential oils. Your therapist selects a bespoke blend based on your needs — whether you seek relaxation, energy, pain relief, or emotional balance. The result is a deeply restorative experience that benefits body and mind.", features: ["Bespoke essential oil blending for each session", "Swedish-based massage with aromatherapy techniques", "Oils sourced from organic, sustainable suppliers", "Options for relaxation, energising, or balancing blends", "Scalp massage and facial pressure points included", "Take-home oil sample to continue benefits at home"], icon: (<svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M7 21a4 4 0 01-4-4V5a2 2 0 012-2h4a2 2 0 012 2v12a4 4 0 01-4 4zm0 0h12a2 2 0 002-2v-4a2 2 0 00-2-2h-2.343M11 7.343l1.657-1.657a2 2 0 012.828 0l2.829 2.829a2 2 0 010 2.828l-8.486 8.485M7 17h.01" /></svg>) },
    { id: "couples-treatments", title: "Couples Treatments", subtitle: "Share the Experience", description: "Our dual treatment suite allows you to enjoy spa treatments side by side with your partner, friend, or family member. Choose from our curated couples packages or create your own combination. Each package includes use of the relaxation lounge and complimentary refreshments.", features: ["Private dual treatment suite", "Side-by-side massage, facial, or combination packages", "Champagne and chocolates add-on available", "Anniversary, birthday, and celebration packages", "Gift vouchers available for all couples experiences", "Pre-treatment consultation for both guests"], icon: (<svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M12 4.354a4 4 0 110 5.292M15 21H3v-1a6 6 0 0112 0v1zm0 0h6v-1a6 6 0 00-9-5.197M13 7a4 4 0 11-8 0 4 4 0 018 0z" /></svg>) },
    { id: "membership-packages", title: "Membership Packages", subtitle: "Invest in Your Wellbeing", description: "Our monthly memberships make regular self-care accessible and rewarding. Members enjoy priority booking, exclusive discounts on all treatments, complimentary access to our thermal suite, and a monthly treatment allowance. It is the most cost-effective way to make wellness a consistent part of your routine.", features: ["Monthly treatment credit included in membership", "Priority booking for peak time slots", "15% discount on all additional treatments", "Complimentary thermal suite access", "Guest passes included each quarter", "Flexible membership tiers to suit every budget"], icon: (<svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1M21 12a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>) },
  ];

  return (
    <>
      <section className="hero-gradient py-20 lg:py-28"><div className="container-width"><div className="max-w-3xl"><span className="text-accent font-semibold tracking-wider uppercase text-sm">Our Treatments</span><h1 className="text-4xl md:text-5xl font-bold text-white mt-4 mb-6">Spa Treatments &amp; Packages</h1><p className="text-xl text-gray-200 leading-relaxed">Every treatment is performed by a qualified therapist using premium products, tailored to your individual needs and preferences.</p></div></div></section>

      <section className="section-padding bg-white">
        <div className="container-width">
          <div className="text-center mb-16"><h2 className="text-3xl md:text-4xl font-bold text-primary mb-4">Our Treatment Menu</h2><div className="gold-line-center mb-6"></div><p className="text-lg text-gray-600 max-w-3xl mx-auto">From targeted massage therapy to indulgent facials and body treatments, discover the perfect experience for you.</p></div>
          <div className="space-y-16">
            {services.map((service, index) => (
              <div key={service.id} id={service.id} className={`grid lg:grid-cols-2 gap-12 items-center ${index % 2 === 1 ? "lg:flex-row-reverse" : ""}`}>
                <div className={index % 2 === 1 ? "lg:order-2" : ""}><div className="text-primary mb-4">{service.icon}</div><h3 className="text-2xl md:text-3xl font-bold text-primary mb-2">{service.title}</h3><p className="text-accent font-semibold mb-4">{service.subtitle}</p><p className="text-gray-600 mb-6 leading-relaxed">{service.description}</p>
                  <ul className="space-y-3 mb-8">{service.features.map((f, i) => (<li key={i} className="flex items-start gap-3"><svg className="w-5 h-5 text-accent mt-0.5 flex-shrink-0" fill="currentColor" viewBox="0 0 20 20"><path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" /></svg><span className="text-gray-700">{f}</span></li>))}</ul>
                  <Link href="/spa-mayfair/contact" className="btn-accent">Book This Treatment</Link>
                </div>
                <div className={`bg-gray-50 p-8 lg:p-12 rounded-sm ${index % 2 === 1 ? "lg:order-1" : ""}`}><div className="aspect-video bg-gradient-to-br from-primary to-secondary rounded-sm flex items-center justify-center"><div className="text-white opacity-20 scale-150">{service.icon}</div></div></div>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section className="section-padding bg-gray-50"><div className="container-width"><div className="text-center mb-16"><span className="text-accent font-semibold tracking-wider uppercase text-sm">Your Experience</span><h2 className="text-3xl md:text-4xl font-bold text-primary mt-4 mb-4">What to Expect</h2><div className="gold-line-center mb-6"></div></div>
        <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8">
          {[{ n: "1", t: "Book", d: "Reserve your treatment online, by phone, or email. We will confirm your appointment promptly." }, { n: "2", t: "Arrive", d: "Arrive 15 minutes early to relax in our lounge. Your therapist will conduct a brief consultation." }, { n: "3", t: "Enjoy", d: "Surrender to the experience. Your treatment is tailored to you from start to finish." }, { n: "4", t: "Glow", d: "After your treatment, unwind in our relaxation room with herbal tea and take home aftercare advice." }].map((s, i) => (
            <div key={i} className="text-center"><div className="w-16 h-16 bg-primary text-white rounded-full flex items-center justify-center mx-auto mb-4 text-2xl font-bold font-serif">{s.n}</div><h3 className="text-xl font-bold text-primary mb-2">{s.t}</h3><p className="text-gray-600">{s.d}</p></div>
          ))}
        </div>
      </div></section>

      <section className="section-padding bg-primary"><div className="container-width text-center"><h2 className="text-3xl md:text-4xl font-bold text-white mb-4">Ready to Unwind?</h2><p className="text-xl text-gray-200 mb-8 max-w-2xl mx-auto">Book your treatment today and escape to Mayfair&apos;s finest wellness destination.</p>
        <div className="flex flex-col sm:flex-row justify-center gap-4"><Link href="/spa-mayfair/contact" className="btn-accent">Book a Treatment</Link><a href="tel:02079468800" className="btn-outline border-white text-white hover:bg-white hover:text-primary">Call 020 7946 8800</a></div>
      </div></section>
    </>
  );
}
