import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = { title: "Dental Services | General, Cosmetic & Emergency Dentistry", description: "Full range of dental services in Clapham. General dentistry, cosmetic treatments, teeth whitening, implants, Invisalign, and emergency care. GDC registered." };

export default function ServicesPage() {
  const services = [
    { id: "general-dentistry", title: "General Dentistry", subtitle: "The Foundation of a Healthy Smile", description: "Good oral health starts with regular care. Our general dentistry services focus on prevention, early detection, and treatment of dental problems. We make every visit comfortable and thorough, ensuring your teeth and gums stay healthy for life.", features: ["Comprehensive dental check-ups and examinations", "Dental hygiene appointments and scale & polish", "Fillings — tooth-coloured composite and amalgam", "Root canal treatment (endodontics)", "Tooth extractions including wisdom teeth", "Mouthguards for sports and teeth grinding"], icon: "M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z" },
    { id: "cosmetic-dentistry", title: "Cosmetic Dentistry", subtitle: "Transform Your Smile, Transform Your Confidence", description: "Your smile is often the first thing people notice. Our cosmetic treatments can correct chips, gaps, discolouration, and misalignment to give you the smile you've always wanted. We combine artistry with clinical precision for natural-looking results.", features: ["Porcelain veneers for a flawless finish", "Composite bonding to repair chips and gaps", "Complete smile makeovers", "Tooth reshaping and contouring", "Gum contouring for a balanced smile line", "Digital smile design — preview your results before treatment"], icon: "M5 3v4M3 5h4M6 17v4m-2-2h4m5-16l2.286 6.857L21 12l-5.714 2.143L13 21l-2.286-6.857L5 12l5.714-2.143L13 3z" },
    { id: "teeth-whitening", title: "Teeth Whitening", subtitle: "A Brighter Smile in Just One Visit", description: "Professional teeth whitening delivers dramatically better results than shop-bought products. We offer both in-surgery whitening for instant results and take-home kits for gradual brightening at your convenience.", features: ["In-surgery whitening — results in one appointment", "Custom take-home whitening trays", "Combination packages for best results", "Safe, dentist-supervised treatment", "Long-lasting results with proper care", "Touch-up treatments available"], icon: "M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z" },
    { id: "dental-implants", title: "Dental Implants", subtitle: "The Permanent Solution for Missing Teeth", description: "Dental implants are the most natural-feeling replacement for missing teeth. A titanium post is placed in your jawbone, acting as a root for a new crown. The result looks, feels, and functions just like a natural tooth.", features: ["Single tooth implants with natural-looking crowns", "Multiple implant solutions for several missing teeth", "All-on-4 full arch replacement", "CT scanning for precise implant planning", "Bone grafting where required", "Lifetime guarantee on implant fixtures"], icon: "M19.428 15.428a2 2 0 00-1.022-.547l-2.387-.477a6 6 0 00-3.86.517l-.318.158a6 6 0 01-3.86.517L6.05 15.21a2 2 0 00-1.806.547M8 4h8l-1 1v5.172a2 2 0 00.586 1.414l5 5c1.26 1.26.367 3.414-1.415 3.414H4.828c-1.782 0-2.674-2.154-1.414-3.414l5-5A2 2 0 009 10.172V5L8 4z" },
    { id: "invisalign", title: "Invisalign", subtitle: "Straight Teeth Without the Braces", description: "Invisalign uses a series of custom-made, virtually invisible aligners to gradually straighten your teeth. No metal brackets, no wires — just a comfortable, discreet path to a perfect smile. Most treatments complete in 6-18 months.", features: ["Free Invisalign consultation and assessment", "3D digital scanning — no messy impressions", "Custom-made clear aligners changed every 1-2 weeks", "Removable for eating, drinking, and brushing", "Suitable for mild to moderate alignment issues", "Interest-free finance available"], icon: "M14.828 14.828a4 4 0 01-5.656 0M9 10h.01M15 10h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" },
    { id: "emergency-dental-care", title: "Emergency Dental Care", subtitle: "Same-Day Relief When You Need It Most", description: "Dental emergencies can happen at any time. Whether it's severe toothache, a knocked-out tooth, or a broken filling, we offer same-day emergency appointments to get you out of pain and protect your dental health.", features: ["Same-day emergency appointments available", "Severe toothache diagnosis and relief", "Treatment for knocked-out or broken teeth", "Lost or broken filling and crown repair", "Dental abscess treatment", "After-hours emergency advice line"], icon: "M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" },
  ];

  return (
    <>
      <section className="hero-gradient py-20 lg:py-28"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="max-w-3xl"><span className="text-[var(--accent)] font-semibold tracking-wider uppercase text-sm">Our Services</span><h1 className="text-4xl md:text-5xl font-bold text-white mt-4 mb-6 font-serif">Dental Services in Clapham</h1><p className="text-xl text-gray-200 leading-relaxed">Comprehensive dental care from GDC registered dentists. NHS and private options available with evening appointments.</p></div></div></section>

      <section className="py-16 lg:py-24 bg-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16"><h2 className="text-3xl md:text-4xl font-bold text-[var(--primary)] mb-4 font-serif">Our Treatments</h2><div className="w-16 h-1 bg-[var(--accent)] mx-auto mb-6"></div><p className="text-lg text-gray-600 max-w-3xl mx-auto">From routine check-ups to advanced cosmetic procedures, our experienced team provides the full spectrum of dental care in a modern, welcoming environment.</p></div>
          <div className="space-y-16">
            {services.map((service, index) => (
              <div key={service.id} id={service.id} className={`grid lg:grid-cols-2 gap-12 items-center`}>
                <div className={index % 2 === 1 ? "lg:order-2" : ""}><div className="text-[var(--primary)] mb-4"><svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d={service.icon} /></svg></div><h3 className="text-2xl md:text-3xl font-bold text-[var(--primary)] mb-2 font-serif">{service.title}</h3><p className="text-[var(--accent)] font-semibold mb-4">{service.subtitle}</p><p className="text-gray-600 mb-6 leading-relaxed">{service.description}</p><ul className="space-y-3 mb-8">{service.features.map((f,i) => (<li key={i} className="flex items-start gap-3"><svg className="w-5 h-5 text-[var(--accent)] mt-0.5 flex-shrink-0" fill="currentColor" viewBox="0 0 20 20"><path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" /></svg><span className="text-gray-700">{f}</span></li>))}</ul><Link href="/dentist-clapham/contact" className="bg-[var(--accent)] text-white px-8 py-3 font-semibold rounded-sm hover:bg-[var(--accent-light)] transition-colors inline-block">Book Appointment</Link></div>
                <div className={`bg-gray-50 p-8 lg:p-12 rounded-sm ${index % 2 === 1 ? "lg:order-1" : ""}`}><div className="aspect-video bg-gradient-to-br from-[var(--primary)] to-[var(--secondary)] rounded-sm flex items-center justify-center"><div className="text-white opacity-20 scale-150"><svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d={service.icon} /></svg></div></div></div>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section className="py-16 lg:py-24 bg-gray-50"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="text-center mb-16"><span className="text-[var(--accent)] font-semibold tracking-wider uppercase text-sm">Your Journey</span><h2 className="text-3xl md:text-4xl font-bold text-[var(--primary)] mt-4 mb-4 font-serif">What to Expect</h2><div className="w-16 h-1 bg-[var(--accent)] mx-auto mb-6"></div></div><div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8">{[{ n:"1", t:"Book", d:"Schedule your appointment online or by phone. New patients welcome." },{ n:"2", t:"Consultation", d:"We examine your teeth, discuss your goals, and create a personalised treatment plan." },{ n:"3", t:"Treatment", d:"Expert care in a comfortable, modern environment. We explain every step." },{ n:"4", t:"Aftercare", d:"Follow-up appointments and ongoing care to maintain your results." }].map((s) => (<div key={s.n} className="text-center"><div className="w-16 h-16 bg-[var(--primary)] text-white rounded-full flex items-center justify-center mx-auto mb-4 text-2xl font-bold font-serif">{s.n}</div><h3 className="text-xl font-bold text-[var(--primary)] mb-2 font-serif">{s.t}</h3><p className="text-gray-600">{s.d}</p></div>))}</div></div></section>

      <section className="py-16 lg:py-24 bg-[var(--primary)]"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center"><h2 className="text-3xl md:text-4xl font-bold text-white mb-4 font-serif">Ready to Book Your Appointment?</h2><p className="text-xl text-gray-200 mb-8 max-w-2xl mx-auto">New patients welcome. NHS and private options. Evening appointments available.</p><div className="flex flex-col sm:flex-row justify-center gap-4"><Link href="/dentist-clapham/contact" className="bg-[var(--accent)] text-white px-8 py-4 font-semibold rounded-sm hover:bg-[var(--accent-light)] transition-colors inline-block">Book Appointment</Link><a href="tel:02079461234" className="border-2 border-white text-white px-8 py-4 font-semibold rounded-sm hover:bg-white hover:text-[var(--primary)] transition-colors inline-block">Call 020 7946 1234</a></div></div></section>

      <section className="py-8 bg-gray-100"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="bg-gray-50 border border-gray-200 rounded-sm p-4 text-sm text-gray-600"><p><strong>GDC Registered:</strong> All dentists are GDC registered. Treatments are subject to clinical assessment. Cosmetic treatment results may vary. Finance options available on selected treatments.</p></div></div></section>
    </>
  );
}
