import type { Metadata } from "next";
import Link from "next/link";
export const metadata: Metadata = { title: "About Us | HCPC Registered Speech & Language Therapists", description: "Learn about Hampstead Speech Therapy - 6 HCPC registered therapists helping over 3,000 children and adults find their voice since 2014.", openGraph: { title: "About Us | Hampstead Speech Therapy", description: "HCPC registered speech and language therapy practice in Hampstead since 2014." } };

export default function AboutPage() {
  return (
    <>
      <section className="hero-gradient py-20 lg:py-28"><div className="container-width"><div className="max-w-3xl"><span className="text-accent font-semibold tracking-wider uppercase text-sm">About Us</span><h1 className="text-4xl md:text-5xl font-bold text-white mt-4 mb-6">Helping People Find Their Voice</h1><p className="text-xl text-gray-200 leading-relaxed">A team of six specialist speech and language therapists providing compassionate, evidence-based care from our Hampstead clinic since 2014.</p></div></div></section>

      <section className="section-padding bg-white"><div className="container-width"><div className="grid lg:grid-cols-2 gap-16 items-center"><div><span className="text-accent font-semibold tracking-wider uppercase text-sm">Our Story</span><h2 className="text-3xl md:text-4xl font-bold text-primary mt-4 mb-4">A Practice Built on Care</h2><div className="gold-line mb-6"></div>
        <p className="text-lg text-gray-600 mb-6 leading-relaxed">Hampstead Speech Therapy was founded in 2014 by a senior speech and language therapist who had spent over a decade working in NHS hospitals and community clinics. The vision was simple: to create a practice where clients receive the time, expertise and individual attention that pressured NHS caseloads can make difficult.</p>
        <p className="text-gray-600 mb-6 leading-relaxed">Our clinic on Flask Walk, in the heart of Hampstead village, provides a calm and welcoming environment. The therapy rooms are purpose-built for both children and adults, with natural light, minimal distractions and everything we need to deliver the highest quality therapy.</p>
        <p className="text-gray-600 leading-relaxed">Today our team of six therapists includes specialists in paediatric speech and language therapy, adult neurological communication disorders, stammering, voice therapy and dysphagia. We have helped over three thousand clients and remain as passionate about our work as we were on day one.</p>
      </div><div className="bg-gray-50 p-8 lg:p-12 rounded-sm"><div className="grid grid-cols-2 gap-8"><div className="text-center p-6 bg-white rounded-sm shadow-sm"><div className="stat-number">3k+</div><p className="text-gray-600 mt-2 font-medium">Clients Helped</p></div><div className="text-center p-6 bg-white rounded-sm shadow-sm"><div className="stat-number">6</div><p className="text-gray-600 mt-2 font-medium">Specialist Therapists</p></div><div className="text-center p-6 bg-white rounded-sm shadow-sm"><div className="stat-number">11+</div><p className="text-gray-600 mt-2 font-medium">Years Experience</p></div><div className="text-center p-6 bg-white rounded-sm shadow-sm"><div className="stat-number">HCPC</div><p className="text-gray-600 mt-2 font-medium">Registered Practice</p></div></div></div></div></div></section>

      <section className="section-padding bg-gray-50"><div className="container-width"><div className="text-center mb-16"><span className="text-accent font-semibold tracking-wider uppercase text-sm">Our Values</span><h2 className="text-3xl md:text-4xl font-bold text-primary mt-4 mb-4">What Guides Our Practice</h2><div className="gold-line-center mb-6"></div></div>
        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
          {[{t:"Evidence-Based Practice",d:"Every therapy approach we use is grounded in the latest research. We stay current through continuous professional development and active involvement in clinical research."},{t:"Individual Care",d:"No two clients are the same. We take time to understand your unique circumstances, preferences and goals, and we tailor every therapy programme accordingly."},{t:"Family Involvement",d:"Communication happens in everyday life, not just in the therapy room. We involve families, carers and schools so that strategies are practised and reinforced throughout the week."},{t:"Honest Communication",d:"We are straightforward about what therapy can achieve and the timescales involved. You will always know where you stand and what the next steps are."},{t:"Warmth and Patience",d:"Communication difficulties can be frustrating and sometimes distressing. We create a safe, non-judgemental space where you can work towards your goals at your own pace."},{t:"Professional Standards",d:"All our therapists are HCPC registered and members of the Royal College of Speech and Language Therapists. We carry full professional indemnity insurance."}].map((v) => (
            <div key={v.t} className="card-premium p-8"><div className="w-16 h-16 bg-primary/10 rounded-full flex items-center justify-center mb-6"><svg className="w-8 h-8 text-primary" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" /></svg></div><h3 className="text-xl font-bold text-primary mb-3">{v.t}</h3><p className="text-gray-600">{v.d}</p></div>
          ))}
        </div>
      </div></section>

      <section className="section-padding bg-white"><div className="container-width"><div className="text-center mb-16"><span className="text-accent font-semibold tracking-wider uppercase text-sm">Our Clinic</span><h2 className="text-3xl md:text-4xl font-bold text-primary mt-4 mb-4">Visit Us on Flask Walk</h2><div className="gold-line-center mb-6"></div><p className="text-lg text-gray-600 max-w-3xl mx-auto">Our clinic is tucked away on Flask Walk, one of Hampstead&apos;s most charming streets. Purpose-built therapy rooms in a calm, welcoming setting just moments from Hampstead station.</p></div>
        <div className="bg-gray-50 p-8 lg:p-12 rounded-sm border-t-4 border-accent max-w-3xl mx-auto"><address className="not-italic text-gray-700 mb-6 text-lg"><strong>Hampstead Speech Therapy</strong><br />8 Flask Walk<br />Hampstead, London NW3 1HE</address><div className="space-y-2 text-gray-600"><p><strong>Hampstead Station:</strong> 3-minute walk</p><p><strong>Belsize Park Station:</strong> 6-minute walk</p><p><strong>Finchley Road Station:</strong> 8-minute walk</p></div></div>
      </div></section>

      <section className="section-padding bg-primary"><div className="container-width text-center"><h2 className="text-3xl md:text-4xl font-bold text-white mb-4">Ready to Start Your Journey?</h2><p className="text-xl text-gray-200 mb-8 max-w-2xl mx-auto">Book a consultation to discuss your concerns with one of our specialist therapists. No GP referral needed.</p><div className="flex flex-col sm:flex-row justify-center gap-4"><Link href="/speech-therapist-hampstead/contact" className="btn-accent">Book Consultation</Link><a href="tel:02079464450" className="btn-outline border-white text-white hover:bg-white hover:text-primary">Call 020 7946 4450</a></div></div></section>
    </>
  );
}
