import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Chiropractic Treatments | Adjustments, Sports Chiropractic & More",
  description: "Evidence-based chiropractic treatments in Kensington. Spinal adjustments, decompression, sports chiropractic, posture correction, headache relief and pregnancy care.",
  openGraph: { title: "Chiropractic Treatments | Kensington Chiropractic Centre", description: "GCC registered chiropractic treatments in Kensington, W8." },
};

export default function ServicesPage() {
  const services = [
    { id: "chiropractic-adjustments", title: "Chiropractic Adjustments", subtitle: "Restore Proper Alignment", description: "Chiropractic adjustments are precise, controlled movements applied to spinal joints that aren't moving properly. By restoring normal joint function, we reduce nerve irritation, relieve pain and allow the body to heal naturally. We use a range of techniques tailored to your comfort and condition.", features: ["Diversified technique for precise corrections", "Thompson drop technique for gentle adjustments", "Activator method for low-force treatment", "Suitable for all ages from children to elderly", "Immediate relief for many conditions", "Regular maintenance care available"], icon: <svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M13 10V3L4 14h7v7l9-11h-7z" /></svg> },
    { id: "spinal-decompression", title: "Spinal Decompression", subtitle: "Non-Surgical Disc Treatment", description: "Spinal decompression therapy gently stretches the spine, creating negative pressure within the disc. This can help retract herniated or bulging disc material and promote the movement of water, oxygen and nutrient-rich fluids into the disc for healing.", features: ["Non-invasive alternative to surgery", "Effective for herniated and bulging discs", "Sciatica and radiculopathy treatment", "Comfortable, relaxing sessions", "Typically 15-20 sessions recommended", "Can be combined with other therapies"], icon: <svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M4 8V4m0 0h4M4 4l5 5m11-1V4m0 0h-4m4 0l-5 5M4 16v4m0 0h4m-4 0l5-5m11 5l-5-5m5 5v-4m0 4h-4" /></svg> },
    { id: "sports-chiropractic", title: "Sports Chiropractic", subtitle: "Perform at Your Best", description: "Our sports chiropractic service caters to athletes at every level. We treat sports injuries, help prevent future injuries and optimise biomechanical function for improved performance. Whether you're a weekend runner or a professional athlete, we understand the demands of your sport.", features: ["Injury diagnosis and treatment", "Biomechanical assessment", "Sports-specific rehabilitation exercises", "Performance optimisation", "Pre-event preparation", "Return-to-sport programmes"], icon: <svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M13 7h8m0 0v8m0-8l-8 8-4-4-6 6" /></svg> },
    { id: "posture-correction", title: "Posture Correction", subtitle: "Stand Taller, Feel Better", description: "Modern lifestyles, particularly desk-based work, create significant postural imbalances. Our posture correction programme combines chiropractic adjustments with targeted exercises and ergonomic advice to address the root causes of poor posture.", features: ["Comprehensive postural assessment", "Digital posture analysis", "Targeted adjustment protocols", "Corrective exercise programmes", "Ergonomic workplace advice", "Progress tracking and monitoring"], icon: <svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" /></svg> },
    { id: "headache-migraine", title: "Headache & Migraine Relief", subtitle: "Treat the Cause, Not Just the Symptoms", description: "Many headaches and migraines originate from dysfunction in the cervical spine. Our chiropractors are skilled at identifying and treating cervicogenic headaches, reducing their frequency, intensity and duration through precise spinal adjustments.", features: ["Cervical spine assessment and treatment", "Tension headache relief", "Cervicogenic migraine treatment", "Trigger point therapy", "Stress management advice", "Significant reduction in headache frequency"], icon: <svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z" /></svg> },
    { id: "pregnancy-chiropractic", title: "Pregnancy Chiropractic", subtitle: "Safe, Gentle Prenatal Care", description: "Pregnancy places significant demands on the spine and pelvis. Our chiropractors are trained in the Webster Technique and other pregnancy-safe methods to provide gentle, effective relief from back pain, pelvic pain and other musculoskeletal discomfort during pregnancy.", features: ["Webster Technique certified", "Safe throughout all trimesters", "Pelvic alignment for optimal positioning", "Lower back and sciatic pain relief", "Pregnancy-specific treatment tables", "Post-natal recovery support"], icon: <svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z" /></svg> },
  ];

  return (
    <>
      <section className="hero-gradient py-20 lg:py-28"><div className="container-width"><div className="max-w-3xl"><span className="text-accent font-semibold tracking-wider uppercase text-sm">Our Treatments</span><h1 className="text-4xl md:text-5xl font-bold text-white mt-4 mb-6">Chiropractic Treatments</h1><p className="text-xl text-gray-200 leading-relaxed">Evidence-based chiropractic care tailored to your condition. All treatments are delivered by GCC registered professionals.</p></div></div></section>

      <section className="section-padding bg-white"><div className="container-width">
        <div className="text-center mb-16"><h2 className="text-3xl md:text-4xl font-bold text-primary mb-4">Evidence-Based Care</h2><div className="gold-line-center mb-6"></div><p className="text-lg text-gray-600 max-w-3xl mx-auto">Every treatment plan is individually designed following a thorough assessment. We combine manual therapy with exercise rehabilitation for lasting results.</p></div>
        <div className="space-y-16">{services.map((service, index) => (
          <div key={service.id} id={service.id} className={`grid lg:grid-cols-2 gap-12 items-center ${index % 2 === 1 ? "lg:flex-row-reverse" : ""}`}>
            <div className={index % 2 === 1 ? "lg:order-2" : ""}><div className="text-primary mb-4">{service.icon}</div><h3 className="text-2xl md:text-3xl font-bold text-primary mb-2">{service.title}</h3><p className="text-accent font-semibold mb-4">{service.subtitle}</p><p className="text-gray-600 mb-6 leading-relaxed">{service.description}</p><ul className="space-y-3 mb-8">{service.features.map((f, i) => (<li key={i} className="flex items-start gap-3"><svg className="w-5 h-5 text-accent mt-0.5 flex-shrink-0" fill="currentColor" viewBox="0 0 20 20"><path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" /></svg><span className="text-gray-700">{f}</span></li>))}</ul><Link href="/chiropractor-kensington/contact" className="btn-accent">Book This Treatment</Link></div>
            <div className={`bg-gray-50 p-8 lg:p-12 rounded-sm ${index % 2 === 1 ? "lg:order-1" : ""}`}><div className="aspect-video bg-gradient-to-br from-primary to-secondary rounded-sm flex items-center justify-center"><div className="text-white opacity-20 scale-150">{service.icon}</div></div></div>
          </div>
        ))}</div>
      </div></section>

      <section className="section-padding bg-gray-50"><div className="container-width"><div className="text-center mb-16"><span className="text-accent font-semibold tracking-wider uppercase text-sm">Your Journey</span><h2 className="text-3xl md:text-4xl font-bold text-primary mt-4 mb-4">What to Expect</h2><div className="gold-line-center mb-6"></div></div>
        <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8">
          <div className="text-center"><div className="w-16 h-16 bg-primary text-white rounded-full flex items-center justify-center mx-auto mb-4 text-2xl font-bold font-serif">1</div><h3 className="text-xl font-bold text-primary mb-2">Initial Assessment</h3><p className="text-gray-600">Thorough consultation, examination and diagnosis. We explain your condition clearly and answer all your questions.</p></div>
          <div className="text-center"><div className="w-16 h-16 bg-primary text-white rounded-full flex items-center justify-center mx-auto mb-4 text-2xl font-bold font-serif">2</div><h3 className="text-xl font-bold text-primary mb-2">Treatment Plan</h3><p className="text-gray-600">A personalised plan outlining recommended treatments, expected outcomes and timeline for recovery.</p></div>
          <div className="text-center"><div className="w-16 h-16 bg-primary text-white rounded-full flex items-center justify-center mx-auto mb-4 text-2xl font-bold font-serif">3</div><h3 className="text-xl font-bold text-primary mb-2">Active Treatment</h3><p className="text-gray-600">Regular treatments combined with home exercises and lifestyle advice for optimal recovery.</p></div>
          <div className="text-center"><div className="w-16 h-16 bg-primary text-white rounded-full flex items-center justify-center mx-auto mb-4 text-2xl font-bold font-serif">4</div><h3 className="text-xl font-bold text-primary mb-2">Maintenance Care</h3><p className="text-gray-600">Optional ongoing care to maintain your results and prevent recurrence of symptoms.</p></div>
        </div>
      </div></section>

      <section className="section-padding bg-primary"><div className="container-width text-center"><h2 className="text-3xl md:text-4xl font-bold text-white mb-4">Start Your Recovery Today</h2><p className="text-xl text-gray-200 mb-8 max-w-2xl mx-auto">Book your initial consultation and take the first step towards a pain-free life.</p><div className="flex flex-col sm:flex-row justify-center gap-4"><Link href="/chiropractor-kensington/contact" className="btn-accent">Book an Appointment</Link><a href="tel:02079465890" className="btn-outline border-white text-white hover:bg-white hover:text-primary">Call 020 7946 5890</a></div></div></section>
    </>
  );
}
