import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "About Us | SRA Regulated Solicitors in Wimbledon",
  description: "Learn about Wimbledon Legal Services - SRA regulated solicitors in Wimbledon, SW19. Experienced legal team providing expert advice across multiple practice areas.",
  openGraph: { title: "About Us | Wimbledon Legal Services", description: "SRA regulated solicitors in Wimbledon providing expert legal services since 2008." },
};

export default function AboutPage() {
  return (
    <>
      <section className="hero-gradient py-20 lg:py-28"><div className="container-width"><div className="max-w-3xl"><span className="text-accent font-semibold tracking-wider uppercase text-sm">About Us</span><h1 className="text-4xl md:text-5xl font-bold text-white mt-4 mb-6">Experienced Solicitors, Personal Service</h1><p className="text-xl text-gray-200 leading-relaxed">SRA regulated solicitors providing clear, practical legal advice from our office on The Broadway in Wimbledon since 2008.</p></div></div></section>

      <section className="section-padding bg-white"><div className="container-width"><div className="grid lg:grid-cols-2 gap-16 items-center"><div><span className="text-accent font-semibold tracking-wider uppercase text-sm">Our Story</span><h2 className="text-3xl md:text-4xl font-bold text-primary mt-4 mb-4">Serving the Wimbledon Community Since 2008</h2><div className="gold-line mb-6"></div><p className="text-lg text-gray-600 mb-6 leading-relaxed">Wimbledon Legal Services was established with a commitment to providing high-quality legal advice that is accessible and affordable. Located on The Broadway, steps from Wimbledon station, we have been a trusted part of the local community for over fifteen years.</p><p className="text-gray-600 mb-6 leading-relaxed">Our team of experienced solicitors covers a broad range of practice areas, from property and family law to employment, commercial matters and immigration. We pride ourselves on taking the time to understand each client&apos;s unique circumstances and providing advice that is both practical and compassionate.</p><p className="text-gray-600 leading-relaxed">As a Law Society accredited practice, we maintain the highest professional standards. We also offer legal aid for eligible family law and immigration cases, ensuring that access to justice is not determined by financial means alone.</p></div><div className="bg-gray-50 p-8 lg:p-12 rounded-sm"><div className="grid grid-cols-2 gap-8"><div className="text-center p-6 bg-white rounded-sm shadow-sm"><div className="stat-number">15+</div><p className="text-gray-600 mt-2 font-medium">Years of Service</p></div><div className="text-center p-6 bg-white rounded-sm shadow-sm"><div className="stat-number">3,000+</div><p className="text-gray-600 mt-2 font-medium">Cases Handled</p></div><div className="text-center p-6 bg-white rounded-sm shadow-sm"><div className="stat-number">98%</div><p className="text-gray-600 mt-2 font-medium">Client Satisfaction</p></div><div className="text-center p-6 bg-white rounded-sm shadow-sm"><div className="stat-number">6</div><p className="text-gray-600 mt-2 font-medium">Practice Areas</p></div></div></div></div></div></section>

      <section className="section-padding bg-gray-50"><div className="container-width"><div className="text-center mb-16"><span className="text-accent font-semibold tracking-wider uppercase text-sm">Our Values</span><h2 className="text-3xl md:text-4xl font-bold text-primary mt-4 mb-4">What Sets Us Apart</h2><div className="gold-line-center mb-6"></div></div><div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
        <div className="card-premium p-8"><div className="w-16 h-16 bg-primary/10 rounded-full flex items-center justify-center mb-6"><svg className="w-8 h-8 text-primary" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M8 12h.01M12 12h.01M16 12h.01M21 12c0 4.418-4.03 8-9 8a9.863 9.863 0 01-4.255-.949L3 20l1.395-3.72C3.512 15.042 3 13.574 3 12c0-4.418 4.03-8 9-8s9 3.582 9 8z" /></svg></div><h3 className="text-xl font-bold text-primary mb-3">Plain English</h3><p className="text-gray-600">We explain the law in clear, understandable language. No legal jargon, no confusing terminology - just straightforward advice you can act on.</p></div>
        <div className="card-premium p-8"><div className="w-16 h-16 bg-primary/10 rounded-full flex items-center justify-center mb-6"><svg className="w-8 h-8 text-primary" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" /></svg></div><h3 className="text-xl font-bold text-primary mb-3">Regulated Standards</h3><p className="text-gray-600">SRA regulation means professional indemnity insurance, strict ethical standards and protections you can rely on. Your interests are always safeguarded.</p></div>
        <div className="card-premium p-8"><div className="w-16 h-16 bg-primary/10 rounded-full flex items-center justify-center mb-6"><svg className="w-8 h-8 text-primary" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1M21 12a9 9 0 11-18 0 9 9 0 0118 0z" /></svg></div><h3 className="text-xl font-bold text-primary mb-3">Affordable Access</h3><p className="text-gray-600">Fixed fees for most matters and legal aid for eligible cases. We believe quality legal advice should be accessible to everyone.</p></div>
        <div className="card-premium p-8"><div className="w-16 h-16 bg-primary/10 rounded-full flex items-center justify-center mb-6"><svg className="w-8 h-8 text-primary" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M12 4.354a4 4 0 110 5.292M15 21H3v-1a6 6 0 0112 0v1zm0 0h6v-1a6 6 0 00-9-5.197M13 7a4 4 0 11-8 0 4 4 0 018 0z" /></svg></div><h3 className="text-xl font-bold text-primary mb-3">Dedicated Solicitor</h3><p className="text-gray-600">Every client works with a named solicitor who knows your case inside out. No being passed between departments or speaking to strangers.</p></div>
        <div className="card-premium p-8"><div className="w-16 h-16 bg-primary/10 rounded-full flex items-center justify-center mb-6"><svg className="w-8 h-8 text-primary" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z" /><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M15 11a3 3 0 11-6 0 3 3 0 016 0z" /></svg></div><h3 className="text-xl font-bold text-primary mb-3">Local Knowledge</h3><p className="text-gray-600">Based on The Broadway since 2008, we understand the Wimbledon community and have established relationships with local courts and professionals.</p></div>
        <div className="card-premium p-8"><div className="w-16 h-16 bg-primary/10 rounded-full flex items-center justify-center mb-6"><svg className="w-8 h-8 text-primary" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M13 10V3L4 14h7v7l9-11h-7z" /></svg></div><h3 className="text-xl font-bold text-primary mb-3">Responsive Service</h3><p className="text-gray-600">We return calls and emails within the same working day. When your legal matter is urgent, you need a solicitor who responds quickly.</p></div>
      </div></div></section>

      <section className="section-padding bg-white"><div className="container-width"><div className="text-center mb-16"><span className="text-accent font-semibold tracking-wider uppercase text-sm">Our Location</span><h2 className="text-3xl md:text-4xl font-bold text-primary mt-4 mb-4">Find Us on The Broadway</h2><div className="gold-line-center mb-6"></div><p className="text-lg text-gray-600 max-w-3xl mx-auto">Our office is centrally located on The Broadway, Wimbledon, just minutes from Wimbledon station and the town centre.</p></div><div className="bg-gray-50 p-8 lg:p-12 rounded-sm border-t-4 border-accent max-w-2xl mx-auto"><address className="not-italic text-gray-700 text-lg mb-4"><strong>Wimbledon Legal Services</strong><br />26 The Broadway<br />Wimbledon, London SW19 1RE</address><p className="text-gray-600 mb-2"><strong>Opening Hours:</strong></p><p className="text-gray-600">Monday &ndash; Friday: 9:00am &ndash; 5:30pm</p><p className="text-gray-600 mb-4">Saturday &amp; Sunday: Closed (emergency appointments available)</p><p className="text-sm text-gray-500">Nearest station: Wimbledon (District line, Thameslink, tram). Town centre car parks nearby.</p></div></div></section>

      <section className="section-padding bg-primary"><div className="container-width text-center"><h2 className="text-3xl md:text-4xl font-bold text-white mb-4">Need Legal Advice?</h2><p className="text-xl text-gray-200 mb-8 max-w-2xl mx-auto">Book a free initial consultation and speak with one of our experienced solicitors about your legal matter.</p><div className="flex flex-col sm:flex-row justify-center gap-4"><Link href="/solicitor-wimbledon/contact" className="btn-accent">Free Initial Consultation</Link><a href="tel:02079464567" className="btn-outline border-white text-white hover:bg-white hover:text-primary">Call 020 7946 4567</a></div></div></section>
    </>
  );
}
