import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Services | Eye Tests, Contact Lenses & Designer Frames",
  description: "Comprehensive eye care services at Brixton Eye Care. Eye examinations, contact lens fitting, designer frames, children's eye care, emergency care, and DVLA screening.",
  openGraph: { title: "Services | Brixton Eye Care", description: "Full range of eye care services. NHS and private eye tests, contact lenses, designer frames, and emergency eye care in Brixton." },
};

export default function ServicesPage() {
  const services = [
    { id: "eye-examinations", title: "Eye Examinations", subtitle: "Thorough, Unhurried, Advanced", description: "Our comprehensive eye examinations last a full 30 minutes — significantly longer than the industry average. We use OCT scanning to examine the layers of your retina, digital retinal photography to create a permanent record of your eye health, and visual field testing to check your peripheral vision. Every examination includes checks for glaucoma, cataracts, macular degeneration, and diabetes-related eye conditions.", features: ["Full 30-minute examination with qualified optometrist", "OCT scan and retinal photography included as standard", "Visual field testing for glaucoma screening", "NHS and private appointments available", "Dilated eye examinations when clinically indicated", "Detailed explanation of results and recommendations"], icon: (<svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" /><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" /></svg>) },
    { id: "contact-lens-fitting", title: "Contact Lens Fitting", subtitle: "The Perfect Fit", description: "Whether you are a first-time wearer or looking to switch lenses, our contact lens specialists will find the ideal solution for your eyes and lifestyle. We fit all types of lenses including daily disposables, monthly lenses, toric lenses for astigmatism, and multifocal lenses for presbyopia. Every fitting includes insertion and removal training and a comprehensive aftercare plan.", features: ["Full range of daily, monthly, and extended wear lenses", "Specialist fitting for astigmatism and multifocal needs", "Free trial lenses to ensure comfort and vision", "Insertion and removal training for new wearers", "Six-month aftercare appointments included", "Competitive pricing on all major lens brands"], icon: (<svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>) },
    { id: "designer-frames", title: "Designer Frames", subtitle: "Style Meets Function", description: "Our dispensing opticians will help you find frames that complement your face shape, suit your prescription, and reflect your personal style. With over 500 frames in stock from leading brands, we have something for every taste and budget. All glazing is done in-house for fast turnaround and precise fitting.", features: ["Over 500 frames from brands including Ray-Ban, Tom Ford, and Prada", "Budget-friendly options starting from 49 pounds complete", "In-house glazing for fast turnaround", "Free adjustments and minor repairs for life", "Anti-reflection, blue-light filter, and photochromic lens options", "Two-for-one offers available on selected ranges"], icon: (<svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M4 6h16M4 10h16M4 14h16M4 18h16" /></svg>) },
    { id: "childrens-eye-care", title: "Children's Eye Care", subtitle: "Young Eyes, Expert Hands", description: "Children&apos;s eye care requires a different approach. Our optometrists are experienced in testing children from age three upwards, using child-friendly techniques and equipment. Early detection of vision problems is crucial for learning and development, which is why we recommend eye tests before starting school and every two years thereafter.", features: ["Free NHS eye tests for all children under 16", "Child-friendly testing techniques from age 3", "Specialist paediatric referral pathways when needed", "Wide range of durable children's frames", "Vision screening for school readiness", "Lazy eye (amblyopia) detection and monitoring"], icon: (<svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M12 4.354a4 4 0 110 5.292M15 21H3v-1a6 6 0 0112 0v1zm0 0h6v-1a6 6 0 00-9-5.197M13 7a4 4 0 11-8 0 4 4 0 018 0z" /></svg>) },
    { id: "emergency-eye-care", title: "Emergency Eye Care", subtitle: "When You Need Us Most", description: "Eye emergencies do not wait. We offer same-day appointments for urgent eye conditions including sudden vision loss, flashes and floaters, red or painful eyes, foreign bodies, and chemical splashes. Our optometrists can assess, treat, and refer to hospital eye services when necessary.", features: ["Same-day emergency appointments available", "Assessment of red eyes, pain, and sudden vision changes", "Foreign body removal", "Chemical splash first aid and management", "Direct referral to hospital eye services when needed", "Available during all opening hours including Saturdays"], icon: (<svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M13 10V3L4 14h7v7l9-11h-7z" /></svg>) },
    { id: "dvla-screening", title: "DVLA Screening", subtitle: "Drive with Confidence", description: "Need a vision test for your driving licence? We provide DVLA-standard visual acuity assessments and issue official certificates. The test takes around 15 minutes and results are available immediately. We also advise on whether your current spectacles meet driving standards.", features: ["DVLA-standard visual acuity testing", "Official certificate issued same day", "Assessment of current spectacles for driving compliance", "15-minute appointment — no need for a full eye test", "Walk-in availability subject to schedule", "Advice on driving-specific lens options"], icon: (<svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-6 9l2 2 4-4" /></svg>) },
  ];

  return (
    <>
      <section className="hero-gradient py-20 lg:py-28"><div className="container-width"><div className="max-w-3xl"><span className="text-accent font-semibold tracking-wider uppercase text-sm">Our Services</span><h1 className="text-4xl md:text-5xl font-bold text-white mt-4 mb-6">Eye Care Services</h1><p className="text-xl text-gray-200 leading-relaxed">Comprehensive eye care for the whole family. NHS and private appointments available with our experienced optometrists.</p></div></div></section>

      <section className="section-padding bg-white"><div className="container-width"><div className="text-center mb-16"><h2 className="text-3xl md:text-4xl font-bold text-primary mb-4">Complete Eye Care Under One Roof</h2><div className="gold-line-center mb-6"></div><p className="text-lg text-gray-600 max-w-3xl mx-auto">From routine check-ups to urgent eye concerns, our team of four GOC-registered optometrists provides expert care using the latest diagnostic technology.</p></div>
        <div className="space-y-16">{services.map((service, index) => (<div key={service.id} id={service.id} className={`grid lg:grid-cols-2 gap-12 items-center ${index % 2 === 1 ? "lg:flex-row-reverse" : ""}`}><div className={index % 2 === 1 ? "lg:order-2" : ""}><div className="text-primary mb-4">{service.icon}</div><h3 className="text-2xl md:text-3xl font-bold text-primary mb-2">{service.title}</h3><p className="text-accent font-semibold mb-4">{service.subtitle}</p><p className="text-gray-600 mb-6 leading-relaxed">{service.description}</p><ul className="space-y-3 mb-8">{service.features.map((f, i) => (<li key={i} className="flex items-start gap-3"><svg className="w-5 h-5 text-accent mt-0.5 flex-shrink-0" fill="currentColor" viewBox="0 0 20 20"><path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" /></svg><span className="text-gray-700">{f}</span></li>))}</ul><Link href="/optician-brixton/contact" className="btn-accent">Book Appointment</Link></div><div className={`bg-gray-50 p-8 lg:p-12 rounded-sm ${index % 2 === 1 ? "lg:order-1" : ""}`}><div className="aspect-video bg-gradient-to-br from-primary to-secondary rounded-sm flex items-center justify-center"><div className="text-white opacity-20 scale-150">{service.icon}</div></div></div></div>))}</div>
      </div></section>

      <section className="section-padding bg-gray-50"><div className="container-width"><div className="text-center mb-16"><span className="text-accent font-semibold tracking-wider uppercase text-sm">Your Appointment</span><h2 className="text-3xl md:text-4xl font-bold text-primary mt-4 mb-4">What to Expect</h2><div className="gold-line-center mb-6"></div></div>
        <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8">
          {[{ n: "1", t: "Book", d: "Call, email, or book online. We will find a time that works for you." }, { n: "2", t: "Arrive", d: "Come 5 minutes early. Bring your current glasses and any referral letters." }, { n: "3", t: "Examination", d: "Your optometrist conducts a thorough 30-minute eye health check." }, { n: "4", t: "Results", d: "We explain your results clearly and discuss any treatment or eyewear options." }].map((s, i) => (
            <div key={i} className="text-center"><div className="w-16 h-16 bg-primary text-white rounded-full flex items-center justify-center mx-auto mb-4 text-2xl font-bold font-serif">{s.n}</div><h3 className="text-xl font-bold text-primary mb-2">{s.t}</h3><p className="text-gray-600">{s.d}</p></div>
          ))}
        </div>
      </div></section>

      <section className="section-padding bg-primary"><div className="container-width text-center"><h2 className="text-3xl md:text-4xl font-bold text-white mb-4">Ready to Book Your Eye Test?</h2><p className="text-xl text-gray-200 mb-8 max-w-2xl mx-auto">Protect your vision with a comprehensive eye examination. NHS and private appointments available.</p><div className="flex flex-col sm:flex-row justify-center gap-4"><Link href="/optician-brixton/contact" className="btn-accent">Book Eye Test</Link><a href="tel:02079465520" className="btn-outline border-white text-white hover:bg-white hover:text-primary">Call 020 7946 5520</a></div></div></section>
    </>
  );
}
