import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "What We Offer | Wine Tastings, Events & Wine Club",
  description: "Explore Clapham Wine Room's services: guided wine tastings, cheese & charcuterie boards, wine by the glass, private events, wine club membership and corporate wine experiences.",
  openGraph: { title: "What We Offer | Clapham Wine Room", description: "Wine tastings, cheese boards, private events and wine club in Clapham." },
};

export default function ServicesPage() {
  const services = [
    { id: "wine-tastings", title: "Wine Tastings", subtitle: "Guided Discovery Evenings", description: "Our sommelier-led wine tastings are the heart of Clapham Wine Room. Every month, we host themed tasting evenings exploring different regions, grape varieties and styles. Each session includes six to eight wines, tasting notes, artisan snacks and a relaxed, sociable atmosphere. Whether you are a complete beginner or a seasoned oenophile, you will leave with new knowledge and new favourites.", features: ["Themed monthly tasting events (regions, grapes, food pairings)", "Six to eight wines per session with detailed tasting notes", "Led by our WSET-qualified resident sommelier", "Artisan snacks and cheese pairings included", "Small groups of 12-16 for an intimate experience", "Gift vouchers available for tasting events"], icon: (<svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M19.428 15.428a2 2 0 00-1.022-.547l-2.387-.477a6 6 0 00-3.86.517l-.318.158a6 6 0 01-3.86.517L6.05 15.21a2 2 0 00-1.806.547M8 4h8l-1 1v5.172a2 2 0 00.586 1.414l5 5c1.26 1.26.367 3.414-1.415 3.414H4.828c-1.782 0-2.674-2.154-1.414-3.414l5-5A2 2 0 009 10.172V5L8 4z" /></svg>) },
    { id: "cheese-charcuterie", title: "Cheese & Charcuterie Boards", subtitle: "The Perfect Pairing", description: "Our artisan cheese and charcuterie boards are sourced from the finest British and European producers. Each board is designed to complement our wines, with our sommelier happy to suggest the perfect pairing. From creamy Brie de Meaux to aged Comte, from bresaola to nduja — every board is a journey in itself.", features: ["Artisan British and European cheeses, hand-selected", "Premium charcuterie from trusted suppliers", "Seasonal accompaniments: chutneys, crackers, dried fruits", "Sommelier pairing suggestions for every board", "Vegetarian boards available with extra cheese selections", "Share boards for 2, 4 or larger groups"], icon: (<svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253" /></svg>) },
    { id: "wine-by-glass", title: "Wine by the Glass", subtitle: "Premium Pours, No Commitment", description: "Thanks to our Coravin preservation system, we can offer over 40 wines by the glass — including premium and rare bottles that most wine bars can only serve by the bottle. This means you can try a glass of fine Burgundy, a rare Barolo or an aged Rioja without committing to a full bottle. Our by-the-glass list rotates regularly, so there is always something new to discover.", features: ["40+ wines available by the glass", "Coravin system preserves wine quality, glass after glass", "Premium and rare wines available in single-glass pours", "Rotating selection to keep things fresh and exciting", "Flight options for tasting across regions or styles", "Expert staff to guide your selection"], icon: (<svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9.75 17L9 20l-1 1h8l-1-1-.75-3M3 13h18M5 17h14a2 2 0 002-2V5a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" /></svg>) },
    { id: "private-events", title: "Private Events", subtitle: "Your Celebration, Our Expertise", description: "The Clapham Wine Room is the perfect intimate venue for private celebrations. Whether it is a birthday, hen party, engagement celebration or just a special get-together, we offer exclusive venue hire with bespoke wine tasting packages. Our sommelier will work with you to create a tailored experience that your guests will remember long after the last glass.", features: ["Exclusive venue hire for up to 40 guests", "Bespoke wine tasting packages designed around your preferences", "Cheese and charcuterie catering included", "Sommelier-hosted events with fun, interactive elements", "Flexible packages to suit your budget", "Available Tuesday to Sunday, subject to availability"], icon: (<svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z" /></svg>) },
    { id: "wine-club", title: "Wine Club Membership", subtitle: "Great Wine, Delivered Monthly", description: "Our wine club is the easiest way to expand your palate. Each month, our sommelier selects two bottles you would never pick yourself — and we guarantee you will love them. Members also enjoy exclusive discounts at the bar, early access to tasting events, and invitations to members-only evenings. It is the gift that keeps on giving.", features: ["Two sommelier-selected bottles delivered monthly", "Detailed tasting notes and food pairing suggestions", "10% discount on all in-bar purchases", "Early access and priority booking for tasting events", "Exclusive members-only evenings quarterly", "Flexible subscription — pause or cancel anytime"], icon: (<svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1M21 12a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>) },
    { id: "corporate", title: "Corporate Wine Experiences", subtitle: "Team Building With Taste", description: "Looking for a corporate event with a difference? Our bespoke wine tasting experiences are perfect for team building, client entertaining or rewarding your team. Fun, educational and genuinely memorable, our corporate events can be hosted at our Clapham venue or at your offices anywhere in London.", features: ["Hosted at our venue or at your offices across London", "Bespoke themes: Old World vs New, Blind Tasting Challenge, etc.", "Fun, interactive format suitable for all knowledge levels", "Premium cheese and charcuterie catering included", "Professional sommelier host throughout", "Groups from 8 to 40 guests"], icon: (<svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M19 21V5a2 2 0 00-2-2H7a2 2 0 00-2 2v16m14 0h2m-2 0h-5m-9 0H3m2 0h5M9 7h1m-1 4h1m4-4h1m-1 4h1m-5 10v-5a1 1 0 011-1h2a1 1 0 011 1v5m-4 0h4" /></svg>) },
  ];

  return (
    <>
      <section className="hero-gradient py-20 lg:py-28"><div className="container-width"><div className="max-w-3xl"><span className="text-accent font-semibold tracking-wider uppercase text-sm">What We Offer</span><h1 className="text-4xl md:text-5xl font-bold text-white mt-4 mb-6">Wine Experiences for Every Occasion</h1><p className="text-xl text-gray-200 leading-relaxed">From casual glasses to curated tastings and private celebrations, discover everything Clapham Wine Room has to offer.</p></div></div></section>

      <section className="section-padding bg-white"><div className="container-width"><div className="text-center mb-16"><h2 className="text-3xl md:text-4xl font-bold text-primary mb-4">Our Services</h2><div className="gold-line-center mb-6"></div><p className="text-lg text-gray-600 max-w-3xl mx-auto">Every experience at Clapham Wine Room is curated by our sommelier to help you discover wines you will love.</p></div>
        <div className="space-y-16">{services.map((service, index) => (
          <div key={service.id} id={service.id} className={`grid lg:grid-cols-2 gap-12 items-center ${index % 2 === 1 ? "lg:flex-row-reverse" : ""}`}>
            <div className={index % 2 === 1 ? "lg:order-2" : ""}><div className="text-primary mb-4">{service.icon}</div><h3 className="text-2xl md:text-3xl font-bold text-primary mb-2">{service.title}</h3><p className="text-accent font-semibold mb-4">{service.subtitle}</p><p className="text-gray-600 mb-6 leading-relaxed">{service.description}</p><ul className="space-y-3 mb-8">{service.features.map((f, i) => (<li key={i} className="flex items-start gap-3"><svg className="w-5 h-5 text-accent mt-0.5 flex-shrink-0" fill="currentColor" viewBox="0 0 20 20"><path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" /></svg><span className="text-gray-700">{f}</span></li>))}</ul><Link href="/wine-bar-clapham/contact" className="btn-accent">Enquire Now</Link></div>
            <div className={`bg-gray-50 p-8 lg:p-12 rounded-sm ${index % 2 === 1 ? "lg:order-1" : ""}`}><div className="aspect-video bg-gradient-to-br from-primary to-secondary rounded-sm flex items-center justify-center"><div className="text-white opacity-20 scale-150">{service.icon}</div></div></div>
          </div>))}</div></div></section>

      <section className="section-padding bg-gray-50"><div className="container-width"><div className="text-center mb-16"><span className="text-accent font-semibold tracking-wider uppercase text-sm">Your Visit</span><h2 className="text-3xl md:text-4xl font-bold text-primary mt-4 mb-4">How It Works</h2><div className="gold-line-center mb-6"></div></div>
        <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8">
          <div className="text-center"><div className="w-16 h-16 bg-primary text-white rounded-full flex items-center justify-center mx-auto mb-4 text-2xl font-bold font-serif">1</div><h3 className="text-xl font-bold text-primary mb-2">Choose Your Experience</h3><p className="text-gray-600">Pop in for a glass, book a tasting event or plan a private celebration.</p></div>
          <div className="text-center"><div className="w-16 h-16 bg-primary text-white rounded-full flex items-center justify-center mx-auto mb-4 text-2xl font-bold font-serif">2</div><h3 className="text-xl font-bold text-primary mb-2">Let Us Guide You</h3><p className="text-gray-600">Our sommelier will recommend wines tailored to your preferences and palate.</p></div>
          <div className="text-center"><div className="w-16 h-16 bg-primary text-white rounded-full flex items-center justify-center mx-auto mb-4 text-2xl font-bold font-serif">3</div><h3 className="text-xl font-bold text-primary mb-2">Taste & Discover</h3><p className="text-gray-600">Explore new regions, grapes and styles in a relaxed, welcoming atmosphere.</p></div>
          <div className="text-center"><div className="w-16 h-16 bg-primary text-white rounded-full flex items-center justify-center mx-auto mb-4 text-2xl font-bold font-serif">4</div><h3 className="text-xl font-bold text-primary mb-2">Take It Home</h3><p className="text-gray-600">Found a favourite? Buy a bottle to take home, or join our wine club for monthly deliveries.</p></div>
        </div></div></section>

      <section className="section-padding bg-primary"><div className="container-width text-center"><h2 className="text-3xl md:text-4xl font-bold text-white mb-4">Ready to Discover Something New?</h2><p className="text-xl text-gray-200 mb-8 max-w-2xl mx-auto">Book a tasting, enquire about private events or just pop in for a glass. We would love to share our passion for wine with you.</p><div className="flex flex-col sm:flex-row justify-center gap-4"><Link href="/wine-bar-clapham/contact" className="btn-accent">Get in Touch</Link><a href="tel:02079469930" className="btn-outline border-white text-white hover:bg-white hover:text-primary">Call 020 7946 9930</a></div></div></section>
    </>
  );
}
