import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = { title: "About Us | Independent Bookshop Since 2009", description: "The story of Bloomsbury Books — an independent bookshop on Great Russell Street since 2009. 20,000+ titles, monthly events, and a community of readers.", openGraph: { title: "About Us | Bloomsbury Books", description: "Independent bookshop in the heart of literary London since 2009." } };

export default function AboutPage() {
  return (
    <>
      <section className="hero-gradient py-20 lg:py-28"><div className="container-width"><div className="max-w-3xl"><span className="text-accent font-semibold tracking-wider uppercase text-sm">About Us</span><h1 className="text-4xl md:text-5xl font-bold text-white mt-4 mb-6">Stories Worth Finding Since 2009</h1><p className="text-xl text-gray-200 leading-relaxed">An independent bookshop on Great Russell Street, championing brilliant writing and building a community of readers in the heart of literary London.</p></div></div></section>

      <section className="section-padding bg-white"><div className="container-width"><div className="grid lg:grid-cols-2 gap-16 items-center">
        <div><span className="text-accent font-semibold tracking-wider uppercase text-sm">Our Story</span><h2 className="text-3xl md:text-4xl font-bold text-primary mt-4 mb-4">Born from a Love of Books</h2><div className="gold-line mb-6"></div>
          <p className="text-lg text-gray-600 mb-6 leading-relaxed">Bloomsbury Books opened in 2009 in a former stationers on Great Russell Street, just around the corner from the British Museum. The founder&apos;s vision was simple: create a bookshop where every title on the shelf was there because someone had read it and believed in it, not because an algorithm predicted it would sell.</p>
          <p className="text-gray-600 mb-6 leading-relaxed">That principle has guided us ever since. We grew steadily through the support of local readers, literary tourists visiting the British Museum, and a growing events programme that brought authors directly to our upstairs space. Word spread through the literary community, and today we are regarded as one of London&apos;s finest independent bookshops.</p>
          <p className="text-gray-600 leading-relaxed">Over sixteen years we have hosted hundreds of author events, built a thriving book club, developed a rare books collection that draws collectors from across the country, and — most importantly — put the right book into the right hands tens of thousands of times. That is what a good bookshop does, and we intend to keep doing it for many years to come.</p>
        </div>
        <div className="bg-gray-50 p-8 lg:p-12 rounded-sm"><div className="grid grid-cols-2 gap-8">
          <div className="text-center p-6 bg-white rounded-sm shadow-sm"><div className="stat-number">16+</div><p className="text-gray-600 mt-2 font-medium">Years Independent</p></div>
          <div className="text-center p-6 bg-white rounded-sm shadow-sm"><div className="stat-number">20k+</div><p className="text-gray-600 mt-2 font-medium">Titles in Stock</p></div>
          <div className="text-center p-6 bg-white rounded-sm shadow-sm"><div className="stat-number">100+</div><p className="text-gray-600 mt-2 font-medium">Events Per Year</p></div>
          <div className="text-center p-6 bg-white rounded-sm shadow-sm"><div className="stat-number">7</div><p className="text-gray-600 mt-2 font-medium">Days Open</p></div>
        </div></div>
      </div></div></section>

      <section className="section-padding bg-gray-50"><div className="container-width"><div className="text-center mb-16"><span className="text-accent font-semibold tracking-wider uppercase text-sm">Our Values</span><h2 className="text-3xl md:text-4xl font-bold text-primary mt-4 mb-4">What We Stand For</h2><div className="gold-line-center mb-6"></div></div>
        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
          <div className="card-premium p-8"><div className="w-16 h-16 bg-primary/10 rounded-full flex items-center justify-center mb-6"><svg className="w-8 h-8 text-primary" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253" /></svg></div><h3 className="text-xl font-bold text-primary mb-3">Curation Over Commerce</h3><p className="text-gray-600">We stock what we love, not what sells fastest. Our shelves are a reflection of our booksellers&apos; taste, knowledge, and reading lives.</p></div>
          <div className="card-premium p-8"><div className="w-16 h-16 bg-primary/10 rounded-full flex items-center justify-center mb-6"><svg className="w-8 h-8 text-primary" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z" /></svg></div><h3 className="text-xl font-bold text-primary mb-3">Community First</h3><p className="text-gray-600">A bookshop should be a gathering place. Events, book club, story time — these are not extras, they are central to who we are.</p></div>
          <div className="card-premium p-8"><div className="w-16 h-16 bg-primary/10 rounded-full flex items-center justify-center mb-6"><svg className="w-8 h-8 text-primary" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z" /></svg></div><h3 className="text-xl font-bold text-primary mb-3">Personal Recommendations</h3><p className="text-gray-600">Ask any of our booksellers what to read next and they will give you an answer worth listening to. That is a service no website can match.</p></div>
          <div className="card-premium p-8"><div className="w-16 h-16 bg-primary/10 rounded-full flex items-center justify-center mb-6"><svg className="w-8 h-8 text-primary" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M3.055 11H5a2 2 0 012 2v1a2 2 0 002 2 2 2 0 012 2v2.945M8 3.935V5.5A2.5 2.5 0 0010.5 8h.5a2 2 0 012 2 2 2 0 104 0 2 2 0 012-2h1.064M15 20.488V18a2 2 0 012-2h3.064M21 12a9 9 0 11-18 0 9 9 0 0118 0z" /></svg></div><h3 className="text-xl font-bold text-primary mb-3">Supporting Authors</h3><p className="text-gray-600">We champion debut writers and independent publishers. Our events programme gives new voices a platform alongside established names.</p></div>
          <div className="card-premium p-8"><div className="w-16 h-16 bg-primary/10 rounded-full flex items-center justify-center mb-6"><svg className="w-8 h-8 text-primary" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" /></svg></div><h3 className="text-xl font-bold text-primary mb-3">Longevity</h3><p className="text-gray-600">Sixteen years and counting. In an age of closures, we have grown steadily because our readers value what we do and keep coming back.</p></div>
          <div className="card-premium p-8"><div className="w-16 h-16 bg-primary/10 rounded-full flex items-center justify-center mb-6"><svg className="w-8 h-8 text-primary" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M5 3v4M3 5h4M6 17v4m-2-2h4m5-16l2.286 6.857L21 12l-5.714 2.143L13 21l-2.286-6.857L5 12l5.714-2.143L13 3z" /></svg></div><h3 className="text-xl font-bold text-primary mb-3">Discovery</h3><p className="text-gray-600">The best books find you when you are not looking. Our shop is designed for serendipity — the unexpected title that changes how you think.</p></div>
        </div>
      </div></section>

      <section className="section-padding bg-white"><div className="container-width"><div className="text-center mb-16"><span className="text-accent font-semibold tracking-wider uppercase text-sm">Find Us</span><h2 className="text-3xl md:text-4xl font-bold text-primary mt-4 mb-4">Our Bloomsbury Home</h2><div className="gold-line-center mb-6"></div><p className="text-lg text-gray-600 max-w-3xl mx-auto">We are on Great Russell Street, steps from the British Museum. Three minutes from Tottenham Court Road tube, four from Russell Square, and five from Holborn.</p></div>
        <div className="bg-gray-50 p-8 lg:p-12 rounded-sm border-t-4 border-accent max-w-2xl mx-auto"><address className="not-italic text-gray-700 mb-4 text-center"><strong className="text-primary text-lg">Bloomsbury Books</strong><br />38 Great Russell Street<br />Bloomsbury, London WC1B 3QQ</address><div className="text-center text-gray-600"><p className="mb-2"><strong>Opening Hours:</strong></p><p>Mon-Sat: 9:30am - 7pm</p><p>Sun: 11am - 5pm</p></div></div>
      </section>

      <section className="section-padding bg-primary"><div className="container-width text-center"><h2 className="text-3xl md:text-4xl font-bold text-white mb-4">Come and Browse</h2><p className="text-xl text-gray-200 mb-8 max-w-2xl mx-auto">We are open seven days a week. There is always something new on the shelves and our booksellers are always happy to help.</p><div className="flex flex-col sm:flex-row justify-center gap-4"><Link href="/bookshop-bloomsbury/contact" className="btn-accent">Plan Your Visit</Link><a href="tel:02079461190" className="btn-outline border-white text-white hover:bg-white hover:text-primary">Call 020 7946 1190</a></div></div></section>
    </>
  );
}
