import type { Metadata } from "next";
import Link from "next/link";
export const metadata: Metadata = { title: "FAQ | Garden Design Questions Answered", description: "Frequently asked questions about garden design, landscaping, costs and working with Richmond Garden Design.", openGraph: { title: "FAQ | Richmond Garden Design", description: "Common questions about garden design services, costs and processes answered." } };

export default function FAQPage() {
  const faqs = [
    { category: "Garden Design Process", questions: [
      { question: "How does the design process work?", answer: "It begins with a free initial consultation where we visit your garden, listen to your ideas and discuss your budget. We then produce concept designs with mood boards and sketches. After your feedback, we develop detailed technical drawings and planting plans. Finally, we oversee the landscaping and planting to bring the design to life." },
      { question: "How long does a garden design take?", answer: "The design phase typically takes 4-8 weeks depending on the size and complexity of the garden. Construction timescales vary, but a typical back garden project takes 3-6 weeks to build. We will give you a clear timeline at the start of every project." },
      { question: "Do you only design or do you build as well?", answer: "We are primarily a design studio, but we work with a select group of trusted landscaping contractors who build our designs. We oversee the construction process to ensure the finished garden matches the design precisely. This gives you the benefit of specialist designers and specialist builders." },
      { question: "Can you work with my existing landscaper?", answer: "Absolutely. If you have a preferred landscaper, we can produce detailed technical drawings for them to work from. We are happy to brief them and remain available for queries during construction." },
    ] },
    { category: "Costs & Budget", questions: [
      { question: "How much does garden design cost?", answer: "Design fees depend on the size of the garden and scope of work. As a guide, our fees for a typical London back garden design start from around two thousand pounds. This includes the initial consultation, concept designs, detailed plans and planting schemes. We will provide a clear fee proposal after our first meeting." },
      { question: "How much should I budget for the full garden build?", answer: "Build costs vary enormously depending on materials, size and complexity. As a rough guide, a well-designed London garden build typically costs between five hundred and one thousand pounds per square metre. We can design to any budget and will always be transparent about likely costs." },
      { question: "Is the initial consultation free?", answer: "Yes, our initial consultation is completely free and without obligation. We visit your garden, discuss your ideas and aspirations, and give you an honest assessment of what is possible within your budget." },
    ] },
    { category: "Planting & Maintenance", questions: [
      { question: "Will you choose plants that suit my garden?", answer: "Absolutely. We assess your soil type, aspect, sunlight levels and microclimate before selecting a single plant. We also take into account your preferences, any allergies, whether you have children or pets, and how much time you want to spend maintaining the garden." },
      { question: "Do you offer ongoing garden maintenance?", answer: "Yes, we offer seasonal maintenance programmes tailored to your garden. This includes pruning, lawn care, border maintenance, planting top-ups and general seasonal care. Regular maintenance ensures your garden matures beautifully and reaches its full potential." },
      { question: "Can you design a low-maintenance garden?", answer: "Yes, low maintenance does not mean low interest. We can design gardens using evergreen structures, ground-cover planting, gravel gardens, drought-tolerant species and automated irrigation to minimise the time you need to spend on upkeep while still creating a beautiful space." },
    ] },
    { category: "Practical Questions", questions: [
      { question: "Do I need planning permission for a new garden?", answer: "Most garden works do not require planning permission, but there are exceptions, particularly if your property is listed or in a conservation area, or if you are making significant changes to levels, boundaries or drainage. We will advise you on this during our initial consultation." },
      { question: "What happens in winter?", answer: "Garden construction can continue through winter for most hard landscaping works. Planting is best done in spring or autumn depending on the species. We plan project timelines to align planting with the optimal season for establishment." },
      { question: "Do you design small gardens and balconies?", answer: "Yes, some of our favourite projects have been compact urban gardens, roof terraces and balconies. Small spaces often benefit the most from professional design because every element has to work twice as hard. We love the creative challenge." },
    ] },
  ];
  const faqSchema = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faqs.flatMap((c) => c.questions.map((q) => ({ "@type": "Question", name: q.question, acceptedAnswer: { "@type": "Answer", text: q.answer } }))) };

  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} />
      <section className="hero-gradient py-20 lg:py-28"><div className="container-width"><div className="max-w-3xl"><span className="text-accent font-semibold tracking-wider uppercase text-sm">FAQ</span><h1 className="text-4xl md:text-5xl font-bold text-white mt-4 mb-6">Frequently Asked Questions</h1><p className="text-xl text-gray-200 leading-relaxed">Find answers to common questions about garden design, our process, costs and how we can help transform your outdoor space.</p></div></div></section>
      <section className="section-padding bg-white"><div className="container-width"><div className="max-w-4xl mx-auto">{faqs.map((c, ci) => (<div key={ci} className="mb-12"><h2 className="text-2xl font-bold text-primary mb-6 flex items-center gap-3"><div className="w-1 h-8 bg-accent"></div>{c.category}</h2><div className="space-y-1">{c.questions.map((f, fi) => (<details key={fi} className="group bg-gray-50 rounded-sm overflow-hidden"><summary className="faq-question p-6 list-none cursor-pointer"><span className="flex-1 pr-4">{f.question}</span><svg className="w-5 h-5 text-accent flex-shrink-0 transition-transform duration-300 group-open:rotate-180" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" /></svg></summary><div className="px-6 pb-6"><p className="text-gray-600 leading-relaxed">{f.answer}</p></div></details>))}</div></div>))}</div></div></section>
      <section className="section-padding bg-gray-50"><div className="container-width"><div className="max-w-3xl mx-auto text-center"><h2 className="text-3xl font-bold text-primary mb-4">Still Have Questions?</h2><div className="gold-line-center mb-6"></div><p className="text-lg text-gray-600 mb-8">We&apos;re always happy to chat about your garden. Get in touch and we will do our best to help.</p><div className="flex flex-col sm:flex-row justify-center gap-4"><Link href="/garden-designer-richmond/contact" className="btn-accent">Contact Us</Link><a href="tel:02079463340" className="btn-outline">Call 020 7946 3340</a></div></div></div></section>
      <section className="section-padding bg-primary"><div className="container-width text-center"><h2 className="text-3xl md:text-4xl font-bold text-white mb-4">Ready for Your Dream Garden?</h2><p className="text-xl text-gray-200 mb-8 max-w-2xl mx-auto">Book a free consultation to discuss your garden vision with our award-winning design team.</p><Link href="/garden-designer-richmond/contact" className="btn-accent">Book Consultation</Link></div></section>
    </>
  );
}
