import type { Metadata } from "next";
import Link from "next/link";
export const metadata: Metadata = { title: "FAQ | Speech Therapy Questions Answered", description: "Frequently asked questions about speech and language therapy, referrals, costs and what to expect from Hampstead Speech Therapy.", openGraph: { title: "FAQ | Hampstead Speech Therapy", description: "Common questions about speech therapy services, referrals and what to expect." } };

export default function FAQPage() {
  const faqs = [
    { category: "Getting Started", questions: [
      { question: "Do I need a GP referral to see you?", answer: "No, you do not need a GP referral. You can contact us directly to book an appointment. Many of our clients are self-referred. However, if you have been referred by a GP, paediatrician, health visitor or school, we are happy to accept those referrals too." },
      { question: "What happens at the first appointment?", answer: "The first appointment is a comprehensive assessment. For children, this usually involves a combination of play-based activities, standardised assessments and discussion with parents or carers. For adults, we use a combination of conversation, standardised tests and clinical observation. We take time to understand the full picture before recommending a therapy plan." },
      { question: "How long does an assessment take?", answer: "An initial assessment typically takes between 60 and 90 minutes. This gives us enough time to carry out a thorough evaluation and discuss the results with you. Following the assessment, we provide a detailed written report with our findings, diagnosis and recommendations." },
      { question: "How often will I need to attend therapy?", answer: "This depends on the nature and severity of the difficulty. Most clients attend weekly or fortnightly sessions. Each session lasts between 30 and 60 minutes depending on the type of therapy and the age of the client. We will discuss the recommended frequency with you after the assessment." },
    ] },
    { category: "Costs & Practicalities", questions: [
      { question: "How much does speech therapy cost?", answer: "Our assessment fees and session fees depend on the type and length of appointment. We provide a clear fee schedule before you commit to anything. Many private health insurance policies cover speech and language therapy, and we can provide invoices and reports for insurance claims. Please contact us for our current fee schedule." },
      { question: "Do you accept health insurance?", answer: "We are recognised by most major health insurers including Bupa, AXA PPP, Aviva, Cigna and WPA. We can invoice your insurer directly in many cases. Please check with your insurer whether speech and language therapy is covered under your policy and whether you need a GP referral for insurance purposes." },
      { question: "Can I claim therapy on my health insurance?", answer: "Yes, in most cases. You will need to check your specific policy for speech and language therapy cover. Some policies require a GP referral letter. We provide detailed invoices and clinical reports to support your claim. Our clinic is registered with all major insurers." },
      { question: "What is your cancellation policy?", answer: "We ask for at least 24 hours notice if you need to cancel or reschedule an appointment. Appointments cancelled with less than 24 hours notice or missed without notification may be charged at the full session fee. We understand that life sometimes gets in the way, so please just let us know as soon as possible." },
    ] },
    { category: "Children's Therapy", questions: [
      { question: "At what age should I be concerned about my child's speech?", answer: "Every child develops at their own pace, but there are general milestones to be aware of. If your child is not babbling by 12 months, not using any words by 18 months, not combining words by age two, or is very difficult to understand by age three, it is worth seeking advice. However, you can contact us at any age if you have concerns. Early intervention often leads to the best outcomes." },
      { question: "Will my child need to miss school for therapy?", answer: "Not necessarily. We offer after-school and Saturday morning appointments at our Hampstead clinic. We also provide school-based therapy across North London, where we visit your child's school during the school day. Many schools welcome this as it means therapy can be integrated into the school environment." },
      { question: "Can parents sit in on therapy sessions?", answer: "Absolutely. For younger children, we actively encourage parent involvement in sessions. This allows you to learn the strategies we are using so you can practise them at home. For older children and teenagers, we discuss what works best on a case-by-case basis, always respecting the young person's preferences." },
    ] },
    { category: "Adult Therapy", questions: [
      { question: "Can speech therapy help after a stroke?", answer: "Yes, speech and language therapy is a key part of stroke rehabilitation. We work with people who have aphasia, which affects the ability to speak, understand, read or write, as well as dysarthria, which affects the clarity of speech, and dysphagia, which affects swallowing. Therapy can be effective months or even years after a stroke, so it is never too late to seek help." },
      { question: "I have stammered since childhood. Can therapy still help?", answer: "Yes, absolutely. Many of our adult stammering clients have tried therapy before and found it unhelpful. We use modern, evidence-based approaches that focus not just on fluency but on reducing the impact of stammering on your confidence, relationships and career. Many adults who stammer find that therapy with the right therapist can be genuinely life-changing." },
      { question: "Do you offer online therapy sessions?", answer: "Yes, we offer secure video therapy sessions for clients who prefer not to travel or who live outside the Hampstead area. Online therapy has been shown to be just as effective as face-to-face therapy for many types of communication difficulty. We use a secure, GDPR-compliant video platform that works on any device." },
    ] },
  ];
  const faqSchema = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faqs.flatMap((c) => c.questions.map((q) => ({ "@type": "Question", name: q.question, acceptedAnswer: { "@type": "Answer", text: q.answer } }))) };

  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} />
      <section className="hero-gradient py-20 lg:py-28"><div className="container-width"><div className="max-w-3xl"><span className="text-accent font-semibold tracking-wider uppercase text-sm">FAQ</span><h1 className="text-4xl md:text-5xl font-bold text-white mt-4 mb-6">Frequently Asked Questions</h1><p className="text-xl text-gray-200 leading-relaxed">Find answers to common questions about speech therapy, referrals, costs and what to expect from your appointments with us.</p></div></div></section>
      <section className="section-padding bg-white"><div className="container-width"><div className="max-w-4xl mx-auto">{faqs.map((c, ci) => (<div key={ci} className="mb-12"><h2 className="text-2xl font-bold text-primary mb-6 flex items-center gap-3"><div className="w-1 h-8 bg-accent"></div>{c.category}</h2><div className="space-y-1">{c.questions.map((f, fi) => (<details key={fi} className="group bg-gray-50 rounded-sm overflow-hidden"><summary className="faq-question p-6 list-none cursor-pointer"><span className="flex-1 pr-4">{f.question}</span><svg className="w-5 h-5 text-accent flex-shrink-0 transition-transform duration-300 group-open:rotate-180" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" /></svg></summary><div className="px-6 pb-6"><p className="text-gray-600 leading-relaxed">{f.answer}</p></div></details>))}</div></div>))}</div></div></section>
      <section className="section-padding bg-gray-50"><div className="container-width"><div className="max-w-3xl mx-auto text-center"><h2 className="text-3xl font-bold text-primary mb-4">Still Have Questions?</h2><div className="gold-line-center mb-6"></div><p className="text-lg text-gray-600 mb-8">We are always happy to chat about your concerns. Get in touch and we will do our best to help.</p><div className="flex flex-col sm:flex-row justify-center gap-4"><Link href="/speech-therapist-hampstead/contact" className="btn-accent">Contact Us</Link><a href="tel:02079464450" className="btn-outline">Call 020 7946 4450</a></div></div></div></section>
      <section className="section-padding bg-primary"><div className="container-width text-center"><h2 className="text-3xl md:text-4xl font-bold text-white mb-4">Ready to Take the First Step?</h2><p className="text-xl text-gray-200 mb-8 max-w-2xl mx-auto">Book a consultation to discuss your concerns. No GP referral needed and we are always happy to have an initial conversation.</p><Link href="/speech-therapist-hampstead/contact" className="btn-accent">Book Consultation</Link></div></section>
    </>
  );
}
