import type { Metadata } from "next";
export const metadata: Metadata = { title: "Contact Us | Book a Free Garden Design Consultation", description: "Contact Richmond Garden Design for a free consultation. Visit our studio at 22 The Quadrant or call 020 7946 3340.", openGraph: { title: "Contact Us | Richmond Garden Design", description: "Book a free garden design consultation. Call 020 7946 3340 or visit our Richmond studio." } };

export default function ContactPage() {
  return (
    <>
      <section className="hero-gradient py-20 lg:py-28"><div className="container-width"><div className="max-w-3xl"><span className="text-accent font-semibold tracking-wider uppercase text-sm">Get In Touch</span><h1 className="text-4xl md:text-5xl font-bold text-white mt-4 mb-6">Contact Us</h1><p className="text-xl text-gray-200 leading-relaxed">Ready to discuss your garden project? Book a free consultation or simply drop us a line. We would love to hear from you.</p></div></div></section>

      <section className="section-padding bg-white"><div className="container-width"><div className="grid lg:grid-cols-2 gap-16">
        <div><h2 className="text-2xl md:text-3xl font-bold text-primary mb-2">Book Your Free Consultation</h2><p className="text-gray-600 mb-8">Tell us about your garden and we will arrange a convenient time to visit and discuss your ideas.</p>
          <form className="space-y-6">
            <div className="grid md:grid-cols-2 gap-6"><div><label htmlFor="firstName" className="form-label">First Name *</label><input type="text" id="firstName" name="firstName" required className="form-input" placeholder="Jane" /></div><div><label htmlFor="lastName" className="form-label">Last Name *</label><input type="text" id="lastName" name="lastName" required className="form-input" placeholder="Smith" /></div></div>
            <div className="grid md:grid-cols-2 gap-6"><div><label htmlFor="email" className="form-label">Email Address *</label><input type="email" id="email" name="email" required className="form-input" placeholder="jane@example.com" /></div><div><label htmlFor="phone" className="form-label">Phone Number *</label><input type="tel" id="phone" name="phone" required className="form-input" placeholder="07123 456789" /></div></div>
            <div><label htmlFor="service" className="form-label">Service of Interest</label><select id="service" name="service" className="form-input"><option value="">Select a service</option><option value="design">Garden Design</option><option value="planting">Planting Plans</option><option value="landscaping">Landscaping</option><option value="maintenance">Garden Maintenance</option><option value="lighting">Lighting Design</option><option value="water">Water Features</option><option value="other">Other / Not Sure</option></select></div>
            <div><label htmlFor="preferredDate" className="form-label">Preferred Consultation Date</label><input type="text" id="preferredDate" name="preferredDate" className="form-input" placeholder="e.g. Next Wednesday" /></div>
            <div><label htmlFor="message" className="form-label">Tell Us About Your Garden</label><textarea id="message" name="message" rows={5} className="form-textarea" placeholder="Garden size, current state, what you would like to achieve, any inspiration..."></textarea></div>
            <button type="submit" className="btn-accent w-full sm:w-auto">Request Consultation</button>
          </form>
        </div>
        <div><h2 className="text-2xl md:text-3xl font-bold text-primary mb-8">Our Studio</h2>
          <div className="location-card mb-8"><div className="flex items-center gap-3 mb-4"><div className="w-12 h-12 bg-primary/10 rounded-full flex items-center justify-center"><svg className="w-6 h-6 text-primary" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z" /><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 11a3 3 0 11-6 0 3 3 0 016 0z" /></svg></div><div><span className="text-sm text-primary font-semibold">Richmond</span><h3 className="text-xl font-bold text-primary">Design Studio</h3></div></div>
            <address className="not-italic text-gray-700 mb-4"><strong>Richmond Garden Design</strong><br />22 The Quadrant<br />Richmond<br />London TW9 1BP</address>
            <div className="space-y-2 text-gray-600 mb-4"><p><strong>Opening Hours:</strong><br />Monday - Friday: 9:00am - 5:30pm<br />Saturday: By appointment<br />Sunday: Closed</p></div></div>
          <div className="bg-gray-50 p-6 rounded-sm mb-8"><h3 className="text-lg font-bold text-primary mb-4">Direct Contact</h3><div className="space-y-4">
            <a href="tel:02079463340" className="flex items-center gap-3 text-gray-700 hover:text-accent transition-colors"><div className="w-10 h-10 bg-accent/10 rounded-full flex items-center justify-center"><svg className="w-5 h-5 text-accent" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 5a2 2 0 012-2h3.28a1 1 0 01.948.684l1.498 4.493a1 1 0 01-.502 1.21l-2.257 1.13a11.042 11.042 0 005.516 5.516l1.13-2.257a1 1 0 011.21-.502l4.493 1.498a1 1 0 01.684.949V19a2 2 0 01-2 2h-1C9.716 21 3 14.284 3 6V5z" /></svg></div><div><p className="font-semibold">020 7946 3340</p><p className="text-sm text-gray-500">Call during office hours</p></div></a>
            <a href="mailto:hello@richmondgardens.co.uk" className="flex items-center gap-3 text-gray-700 hover:text-accent transition-colors"><div className="w-10 h-10 bg-accent/10 rounded-full flex items-center justify-center"><svg className="w-5 h-5 text-accent" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" /></svg></div><div><p className="font-semibold">hello@richmondgardens.co.uk</p><p className="text-sm text-gray-500">Email us anytime</p></div></a>
          </div></div>
          <div className="bg-gray-50 p-6 rounded-sm"><h3 className="text-lg font-bold text-primary mb-4">Getting Here</h3><div className="space-y-3 text-gray-600">
            <div className="flex items-center gap-3"><svg className="w-5 h-5 text-accent flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z" /><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 11a3 3 0 11-6 0 3 3 0 016 0z" /></svg><p><strong>Richmond:</strong> 4-minute walk</p></div>
            <div className="flex items-center gap-3"><svg className="w-5 h-5 text-accent flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z" /><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 11a3 3 0 11-6 0 3 3 0 016 0z" /></svg><p><strong>North Sheen:</strong> 7-minute walk</p></div>
            <div className="flex items-center gap-3"><svg className="w-5 h-5 text-accent flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z" /><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 11a3 3 0 11-6 0 3 3 0 016 0z" /></svg><p><strong>Kew Gardens:</strong> 10-minute walk</p></div>
          </div></div>
        </div>
      </div></div></section>
    </>
  );
}
