import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Services | Dry Cleaning, Laundry, Wedding Dress Care & More",
  description: "Full range of dry cleaning and laundry services: garment cleaning, shirt service, wedding dress care, curtain cleaning, alterations and same-day express in Kensington.",
  openGraph: { title: "Services | Kensington Dry Cleaners", description: "Premium dry cleaning, shirt service, wedding dress care, alterations and same-day express on Kensington High Street." },
};

export default function ServicesPage() {
  const services = [
    { id: "dry-cleaning", title: "Dry Cleaning", subtitle: "Professional Garment Care", description: "Our core dry cleaning service uses GreenEarth eco-friendly solvents to clean suits, dresses, coats, jackets, trousers and delicate fabrics safely and effectively. Every garment is individually inspected for stains, damage and care requirements before processing. Items are finished by hand, pressed to perfection and returned on quality hangers with protective covers.", features: ["Eco-friendly GreenEarth silicone solvents", "Individual garment inspection and stain treatment", "Hand finishing and professional pressing", "Protective garment covers included", "Specialist care for silk, cashmere and wool", "Free collection and delivery available"], icon: <svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M5 3v4M3 5h4M6 17v4m-2-2h4m5-16l2.286 6.857L21 12l-5.714 2.143L13 21l-2.286-6.857L5 12l5.714-2.143L13 3z" /></svg> },
    { id: "shirt-service", title: "Shirt Service", subtitle: "Crisp, Professional Laundering", description: "Our dedicated shirt service is designed for busy professionals who expect impeccable presentation. Shirts are washed, starched to your preference and professionally pressed. Choose from hanger or boxed folded finish. We handle cotton, linen, poplin and performance fabrics with equal expertise.", features: ["Washed, starched and pressed to your preference", "Hanger or folded finish options", "Light, medium or heavy starch choices", "Button check and minor repair included", "Bulk discounts for five or more shirts", "48-hour standard or same-day express turnaround"], icon: <svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg> },
    { id: "wedding-dress", title: "Wedding Dress Care", subtitle: "Specialist Bridal Services", description: "Your wedding dress is one of the most precious garments you will ever own. Our specialist bridal team carefully cleans every layer of fabric, removes stains from the day, and can preserve your gown in an acid-free box for long-term storage. We also offer pre-wedding pressing and steaming to ensure you look flawless on your big day.", features: ["Pre-wedding pressing and steaming", "Post-wedding deep cleaning and stain removal", "Acid-free preservation boxing", "Veil and accessory cleaning", "Full consultation before any treatment", "Insured handling for complete peace of mind"], icon: <svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z" /></svg> },
    { id: "curtain-upholstery", title: "Curtain & Upholstery Cleaning", subtitle: "Refresh Your Home", description: "Curtains, blinds, cushion covers, throws and upholstered furniture all benefit from professional cleaning. We remove dust, allergens and odours, restoring freshness and colour to your soft furnishings. We offer a take-down and re-hang service for curtains and can advise on the best cleaning method for every fabric.", features: ["Curtain take-down and re-hang service", "Blind cleaning (roller, Roman, Venetian)", "Cushion covers, throws and sofa covers", "Dust mite and allergen removal", "Colour and fabric restoration", "On-site upholstery cleaning available"], icon: <svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6" /></svg> },
    { id: "alterations", title: "Alterations & Repairs", subtitle: "Expert Tailoring", description: "Our in-house seamstress handles everything from simple trouser hems to complex re-lining and garment restructuring. Whether you need a suit taken in, a zip replaced, or a vintage piece restored, we deliver precise, high-quality alterations that maintain the integrity of the original garment.", features: ["Trouser and skirt hems and shortening", "Jacket and dress taking in or letting out", "Zip replacement and button repairs", "Re-lining coats and jackets", "Bespoke alterations for a perfect fit", "Quick turnaround for urgent alterations"], icon: <svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M14.121 14.121L19 19m-7-7l7-7m-7 7l-2.879 2.879M12 12L9.121 9.121m0 5.758a3 3 0 10-4.243 4.243 3 3 0 004.243-4.243zm0-5.758a3 3 0 10-4.243-4.243 3 3 0 004.243 4.243z" /></svg> },
    { id: "same-day", title: "Same-Day Express", subtitle: "When Time Is of the Essence", description: "Life does not always run to plan. Our same-day express service ensures your garments are cleaned, pressed and ready by 5pm when dropped off before 10am. Ideal for last-minute events, unexpected business trips or when you simply cannot wait. A small surcharge applies, but the convenience is priceless.", features: ["Drop off before 10am, collect by 5pm", "Available for most garment types", "Full dry cleaning or press-only options", "Same high quality as our standard service", "Available in-store and via collection", "Small express surcharge applies"], icon: <svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M13 10V3L4 14h7v7l9-11h-7z" /></svg> },
  ];

  return (
    <>
      <section className="hero-gradient py-20 lg:py-28"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="max-w-3xl"><span className="text-[var(--accent)] font-semibold tracking-wider uppercase text-sm">Our Services</span><h1 className="text-4xl md:text-5xl font-bold text-white mt-4 mb-6">Premium Garment Care Services</h1><p className="text-xl text-gray-200 leading-relaxed">From everyday dry cleaning to specialist bridal care, we offer a comprehensive range of services to keep your wardrobe immaculate.</p></div></div></section>

      <section className="py-16 lg:py-24 bg-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16"><h2 className="text-3xl md:text-4xl font-bold text-[var(--primary)] mb-4">Everything Your Wardrobe Needs</h2><div className="w-16 h-1 bg-[var(--accent)] mx-auto mb-6"></div><p className="text-lg text-gray-600 max-w-3xl mx-auto">Every service uses our eco-friendly GreenEarth solvents and comes with our guarantee of immaculate care.</p></div>
          <div className="space-y-16">
            {services.map((service, index) => (
              <div key={service.id} id={service.id} className={`grid lg:grid-cols-2 gap-12 items-center ${index % 2 === 1 ? "lg:flex-row-reverse" : ""}`}>
                <div className={index % 2 === 1 ? "lg:order-2" : ""}><div className="text-[var(--accent)] mb-4">{service.icon}</div><h3 className="text-2xl md:text-3xl font-bold text-[var(--primary)] mb-2">{service.title}</h3><p className="text-[var(--accent)] font-semibold mb-4">{service.subtitle}</p><p className="text-gray-600 mb-6 leading-relaxed">{service.description}</p><ul className="space-y-3 mb-8">{service.features.map((f, i) => (<li key={i} className="flex items-start gap-3"><svg className="w-5 h-5 text-[var(--accent)] mt-0.5 flex-shrink-0" fill="currentColor" viewBox="0 0 20 20"><path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" /></svg><span className="text-gray-700">{f}</span></li>))}</ul><Link href="/dry-cleaner-kensington/contact" className="bg-[var(--accent)] text-white px-6 py-3 font-semibold rounded-sm hover:bg-[var(--accent-light)] transition-colors inline-block">Get a Quote</Link></div>
                <div className={`bg-gray-50 p-8 lg:p-12 rounded-sm ${index % 2 === 1 ? "lg:order-1" : ""}`}><div className="aspect-video bg-gradient-to-br from-[var(--primary)] to-[var(--secondary)] rounded-sm flex items-center justify-center"><div className="text-white opacity-20 scale-150">{service.icon}</div></div></div>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section className="py-16 lg:py-24 bg-gray-50"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="text-center mb-16"><span className="text-[var(--accent)] font-semibold tracking-wider uppercase text-sm">How It Works</span><h2 className="text-3xl md:text-4xl font-bold text-[var(--primary)] mt-4 mb-4">Simple, Convenient Service</h2><div className="w-16 h-1 bg-[var(--accent)] mx-auto mb-6"></div></div><div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8">
        <div className="text-center"><div className="w-16 h-16 bg-[var(--primary)] text-white rounded-full flex items-center justify-center mx-auto mb-4 text-2xl font-bold font-serif">1</div><h3 className="text-xl font-bold text-[var(--primary)] mb-2">Drop Off or Book</h3><p className="text-gray-600">Visit our shop on Kensington High Street or book a free collection from your home or office.</p></div>
        <div className="text-center"><div className="w-16 h-16 bg-[var(--primary)] text-white rounded-full flex items-center justify-center mx-auto mb-4 text-2xl font-bold font-serif">2</div><h3 className="text-xl font-bold text-[var(--primary)] mb-2">We Inspect &amp; Clean</h3><p className="text-gray-600">Every garment is individually assessed, stain-treated and cleaned using the appropriate eco-friendly process.</p></div>
        <div className="text-center"><div className="w-16 h-16 bg-[var(--primary)] text-white rounded-full flex items-center justify-center mx-auto mb-4 text-2xl font-bold font-serif">3</div><h3 className="text-xl font-bold text-[var(--primary)] mb-2">Hand Finished</h3><p className="text-gray-600">Items are pressed, finished by hand and quality-checked before being wrapped in protective covers.</p></div>
        <div className="text-center"><div className="w-16 h-16 bg-[var(--primary)] text-white rounded-full flex items-center justify-center mx-auto mb-4 text-2xl font-bold font-serif">4</div><h3 className="text-xl font-bold text-[var(--primary)] mb-2">Collect or Deliver</h3><p className="text-gray-600">Pick up from our shop or we deliver straight to your door, free of charge within our service area.</p></div>
      </div></div></section>

      <section className="py-16 lg:py-24 bg-[var(--primary)]"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center"><h2 className="text-3xl md:text-4xl font-bold text-white mb-4">Need Something Cleaned?</h2><p className="text-xl text-gray-200 mb-8 max-w-2xl mx-auto">Book a free collection or drop in to our Kensington High Street shop. Same-day express available.</p><div className="flex flex-col sm:flex-row justify-center gap-4"><Link href="/dry-cleaner-kensington/contact" className="bg-[var(--accent)] text-white px-8 py-4 font-semibold rounded-sm hover:bg-[var(--accent-light)] transition-colors">Book a Collection</Link><a href="tel:02079465530" className="border-2 border-white text-white px-8 py-4 font-semibold rounded-sm hover:bg-white hover:text-[var(--primary)] transition-colors">Call 020 7946 5530</a></div></div></section>
    </>
  );
}
