import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Tailoring Services | Bespoke Suits, Made-to-Measure & Shirts",
  description: "Bespoke tailoring services on Savile Row. Fully bespoke suits, made-to-measure, shirt making, alterations, wedding suits and corporate tailoring.",
  openGraph: { title: "Tailoring Services | Savile Row Bespoke", description: "Master tailoring services from Savile Row. Bespoke suits, made-to-measure, shirt making and more." },
};

export default function ServicesPage() {
  const services = [
    { id: "bespoke-suits", title: "Bespoke Suits", subtitle: "The Pinnacle of Tailoring", description: "A fully bespoke suit is created entirely from scratch to your unique measurements and specifications. Over the course of multiple fittings, our master tailor sculpts the garment to your body, ensuring a fit that is truly yours alone. Every detail, from the canvas construction to the hand-finished buttonholes, reflects decades of Savile Row expertise.", features: ["Individual paper pattern created for your body", "Choice of over 3,000 fabrics from leading mills", "Full canvas construction for superior drape", "Multiple fittings to achieve perfection", "Hand-finished buttonholes and details", "Minimum 60 hours of hand craftsmanship"], icon: <svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M5 3v4M3 5h4M6 17v4m-2-2h4m5-16l2.286 6.857L21 12l-5.714 2.143L13 21l-2.286-6.857L5 12l5.714-2.143L13 3z" /></svg> },
    { id: "made-to-measure", title: "Made-to-Measure", subtitle: "Precision Without Compromise", description: "Our made-to-measure service offers an exceptional fit from a curated selection of styles. Your measurements are taken and the garment is constructed to fit your individual body shape, with personalised details including fabric, lining, buttons and monogramming.", features: ["Precise body measurements taken in-house", "Curated selection of premium fabrics", "Personalised style details and trimmings", "One fitting to ensure perfect fit", "Ready in approximately 4-6 weeks", "Significantly more affordable than full bespoke"], icon: <svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M3 6l3 1m0 0l-3 9a5.002 5.002 0 006.001 0M6 7l3 9M6 7l6-2m6 2l3-1m-3 1l-3 9a5.002 5.002 0 006.001 0M18 7l3 9m-3-9l-6-2m0-2v2m0 16V5m0 16H9m3 0h3" /></svg> },
    { id: "shirt-making", title: "Shirt Making", subtitle: "The Foundation of Style", description: "A bespoke shirt is the foundation of any well-dressed man's wardrobe. Our shirt maker crafts each shirt from the finest Swiss and Italian cottons, with your choice of collar style, cuff design, placket and monogramming.", features: ["Finest Swiss and Italian cotton fabrics", "Choice of collar, cuff and placket styles", "Personalised monogramming available", "Mother-of-pearl buttons as standard", "Single-needle stitching throughout", "Minimum order of three shirts recommended"], icon: <svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M7 21a4 4 0 01-4-4V5a2 2 0 012-2h4a2 2 0 012 2v12a4 4 0 01-4 4zm0 0h12a2 2 0 002-2v-4a2 2 0 00-2-2h-2.343M11 7.343l1.657-1.657a2 2 0 012.828 0l2.829 2.829a2 2 0 010 2.828l-8.486 8.485M7 17h.01" /></svg> },
    { id: "alterations-repairs", title: "Alterations & Repairs", subtitle: "Perfect Fit, Extended Life", description: "Whether adjusting an existing garment for a better fit or restoring a treasured piece, our expert tailors handle alterations and repairs with the same care and precision we bring to new commissions.", features: ["Suit and jacket alterations", "Trouser adjustments and re-styling", "Weight change adaptations", "Relining and re-canvassing", "Vintage garment restoration", "Zip and button replacements"], icon: <svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M14.121 14.121L19 19m-7-7l7-7m-7 7l-2.879 2.879M12 12L9.121 9.121m0 5.758a3 3 0 10-4.243 4.243 3 3 0 004.243-4.243zm0-5.758a3 3 0 10-4.243-4.243 3 3 0 004.243 4.243z" /></svg> },
    { id: "wedding-suits", title: "Wedding Suits", subtitle: "Your Perfect Day, Perfectly Dressed", description: "Your wedding suit should be as memorable as the day itself. We work with grooms and wedding parties to create bespoke or made-to-measure suits that capture the formality and personality of the occasion.", features: ["Bespoke or made-to-measure options", "Matching suits for the wedding party", "Waistcoats and accessories included", "Morning suits and evening wear", "Allow 12-16 weeks for bespoke", "Fitting appointments at your convenience"], icon: <svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z" /></svg> },
    { id: "corporate-tailoring", title: "Corporate Tailoring", subtitle: "Dress to Impress", description: "First impressions matter in business. Our corporate tailoring service ensures your team looks polished and professional. We offer packages for executives, sales teams and entire organisations.", features: ["Bulk pricing for corporate clients", "On-site measuring at your office", "Consistent style across teams", "Account management and re-ordering", "Branded linings and details available", "Flexible fitting schedule"], icon: <svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M19 21V5a2 2 0 00-2-2H7a2 2 0 00-2 2v16m14 0h2m-2 0h-5m-9 0H3m2 0h5M9 7h1m-1 4h1m4-4h1m-1 4h1m-5 10v-5a1 1 0 011-1h2a1 1 0 011 1v5m-4 0h4" /></svg> },
  ];

  return (
    <>
      <section className="hero-gradient py-20 lg:py-28"><div className="container-width"><div className="max-w-3xl"><span className="text-accent font-semibold tracking-wider uppercase text-sm">Our Services</span><h1 className="text-4xl md:text-5xl font-bold text-white mt-4 mb-6">Bespoke Tailoring Services</h1><p className="text-xl text-gray-200 leading-relaxed">From fully bespoke suits to expert alterations, every service reflects our commitment to Savile Row excellence.</p></div></div></section>

      <section className="section-padding bg-white">
        <div className="container-width">
          <div className="text-center mb-16"><h2 className="text-3xl md:text-4xl font-bold text-primary mb-4">Crafted with Distinction</h2><div className="gold-line-center mb-6"></div><p className="text-lg text-gray-600 max-w-3xl mx-auto">Every garment is a collaboration between tailor and client. We listen, advise and craft to deliver something truly exceptional.</p></div>
          <div className="space-y-16">
            {services.map((service, index) => (
              <div key={service.id} id={service.id} className={`grid lg:grid-cols-2 gap-12 items-center ${index % 2 === 1 ? "lg:flex-row-reverse" : ""}`}>
                <div className={index % 2 === 1 ? "lg:order-2" : ""}>
                  <div className="text-primary mb-4">{service.icon}</div>
                  <h3 className="text-2xl md:text-3xl font-bold text-primary mb-2">{service.title}</h3>
                  <p className="text-accent font-semibold mb-4">{service.subtitle}</p>
                  <p className="text-gray-600 mb-6 leading-relaxed">{service.description}</p>
                  <ul className="space-y-3 mb-8">{service.features.map((f, i) => (<li key={i} className="flex items-start gap-3"><svg className="w-5 h-5 text-accent mt-0.5 flex-shrink-0" fill="currentColor" viewBox="0 0 20 20"><path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" /></svg><span className="text-gray-700">{f}</span></li>))}</ul>
                  <Link href="/tailor-savile-row/contact" className="btn-accent">Book a Consultation</Link>
                </div>
                <div className={`bg-gray-50 p-8 lg:p-12 rounded-sm ${index % 2 === 1 ? "lg:order-1" : ""}`}><div className="aspect-video bg-gradient-to-br from-primary to-secondary rounded-sm flex items-center justify-center"><div className="text-white opacity-20 scale-150">{service.icon}</div></div></div>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section className="section-padding bg-gray-50"><div className="container-width"><div className="text-center mb-16"><span className="text-accent font-semibold tracking-wider uppercase text-sm">The Process</span><h2 className="text-3xl md:text-4xl font-bold text-primary mt-4 mb-4">The Bespoke Journey</h2><div className="gold-line-center mb-6"></div></div>
        <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8">
          <div className="text-center"><div className="w-16 h-16 bg-primary text-white rounded-full flex items-center justify-center mx-auto mb-4 text-2xl font-bold font-serif">1</div><h3 className="text-xl font-bold text-primary mb-2">Consultation</h3><p className="text-gray-600">We discuss your requirements, style preferences and the occasion. Browse our fabric library over a glass of champagne.</p></div>
          <div className="text-center"><div className="w-16 h-16 bg-primary text-white rounded-full flex items-center justify-center mx-auto mb-4 text-2xl font-bold font-serif">2</div><h3 className="text-xl font-bold text-primary mb-2">Measuring</h3><p className="text-gray-600">Our master tailor takes detailed measurements and creates your individual paper pattern.</p></div>
          <div className="text-center"><div className="w-16 h-16 bg-primary text-white rounded-full flex items-center justify-center mx-auto mb-4 text-2xl font-bold font-serif">3</div><h3 className="text-xl font-bold text-primary mb-2">Fittings</h3><p className="text-gray-600">Multiple fittings ensure the garment is sculpted perfectly to your body. We refine every detail.</p></div>
          <div className="text-center"><div className="w-16 h-16 bg-primary text-white rounded-full flex items-center justify-center mx-auto mb-4 text-2xl font-bold font-serif">4</div><h3 className="text-xl font-bold text-primary mb-2">Delivery</h3><p className="text-gray-600">Your finished garment is presented, pressed and ready to wear. The transformation is complete.</p></div>
        </div>
      </div></section>

      <section className="section-padding bg-primary"><div className="container-width text-center"><h2 className="text-3xl md:text-4xl font-bold text-white mb-4">Begin Your Bespoke Journey</h2><p className="text-xl text-gray-200 mb-8 max-w-2xl mx-auto">Visit our Savile Row atelier for a private consultation. We&apos;ll guide you through every step of the process.</p><div className="flex flex-col sm:flex-row justify-center gap-4"><Link href="/tailor-savile-row/contact" className="btn-accent">Book a Consultation</Link><a href="tel:02079464789" className="btn-outline border-white text-white hover:bg-white hover:text-primary">Call 020 7946 4789</a></div></div></section>
    </>
  );
}
